### ISSUE TITLE
Units fails with a ssh connection error on Trestles

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#503] opened 2015-03-18 02:46 UTC
RP: aimes-experiments
SP: devel
RU: devel

Running a bag of 256 tasks, 8 cores each, late binding on 3 pilots of 683 cores each. The pilot on Trestles comes up first, some units - like 30% more or less - fail with the following in their STDERR:
```
ssh_exchange_identification: Connection closed by remote host
```
The scripts spits out here and there the following:
```
'5508d80523769c074c8038be' stderr: ssh_exchange_identification: Connection closed by remote host
.
'5508d80523769c074c8038be' stdout: .
[...]
'5508d81423769c074c803958' stderr: Connection closed by 10.1.255.238
.
[...]
```
Full log of the run is available if needed and the sandbox is retained for debugging.

**Comment by marksantcroos** [comment] 2015-03-18 06:50
Will try to reproduce.

Current guess, given that its not exclusively failing, changed host keys might be a cause.
Possible solution might be to use the MPI launcher for non-MPI tasks too.

**Comment by marksantcroos** [comment] 2015-03-19 11:35
I added tests/issue503.py to devel but can't reproduce so far.
Can you confirm that it mimics what you are doing?
And can you give the script a try?

**Comment by mturilli** [comment] 2015-03-19 12:15
Thank you. 

I see the following differences between issue503.py and my code:
* input file for each unit of 1048576 B and an output file of 20000 B. Input file is stages from origin (experiments VM) to Trestles, output file from Trestles to origin.
* I use late binding and the back filling scheduler.

Do you think these differences might be significant in the context of the observed error?

**Comment by marksantcroos** [comment] 2015-03-19 12:26
Tempted to say that neither of these matter at that stage.

**Comment by mturilli** [comment] 2015-03-19 15:21
Thank you. Tested and did not get any error. 

I suspect the reported errors depend on contingencies like: 
* unusual latency of the network connection, 
* Trestles responsiveness: I noticed that every so often ssh connections take a long while to get through due to filesystem lag; 
* VM congestion: concurrent use of the VM for experiments might cause ssh-based network/sockets congestion?

In case one or more of these hypothesis would be confirmed, might it be an indication that we need to think about some form of better resilience for the communication protocol between origin and target resource?

**Comment by marksantcroos** [comment] 2015-03-19 15:32
Note the ssh errors come from launching the tasks onto the nodes from the login node.
This is in principle independent of the contingencies you list. Perhaps maybe not the 2nd item, load on Trestles itself could play a role.

If you will repeatedly experience your problems with the devel branch too, I suggest we try to switch the launch method to something other than ssh. Happy to keep the ticket open for a bit.

**Comment by mturilli** [comment] 2015-03-19 15:40
Oh, I see what you mean, that explains the 10.1.255.238 and the unit ID in the errors the script outputted locally. Basically we should consider the resource unavailable when ssh connections fail between the master and compute nodes. Would this kind of high level inference in the scope of RP?

**Comment by marksantcroos** [comment] 2015-03-19 15:46
Ultimately yes I would argue. But the logic is non-trivial.

E.g. we could blacklist some nodes if they fail, but then we need some mechanism to whitelist them again, etc.

I would say that although it adds complexity, it will add to the overall user experience.

And of course all of this needs to be configurable as well, etc. :)

But once we go large scale, errors will no longer be exceptions, so we need to tackle it eventually.

**Comment by marksantcroos** [comment] 2015-04-01 20:40
Given Trestles imminent decommissioning I'll close this.

**Closed by marksantcroos** 2015-04-01 20:40 UTC
