### ISSUE TITLE
Archer-testing: radical-pilot-agent-multicore.py: error: no such option: -o

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#518] opened 2015-03-25 19:25 UTC
Terminal output: https://gist.github.com/AntonsT/08089987c8bc33da5d76
agent.out: https://gist.github.com/AntonsT/f03c6cecf283090c2eb5
agent.err: https://gist.github.com/AntonsT/b3396393fbf1fb78400a

**Comment by andre-merzky** [comment] 2015-03-27 12:57
Anons, this should be fixed now.  The problem was caused by a combination of problems, but I hope they are all addressed.  Would you please retry with a fresh VE?  Thanks!

**Closed** 2015-05-05 15:25 UTC
