### ISSUE TITLE
Executing component fails on SuperMIC

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1590] opened 2018-03-30 21:03 UTC
I am using the following stack:
```
$ radical-stack

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/vivek/Research/ves/ve-entk-perf

  radical.entk         : 0.6.1-0.6.0-29-gc2bb40b@devel
  radical.pilot        : 0.47.4
  radical.utils        : 0.47.4
  saga                 : 0.47.3
```

I am running the 00_getting_started example on SuperMIC. I get the following error in the executing component:

```
2018-03-30 15:59:11,203: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
2018-03-30 15:59:11,203: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : got unit (unit.000002)
2018-03-30 15:59:11,203: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
2018-03-30 15:59:11,204: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : Launching unit with SSH (/usr/bin/ssh -o StrictHostKeyChecking=no -o ControlMaster=auto).
2018-03-30 15:59:11,205: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : Error in spawner ('NoneType' object has no attribute 'keys')
Traceback (most recent call last):
  File "/work/vivek91/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017620.0012/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 293, in spawn
    launch_command, hop_cmd = launcher.construct_command(cu, launch_script_name)
  File "/work/vivek91/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017620.0012/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/ssh.py", line 83, in construct_command
    env_list   = self.EXPORT_ENV_VARIABLES + task_env.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
2018-03-30 15:59:11,205: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/work/vivek91/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017620.0012/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 193, in _handle_unit
    self.spawn(launcher=launcher, cu=cu)
  File "/work/vivek91/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017620.0012/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 301, in spawn
    raise RuntimeError(msg)
RuntimeError: Error in spawner ('NoneType' object has no attribute 'keys')
```

Logs attached 
[rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017620.0012.zip](https://github.com/radical-cybertools/radical.pilot/files/1864774/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017620.0012.zip)

**Comment by andre-merzky** [comment] 2018-03-30 21:07
can you please check if `fix/issue_1590` resolves this?  Thanks.

**Comment by vivek-bala** [comment] 2018-03-30 21:08
Woaah.. that was quick! Let me try :)

**Comment by vivek-bala** [comment] 2018-03-30 21:18
Tried it. The prev error is doesn't pop up. But the tasks fail with ```bash: =$: command not found``` in STDERR. The executable in a ```/bin/date``` though.

**Comment by vivek-bala** [comment] 2018-03-30 21:19
I think its coming from the executor again.

```
2018-03-30 16:12:23,372: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : INFO    : Launching unit unit.000179 via /usr/bin/ssh -o StrictHostKeyChecking=no -o ControlMaster=auto smic328   ="$ "  /worka/work/vivek91/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017620.0015/pilot.0000/unit.000179/unit.000179.sh in /worka/work/vivek91/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017620.0015/pilot.0000/unit.000179

```

**Comment by andre-merzky** [comment] 2018-03-31 08:45
Oh...  Can you please send the agent logfiles, and include one of the units sandboxes (which contains the unit shell script)?  Thanks!

**Comment by andre-merzky** [comment] 2018-05-02 11:27
@vivek-bala : ping

**Comment by vivek-bala** [comment] 2018-05-03 19:09
Bootstrap fails with the following:
```
 -------------------------------------------------------------------
# Touching output tarballs
# -------------------------------------------------------------------
VIRTENV : /work/vivek91/radical.pilot.sandbox/ve.xsede.supermic.0.47.4
VIRTENV : /worka/work/vivek91/radical.pilot.sandbox/ve.xsede.supermic.0.47.4 (normalized)
PYTHON: /usr/local/packages/python/2.7.7-anaconda/bin/python
PIP   : /usr/local/packages/python/2.7.7-anaconda/bin/pip
virtenv_create   : TRUE
virtenv_update   : FALSE
rp install sources:  radical.utils-0.47.4/ saga-python-0.47.3/ radical.pilot-0.47.4-v0.47.4-1-ga0e949e-fix-issue-1591/
rp install target : SANDBOX
rp install lock   : FALSE
rp lock for ve create
obtained lock /worka/work/vivek91/radical.pilot.sandbox/ve.xsede.supermic.0.47.4.lock

# -------------------------------------------------------------------
#
# Download virtualenv tgz
# cmd: curl -k -O 'https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.tar.gz'
#
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100   122  100   122    0     0   1104      0 --:--:-- --:--:-- --:--:--  1326
#
# SUCCESS
#
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# unpacking virtualenv tgz
# cmd: tar zxmf 'virtualenv-1.9.tar.gz'
#

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't unpack virtualenv! Using systemv version
ERROR: invalid or unusable virtenv_dist option
Error on virtenv creation -- abort
removed `/worka/work/vivek91/radical.pilot.sandbox/ve.xsede.supermic.0.47.4.lock'
```

Same error as on BW.

**Comment by andre-merzky** [comment] 2018-05-07 19:27
The last error is a duplicate of #1600, which is fixed by now.  Does the original error still occur?

**Comment by vivek-bala** [comment] 2018-05-07 22:40
I think I used the released version of RP. Might not have recreated the VE on SuperMIC and BW. Will test again.

**Comment by vivek-bala** [comment] 2018-05-07 22:42
Scratch that. I seem to have used devel, but your email about the merge probably resolves this. Will test and report back.

**Comment by iparask** [comment] 2019-04-01 15:10
This seems to have been resolved. I'm closing as such

**Closed by iparask** 2019-04-01 15:10 UTC
Labels: comp:agent:executor, priority:high, topic:execution, type:bug
