### ISSUE TITLE
RP (tag TITAN) fails constantly on TITAN

### ISSUE THREAD

**Issue by AA919** [radical-cybertools/radical.pilot#1332] opened 2017-05-01 02:04 UTC
Hi,
I was not able to run a single experiment today on TITAN. All the pilots failed during the bootstrapping almost immediately.

```
It seems ORTE related. I found this in the log files:
Traceback (most recent call last):
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 147, in __init__
    rp.agent.LM.lrms_config_hook(lm, self._cfg, self, self._log))
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 161, in lrms_config_hook
    return impl.lrms_config_hook(name, cfg, lrms, logger)
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 50, in lrms_config_hook
    oi_output = subprocess.check_output(['orte-info|grep "Open RTE"'], shell=True)
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['orte-info|grep "Open RTE"']' returned non-zero exit status 1
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 720, in start
    self._initialize_parent()
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 419, in _initialize_parent
    self.initialize_parent()
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_0.py", line 114, in initialize_parent
    session=self._session)
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 217, in create
    return impl(cfg, session)
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/torque.py", line 19, in __init__
    LRMS.__init__(self, cfg, session)
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 147, in __init__
    rp.agent.LM.lrms_config_hook(lm, self._cfg, self, self._log))
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 161, in lrms_config_hook
    return impl.lrms_config_hook(name, cfg, lrms, logger)
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 50, in lrms_config_hook
    oi_output = subprocess.check_output(['orte-info|grep "Open RTE"'], shell=True)
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['orte-info|grep "Open RTE"']' returned non-zero exit status 1
```

I think that we have this problem since 11 days ago because while I was harvesting data from olrd experiments I noticed that all of them failed.

Alessio

**Comment by andre-merzky** [comment] 2017-05-01 06:37
Can you please give the devel versions (RU, RS, RP) a try?  Thanks!

**Comment by AA919** [comment] 2017-05-02 03:50
I tried, it suffer of the same problem described in #1323. I did experiments  with Gromacs as weel.  We are able to run 1024 single thread simulations on 64 nodes but we hit the walltime at 2048 with 128 nodes. Summarizing, with this last version of ORTE, we doubled the number of nodes on which Gromacs works but we cut off ATLAS workload.

**Comment by andre-merzky** [comment] 2017-05-04 07:37
Sorry, I have no good idea right now, will try to reproduce and pull @marksantcroos

**Comment by andre-merzky** [comment] 2017-05-05 01:23
Alessio, can you please try the RP branch `test/ompi_titan`?  

Also, if you don't mind, please add two examples to the `tests/` in that branch: `issue_1332_pinning.py` to check for the core pinning problem with AthenaMP,  `issue_1332_scaling.py` to check for the scaling limits with gromacs, both with documented expected behavior.  We'll run those on each new deployment of ORTE then.

**Comment by AA919** [comment] 2017-05-05 17:12
Hi,

I tried Atlas workload and it has the same problem. I am trying Gromacs 
right now, as soon as Titan gives me the nodes I will report the result.

Yes, I can add the examples but both of them rely on files that cannot 
be put in Github (Atlas use case needs a file that is more than 100Mb 
and Gromacs must be compiled against the current openMPI). There is a 
place on Lustre where I can put these files in such a way that they are 
accessible by everybody?

Cheers.

Alessio

**Comment by andre-merzky** [comment] 2017-05-05 17:30
re tests: thanks, that would be good.

**Comment by AA919** [comment] 2017-05-06 03:28
Commit done. I had to put the files in the same folder of OpenMPI. 
BTW, I did a bunch of tests with Gromacs, I was not able to complete 2048 single threaded CUs by using 128 nodes.

**Comment by andre-merzky** [comment] 2017-05-08 07:37
Hi Ale - I seem to miss where that commit went to - can you give me a pointer, please?  Thanks!

**Comment by AA919** [comment] 2017-05-08 12:19
Hi man,
Here it is c353a660f01e4e6900de57f23734aa3cf32fd239

**Comment by andre-merzky** [comment] 2017-05-12 08:56
Ale, can you give AthenaMP another try with devel, please? Only RP needs updating.
No news on Gromacs, yet.

**Comment by AA919** [comment] 2017-05-12 16:23
Hi Andre,

I did the pull and I used the stack below but the problem remains. The 
pilot crashes immediately after it starts running. No logs are copied in 
the sandbox.

  python               : 2.7.9
   pythonpath           : 
/sw/xk6/python_pip/8.1.2/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
   virtualenv           : /ccs/home/aleang9/ve_devel

   radical.pilot        : split-69-gc96442b@devel
   radical.utils        : v0.45-44-gd437bb4@devel
   saga                 : split-17-gefa3fcb@devel

**Comment by andre-merzky** [comment] 2017-05-13 22:02
I opened up my installation at `/ccs/home/merzky1/ve_orte_test` - can you please try to use that one?  Also, can you please make a tarball for the sandbox from the failing run above available?  Thanks!

**Comment by AA919** [comment] 2017-05-15 01:24
Hi,

I did a pull from github and I noticed that it was not updating 
ve_titan. So I deleted it manually and let RP rebuild it from scratch.

Anyway.....welcome back ATLAS workload.

Thanks!

Alessio

p.s. I will test gromacs as soon as I compile it against the new open MPI.

**Comment by andre-merzky** [comment] 2017-05-15 15:00
Wohoo!

This is the last (major) ticket holding up release testing.  Sorry for the time it took on my end - it turned out to be several issues colliding (one of them being my stupidity, as usual).  Either way, if you would have some prelim info about gromacs before tomorrows call, that would be excellent.... :)

Thanks, Andre.

**Comment by AA919** [comment] 2017-05-15 15:22
On 15/05/2017 11:00, Andre Merzky wrote:
>
> Wohoo!
>
> This is the last (major) ticket holding up release testing. Sorry for 
> the time it took on my end - it turned out to be several issues 
> colliding (one of them being my stupidity, as usual).
>
There is no need to say sorry. Actually, I should apologize for not 
helping you.

> Either way, if you would have some prelim info about gromacs before 
> tomorrows call, that would be excellent.... :)
>
Doing it right now.
Alessio

**Comment by AA919** [comment] 2017-05-16 01:15
The behavior with gromacs did not change. At the moment we are not able to run 2048 single core CUs on 128 nodes. Everything was fine with 1024 CUs on 64 nodes so I believe that the maximum is somewhere in the middle.
Now, the ATLAS workload is available again, I do not mind to much about the limit on Gromacs. In the end we are doing better than a month ago.

**Comment by ibethune** [comment] 2017-05-16 08:21
OK, so the 'blocking ATLAS workload' part of the issue is fixed.  Is the remaining issue re: many concurrent gromacs CUs covered by #1165 or is that a separate problem?

Since @AA919 seems happy with the current status, I think this ticket can either be closed (or if it is the only place the gromacs scaling limit is covered, deferred to a future release).

**Comment by andre-merzky** [comment] 2017-05-16 12:58
Ack on defer for the gromacs scaling.  Maybe we should open a new ticket for that?

**Comment by ibethune** [comment] 2017-05-16 13:03
Agreed, #1347 is open to track the scaling issue.  Closing this one.

**Closed by ibethune** 2017-05-16 13:03 UTC
