### ISSUE TITLE
app kernel migration

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#498] opened 2015-03-12 14:05 UTC
- Kernel config interpretation should probably be part of RP, or at least not part of "md"kernel.
- Should also use the resource labels.
- Could benefit from a more flexible kernel repo, e.g. pass a url, local files, etc.

**Comment by andre-merzky** [comment] 2015-09-15 08:58
duplicate of #543

**Closed by andre-merzky** 2015-09-15 08:58 UTC
