### ISSUE TITLE
Clarify failure mode for raptor Worker

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2643] opened 2022-07-07 19:38 UTC
# Requesting clarification on raptor Worker failure modes

## Misbehaving tasks may kill the Worker

It is very likely that some Python tasks will include calls to `sys.exit` or other bad behavior, but I do not see how to mitigate in the current code. Moreover, the exit code, stderr, and stdout of the Worker process will be important to retain for the client, in such cases, as proximal task results.

1. Previously, I believe, Worker tasks ran in interpreters forked from the Worker process. I cannot find the code for this now. Does the interpreter process supporting the task for a submitted Worker handle `_dispatch` calls without forking (unless coded to, in the implementing call mode)?

- <s>Confirm: _in general_ tasks being dispatched by Workers run in the Worker's interpreter process.</s> *see below*

2. If the Python interpreter exits while a Worker is handling a `_dispatch()`, what happens?
* Does the framework trigger any of the Master callbacks for the Task?
* Are there any callbacks for the Worker failure?
* How can the Master discover the Worker failure and access the stdout/stderr or output files for the Task produced by `submit_workers`?
* Does the scheduling system avoid sending new requests to a Worker if it does not cleanly disconnect from the zmq queue?

## Unusable or inaccessible Worker can cause hang

If there are _no_ running Worker processes, how do we prevent the Master from blindly submitting more tasks that will never complete?

## Broken configuration can cause hang

If the Worker or environment are misconfigured, the Worker may exit prematurely. No error propagates to the Master or to the user. Pending or subsequently submitted tasks will never finish, so the job will hang.

For example, the MPIWorker has an undocumented dependence on `mpi4py`. If `mpi4py` is missing from the target environment or from a `prepare_env()` call that the raptor tasks will use, the worker will silently fail and the job will hang.

**Comment by andre-merzky** [comment] 2022-07-25 11:39
There is a difference between the two worker implementations in Raptor: the non-MPI worker will run tasks in a forked process, and `sys.exit` and all other exit modes of the task will be handled gracefully.  For the MPI worker we can't do that as a fork would not inherit the MPI communicators, so we have to run in the Python interpreter of the respective MPI ranks.  An `sys.exit` will result in the worker to die.  Note that this may affect other tasks which run in other sub-communicators of the same MPI worker instance.

We at the moment don't handle failing workers.  I take this as a feature request though: we can implement a callback on the master which triggers on failing workers and allows the master to restart them.  The tasks however will be lost and we would not consider them restartable - it would be up to the application to resubmit them if needed.

`sys.exit` though could be caught, we can add that capability - but it will obviously not shield against all forms of termination...

**Comment by eirrgang** [comment] 2022-07-25 12:13
> There is a difference between the two worker implementations in Raptor: the non-MPI worker will run tasks in a forked process, and `sys.exit` and all other exit modes of the task will be handled gracefully. For the MPI worker we can't do that as a fork would not inherit the MPI communicators, so we have to run in the Python interpreter of the respective MPI ranks. An `sys.exit` will result in the worker to die. Note that this may affect other tasks which run in other sub-communicators of the same MPI worker instance.

Yes. That's one of my concerns.

> We at the moment don't handle failing workers. I take this as a feature request though: we can implement a callback on the master which triggers on failing workers and allows the master to restart them. The tasks however will be lost and we would not consider them restartable - it would be up to the application to resubmit them if needed.

Yes, please. At the very least, we need a stable workaround or a way to detect the issue. Is there anything we can do in RP 1.15.1 to poll the Worker? If there is nothing that can be done before RP 1.16 or 1.17, can you advise on the best way for a developer or tester to look for dead Workers when a workflow may have hung?

> `sys.exit` though could be caught, we can add that capability - but it will obviously not shield against all forms of termination...

Yes, that will not be rigorous enough to be worthwhile, I don't think. Some libraries (like libgromacs) have a nasty habit of calling MPI_ABORT and otherwise doing everything they possibly can to destroy their environment. We need to address Worker failures, generally.

> > If there are no running Worker processes, how do we prevent the Master from blindly submitting more tasks that will never complete?
> 
> We don't. 'submitting tasks' from the master perspective means to put tasks in a queue. A master though can always start new workers which then pull tasks from that queue - we cannot know if the master will or will not start new workers eventually.

I think you are saying "no", but is there any way for the Master to check the status of the Workers it has submitted? It seems like the master retains a list of uids of submitted workers. Do these tasks behave like normal Tasks, in that a Master subclass could implement a non-blocking `wait()` or check whether they are FINAL at various times?

In the example at https://github.com/radical-cybertools/radical.pilot/blob/devel/examples/misc/raptor_master.py there is a commented out "wait". Could something like that be used?

Note: this is probably also related to any design and development in support of https://github.com/SCALE-MS/scale-ms/issues/105#issuecomment-822361012

**Comment by andre-merzky** [comment] 2022-09-28 09:59
I would like to delay this a bit until the current work on the raptor examples is merged (#2701) to avoid conflicts.  But the bottom line is from my perspective that the master (which is under application control) is responsible for watching worker health.  The example will be updated to reflect that.

**Comment by andre-merzky** [comment] 2023-01-06 12:09
I have bad news on this item I'm afraid: mpi4py does not cleanly terminate MPI applications on rank failures.  This seems to be a somewhat old problem (see [here](https://github.com/chainer/chainermn/issues/236 for example a discussion from 2018).  Alas, the various workarounds which circulate the interwebs seem not to resolve the issue in our specific case.  I created a minimal reproducer and opened an [mpi4py issue](https://github.com/mpi4py/mpi4py/issues/290).  We will not be able to cleanly handle fatal task errors until that is resolved - it's not possible to remove the process indirection in our popen executor.

ping @mturilli for awareness.

**Comment by eirrgang** [comment] 2023-01-06 12:43
I was just thinking a couple of days ago that I didn't recall seeing the `-m mpi4py` argument to the Python interpreter when launching any of the mpi4py enabled processes. Instead of `sh -c script.py`, can we not launch masters and workers with `$PYTHON -m mpi4py script.py`?

As reported, this sounds like problems I was seeing recently on `anvil`, which seemed to be related to (certain versions of) `libfabric` interacting badly with combinations of `fork` and MPI_Init / MPI_finalize getting called in different parts of a process hierarchy.

It also sounds like problems I've seen where subprocesses see the environment variables injected by `mpiexec` and have broken notions of whether/which MPI_COMM_WORLD they are using / supposed to use. That doesn't seem to be the case because your test shows that the processes each get a unique rank. Still... it might be good to confirm that the MPI context is working before the abort with a collective call like a barrier.

Have you tried a C program instead of the Python test case to confirm that the problem is not a general problem with calling MPI_Init from a subprocess?

**Comment by eirrgang** [comment] 2023-01-06 12:53
Does RCT rely on custom `sys.excepthook` normally?

**Comment by eirrgang** [comment] 2023-01-06 12:57
If I remove the custom exception handler from your reproducer, then the script hangs every time, for me, whether in an extra subprocess layer or not. When I _either_ enable the custom exception handler *or* use the `mpi4py.run` (via `python -m mpi4py`) I don't see the hang, with or without the extra subprocess layer.

**Comment by andre-merzky** [comment] 2023-01-06 14:07
> Instead of `sh -c script.py`, can we not launch masters and workers with `$PYTHON -m mpi4py script.py`?

No, we need to rely on the shell layer for task environment setup, profiling, pre-exec etc, so we cannot remove the shell layer.

> Does RCT rely on custom sys.excepthook normally?

no.  Python exception handling is a mess as it is, the excepthook does not make it simpler.

**Closed** 2023-04-13 13:58 UTC
Labels: type:feature, type:question, topic:execution, layer:rp, priority:high, comp:raptor
