### ISSUE TITLE
bootstrapping fails on blacklight

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#509] opened 2015-03-19 09:42 UTC
```
# cmd: pip --cert cacert.pem install pymongo apache-libcloud colorama python-hostlist
#
Collecting pymongo
  Downloading pymongo-2.8.tar.gz (394kB)
  Exception:
  Traceback (most recent call last):
    File "/usr/uo/5/santcroo/radical.pilot.sandbox/ve_blacklight/lib/python2.7/s
ite-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/usr/uo/5/santcroo/radical.pilot.sandbox/ve_blacklight/lib/python2.7/s
ite-packages/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "/usr/uo/5/santcroo/radical.pilot.sandbox/ve_blacklight/lib/python2.7/s
ite-packages/pip/req/req_set.py", line 385, in prepare_files
      req_to_install.run_egg_info()
    File "/usr/uo/5/santcroo/radical.pilot.sandbox/ve_blacklight/lib/python2.7/s
ite-packages/pip/req/req_install.py", line 310, in run_egg_info
      self.setup_py, self.name,
    File "/usr/uo/5/santcroo/radical.pilot.sandbox/ve_blacklight/lib/python2.7/s
ite-packages/pip/req/req_install.py", line 281, in setup_py
      import setuptools  # noqa
    File "/usr/uo/5/santcroo/radical.pilot.sandbox/ve_blacklight/lib/python2.7/s
ite-packages/setuptools/__init__.py", line 11, in <module>
      from setuptools.extension import Extension
    File "/usr/uo/5/santcroo/radical.pilot.sandbox/ve_blacklight/lib/python2.7/s
ite-packages/setuptools/extension.py", line 8, in <module>
      from .dist import _get_unpatched
    File "/usr/uo/5/santcroo/radical.pilot.sandbox/ve_blacklight/lib/python2.7/s
ite-packages/setuptools/dist.py", line 21, in <module>
      packaging = pkg_resources.packaging
  AttributeError: 'module' object has no attribute 'packaging'
```

**Comment by andre-merzky** [comment] 2015-03-19 12:01
This was caused by a `PYTHONPATH` env which comes from the `module load python` -- should be fixed now.

**Closed by andre-merzky** 2015-03-19 12:01 UTC

**Comment by marksantcroos** [comment] 2015-03-19 12:47
Thanks
