### ISSUE TITLE
RP0.46 unable to get jobs onto the queue on Stampede. 

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1432] opened 2017-09-02 22:49 UTC
...but RP0.46RC2 works fine.

While running some tests this past week I found that while using RP0.46 with the following stack:

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/ubuntu/VirtualEnvironments/RP_46/ve.RP0.46

  radical.analytics    : v0.45.2-2-g476254a@devel
  radical.pilot        : 0.46.1
  radical.utils        : 0.46.2
  saga                 : 0.46.1

the data staging to the Stampede filesystem happens correctly, but upon logging into Stampede separately and doing an showq -u reveals that the submitted job never actually manages to get on the queue. No error files or log files are generated, and the only files in the RP sandbox are the AMBER input files that were staged. 

If more info is needed from me to investigate this, please let me know.

Client side log files:

[rp.session.ubuntu.ubuntu.017411.0013.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1272581/rp.session.ubuntu.ubuntu.017411.0013.tar.gz)

**Comment by andre-merzky** [comment] 2017-09-02 22:50
Can you please send the client side log files?  Thanks!

**Comment by SrinivasMushnoori** [comment] 2017-09-02 22:51
Was just about to do that, compressing them now :)

**Comment by SrinivasMushnoori** [comment] 2017-09-02 22:52
Uploaded to the first post.

**Comment by andre-merzky** [comment] 2017-09-02 22:56
This is a duplicate of #1426 I think - can you please retry with a fresh install?  I literally pushed the hotfix to pypi a couple of minutes ago... :)

**Comment by SrinivasMushnoori** [comment] 2017-09-02 23:04
I see. Attempted with RP0.46.2 and this does indeed solve the issue.
Thanks Andre!

**Closed** 2017-09-03 17:15 UTC
Labels: bug
