### ISSUE TITLE
Malformed CU in session

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1349] opened 2017-05-19 00:47 UTC
Running analytics on a session `rp.session.titan-ext6.aleang9.017304.0004`, I noticed the following:
```
unit.000297:
 U_UMGR_BINDING U_AGENT_QUEUING U_AGENT_QUEUING_EXEC U_AGENT_EXECUTING U_AGENT_SCHEDULING U_UMGR_SCHEDULING
unit.000298:
 U_UMGR_BINDING U_AGENT_QUEUING U_AGENT_QUEUING_EXEC U_AGENT_EXECUTING U_AGENT_SCHEDULING U_UMGR_SCHEDULING
unit.000299:
 U_UMGR_BINDING U_AGENT_QUEUING U_AGENT_QUEUING_EXEC U_AGENT_EXECUTING U_AGENT_SCHEDULING U_UMGR_SCHEDULING
unit.0003:
WARNING: Failed to get timestampe for state UMGR_STAGING_INPUT
WARNING: Failed to get timestampe for state AGENT_STAGING_OUTPUT_PENDING
WARNING: Failed to get timestampe for state AGENT_EXECUTING
WARNING: Failed to get timestampe for state AGENT_SCHEDULING
WARNING: Failed to get timestampe for state AGENT_SCHEDULING_PENDING
WARNING: Failed to get timestampe for state UMGR_STAGING_OUTPUT
WARNING: Failed to get timestampe for state AGENT_EXECUTING_PENDING
WARNING: Failed to get timestampe for state UMGR_SCHEDULING
WARNING: Failed to get timestampe for state AGENT_STAGING_OUTPUT
WARNING: Failed to get timestampe for state DONE
WARNING: Failed to get timestampe for state AGENT_STAGING_INPUT
WARNING: Failed to get timestampe for state UMGR_STAGING_INPUT_PENDING
WARNING: Failed to get timestampe for state NEW
WARNING: Failed to get timestampe for state UMGR_STAGING_OUTPUT_PENDING
WARNING: Failed to get timestampe for state AGENT_STAGING_INPUT_PENDING
WARNING: Failed to get timestampe for state UMGR_SCHEDULING_PENDING
WARNING: Failed to calculate duration U_UMGR_BINDING
WARNING: Failed to calculate duration U_AGENT_QUEUING
WARNING: Failed to calculate duration U_AGENT_QUEUING_EXEC
WARNING: Failed to calculate duration U_AGENT_EXECUTING
WARNING: Failed to calculate duration U_AGENT_SCHEDULING
WARNING: Failed to calculate duration U_UMGR_SCHEDULING
```

Note: 
* the unit name is malformed (I checked and `unit.000003` exists and is normally parsed). The list of units are obtained via `sra_session.filter(etype='unit', inplace=False)` where `sra_session` is `sra_session = ra.Session(sid, 'radical.pilot', src=sdir)`.
* the unit state is empty as in no data and now data structure. 

I am not sure whether this is an issue with RP or RA. Also, I am not aware of what stack was used to run the session. @AA919 might probably provide this information.

The session can be found at:

https://github.com/radical-experiments/rp-paper/blob/master/analysis/data/use_case_id_5_gromacs/exp1.tar.bz2

**Comment by AA919** [comment] 2017-05-19 13:12
The stack is this one:
  python               : 2.7.6
  pythonpath           : 
  virtualenv           : /home/aangius/src-devel/ve_devel

  radical.pilot        : split-71-gfdd36239@devel
  radical.utils        : v0.45-46-g591b33d@devel
  saga                 : split-18-gc074c761@devel

**Comment by ibethune** [comment] 2017-05-22 08:57
Also to look at after RP release.

**Comment by ibethune** [comment] 2017-05-22 09:00
A quick triage to understand if this is indeed an RP issue (in which case if it should be fixed before release), or if the root cause is in RA (which we know is broken and has a set of tickets to look at immediately after the RP release).

**Comment by andre-merzky** [comment] 2017-05-22 11:01
I did not yet look into this one.  Unit uid being maleformed can come from either RP or RA - I have no intuition which one is more likely at fault (I am inclined to say this is impossible, but clearly... :-P )

**Comment by andre-merzky** [comment] 2017-05-25 23:18
Can you please try the following:

* install the RP stack as (which is basically RU, RP, RA: devel, RS: release)
```
  radical.analytics    : v0.45.2@devel
  radical.pilot        : split-73-ge5d68d1@devel
  radical.utils        : v0.45-46-g591b33d@devel
  saga                 : 0.45.1
```
* download your tarball above, extract
* run this script:
```
#!/usr/bin/env python

import os, sys, glob
import radical.utils     as ru
import radical.pilot     as rp
import radical.analytics as ra

sessions = glob.glob('exp1/rp.*')
for src in sessions:
    print src
    json_files = glob.glob('%s/*.json' % src)
    json_file  = json_files[0]
    json       = ru.read_json(json_file)
    sid        = os.path.basename(json_file)[:-5]
    session    = ra.Session(sid, 'radical.pilot', src=src)
    print 'sid: %s ok' % sid
```

I only see one session failing in this setup, and that is due to a missing json file (`exp1/rp.session.titan-ext2.aleang9.017269.0009`).  So I hope that your problem is solved with a stack update... - lets see... :)

**Comment by mturilli** [comment] 2017-06-01 18:24
```
$ radical-stack 

  python               : 2.7.10
  pythonpath           : 
  virtualenv           : /Users/mturilli/Virtualenvs/RADICAL-ANALYTICS

  radical.analytics    : v0.45.2@devel
  radical.pilot        : split-74-g10acb0d3@devel
  radical.utils        : v0.45-46-g591b33d@devel
  saga                 : v0.45.1@master
```

Same error:
```
unit.0003:
WARNING: Failed to get timestampe for state UMGR_STAGING_INPUT
WARNING: Failed to get timestampe for state AGENT_STAGING_OUTPUT_PENDING
WARNING: Failed to get timestampe for state AGENT_EXECUTING
WARNING: Failed to get timestampe for state AGENT_SCHEDULING
WARNING: Failed to get timestampe for state AGENT_SCHEDULING_PENDING
WARNING: Failed to get timestampe for state UMGR_STAGING_OUTPUT
WARNING: Failed to get timestampe for state AGENT_EXECUTING_PENDING
WARNING: Failed to get timestampe for state UMGR_SCHEDULING
WARNING: Failed to get timestampe for state AGENT_STAGING_OUTPUT
WARNING: Failed to get timestampe for state DONE
WARNING: Failed to get timestampe for state AGENT_STAGING_INPUT
WARNING: Failed to get timestampe for state UMGR_STAGING_INPUT_PENDING
WARNING: Failed to get timestampe for state NEW
WARNING: Failed to get timestampe for state UMGR_STAGING_OUTPUT_PENDING
WARNING: Failed to get timestampe for state AGENT_STAGING_INPUT_PENDING
WARNING: Failed to get timestampe for state UMGR_SCHEDULING_PENDING

WARNING: Failed to calculate duration U_UMGR_BINDING

WARNING: Failed to calculate duration U_AGENT_QUEUING

WARNING: Failed to calculate duration U_AGENT_QUEUING_EXEC

WARNING: Failed to calculate duration U_AGENT_EXECUTING

WARNING: Failed to calculate duration U_AGENT_SCHEDULING

WARNING: Failed to calculate duration U_UMGR_SCHEDULING
DEBUG: pu_rels.items():

WARNING: empty pilot name for unit unit.0003
Traceback (most recent call last):
  File "wranglermp.py", line 770, in <module>
    wrangle_session(sdir, sid)
  File "wranglermp.py", line 650, in wrangle_session
    sra_session, pu_rels, uts)
  File "wranglermp.py", line 452, in load_units
    (pilots['pid'] == punit)]['hid'].tolist()[0]
IndexError: list index out of range
```

**Comment by AA919** [comment] 2017-06-01 19:34
This problem is RP side or Alessio's side?

**Comment by andre-merzky** [comment] 2017-06-02 06:53
Alas, I don't find session `rp.session.titan-ext6.aleang9.017304.0004` in that tarball, nor in the experiment repo.  The wrangler seems to churn nicely through the sessions in the tarball (still running though).  Can you check again please with session is affected?

In the script, I am not exactly sure what the affected line is supposed to do - can you elaborate, please:

```
hid = pilots[(pilots['sid'] == sid) &
                     (pilots['pid'] == punit)]['hid'].tolist()[0]
```

I assume that the first part is a filter on pandas or numpy level, and you expect to get some time series or whatever from the result?   I would think that the error indicates that either `hid` is not defined, or that there are no matching pilots in that session?

**Comment by mturilli** [comment] 2017-06-03 09:27
Please find the quoted session at:
```
https://github.com/radical-experiments/rp-paper/tree/master/rawdata/exp1/gromacsweak-titan/rp.session.titan-ext6.aleang9.017304.0004
```

Meaning of 
```
hid = pilots[(pilots['sid'] == sid) &
             (pilots['pid'] == punit)]['hid'].tolist()[0]
```

From the pandas DataFrame `pilots`, assign the first element of the list of host IDs to `hid` for all the pilots with session ID equal to `sid` and pilot ID equal to `punit`; where `sid` is defined via `get_raw_sessions()` and `get_new_sessions()`, and `punit` is the pilot entity on which the unit has been running as found in `pu_rels.items()`.

Assuming that the lists of host IDs and `[key[0] for key in pu_rels.items() if uid in key[1]]` have always one and only one element should be sound:
- Every unit (identified by `uid`) is successfully executed on one and only one pilot;
- pilots are executed on only and only one host;
- Pilots ID is guaranteed to be unique.

To be revised depending on how unit rescheduling is rendered in `ra.session.describe('relations', ['pilot', 'unit'])`.

**Comment by andre-merzky** [comment] 2017-06-05 13:34
Quick note that this issue should not hold up the release, IMHO.

**Comment by mturilli** [comment] 2017-06-08 14:41
Possibly related: session: `rp.session.titan-ext6.aleang9.017303.0016` at https://github.com/radical-experiments/rp-paper/blob/master/analysis/data/use_case_id_5_gromacs/exp1.tar.bz2

When wrangling with `wranglermp.py -d ../data/use_case_id_5_gromacs/ -t exp -s rp.session.titan-ext6.aleang9.017303.0016` (code at: https://github.com/radical-experiments/rp-paper/blob/master/analysis/bin/wranglermp.py):
```
exp1 -- rp.session.titan-ext6.aleang9.017303.0016 -- Loading units:

exp1 --- rp.session.titan-ext6.aleang9.017303.0016
unit.:

WARNING: Failed to get timestampe for state UMGR_STAGING_INPUT
WARNING: Failed to get timestampe for state AGENT_STAGING_OUTPUT_PENDING
WARNING: Failed to get timestampe for state AGENT_EXECUTING
WARNING: Failed to get timestampe for state AGENT_SCHEDULING
WARNING: Failed to get timestampe for state AGENT_SCHEDULING_PENDING
WARNING: Failed to get timestampe for state UMGR_STAGING_OUTPUT
WARNING: Failed to get timestampe for state AGENT_EXECUTING_PENDING
WARNING: Failed to get timestampe for state UMGR_SCHEDULING
WARNING: Failed to get timestampe for state AGENT_STAGING_OUTPUT
WARNING: Failed to get timestampe for state DONE
WARNING: Failed to get timestampe for state AGENT_STAGING_INPUT
WARNING: Failed to get timestampe for state UMGR_STAGING_INPUT_PENDING
WARNING: Failed to get timestampe for state NEW
WARNING: Failed to get timestampe for state UMGR_STAGING_OUTPUT_PENDING
WARNING: Failed to get timestampe for state AGENT_STAGING_INPUT_PENDING
WARNING: Failed to get timestampe for state UMGR_SCHEDULING_PENDING
WARNING: Failed to calculate duration U_UMGR_BINDING
WARNING: Failed to calculate duration U_AGENT_QUEUING
WARNING: Failed to calculate duration U_AGENT_QUEUING_EXEC
WARNING: Failed to calculate duration U_AGENT_EXECUTING
WARNING: Failed to calculate duration U_AGENT_SCHEDULING
WARNING: Failed to calculate duration U_UMGR_SCHEDULING
DEBUG: pu_rels.items():

WARNING: empty pilot name for unit unit.
Traceback (most recent call last):
  File "wranglermp.py", line 770, in <module>
    wrangle_session(sdir, sid)
  File "wranglermp.py", line 650, in wrangle_session
    sra_session, pu_rels, uts)
  File "wranglermp.py", line 452, in load_units
    (pilots['pid'] == punit)]['hid'].tolist()[0]
IndexError: list index out of range
```
Note:
* Name of unit is malformed `unit.`
* `pu_rels.items()` is empty, i.e., `sra_session.describe('relations', ['pilot', 'unit'])` is empty
* therefore does not find the name of the pilot where the unit run

The same happens to sessions: `rp.session.titan-ext6.aleang9.017304.0004`, `rp.session.titan-ext6.aleang9.017304.0001`

Stack:
```
$ radical-stack 

  python               : 2.7.10
  pythonpath           : 
  virtualenv           : /Users/mturilli/Virtualenvs/RADICAL-ANALYTICS

  radical.analytics    : v0.45.2@devel
  radical.pilot        : split-74-g10acb0d3@devel
  radical.utils        : v0.45-46-g591b33d@devel
  saga                 : v0.45.1@master
```

**Comment by andre-merzky** [comment] 2017-06-10 21:40
Matteo, I think I see what's up with the original problem: the session download seems incomplete, and the last lines in update.0.child.prof are:
```
update.0.child.prof:1495084348.7614,update.0.child:update.0.child.subscriber._state_cb,unit.000368,,bulk,bulked (AGENT_EXECUTING)
update.0.child.prof:1495084348.7616,update.0.child:update.0.child.subscriber._state_cb,unit.000369,,get,update unit state to AGENT_EXECUTING
update.0.child.prof:1495084348.7617,update.0.child:update.0.child.subscriber._state_cb,unit.000369,,bulk,bulked (AGENT_EXECUTING)
1495084348.7619,update.0.child:update.0.child.subscriber._state_cb,unit.0003
```

Bingo.  I guess we can shield from errors like this by disallowing imcomplete CSV lines.  FWIW, the pilot profile tarball in that dir is also empty.

As for the second case (rp.session.titan-ext6.aleang9.017303.0016), I can't see it in the tarball you referenced - any idea?

**Comment by andre-merzky** [comment] 2017-06-10 21:49
Nevermind, found that session - I had a tarball with the same name lying around :P

**Comment by andre-merzky** [comment] 2017-06-10 22:05
And same here, this time in the pilot sandbox:

```
$ tail -n 2 update.0.child.prof
1495064385.2767,update.0.child:update.0.child.idler._idle_cb,unit.000065,,update,unit update pushed (DONE)
1495064385.2767,update.0.child:update.0.child.idler._idle_cb,unit.
```

unfortunately, there is not much we can do to cleanly solve this problem.  The CSV reader silently ignores this, and cannot be convinced to complain.  So we could roll our own reader, urgh.  Or we do some manual sanity check afterwards, like looking if the UIDs look like we expect them.  But we will not be able to catch missing entries this way, or incomplete entries which do not break the uid, but rather the entry type or message.

We do have end-of-profile markers actually, which get written when we terminate and flush the profiles, so we can complain when those are missing - but then we are not sure if we tripped over a termination issue, or if the profiles are indeed broken / incomplete.

Any suggestion how you would like to see this handled?

**Comment by mturilli** [comment] 2017-06-12 17:11
Mmm, tricky one. Do we understand why this happened? Maybe something wrong with how we close/flush/synch the file handle of the profile file at termination time?

**Comment by andre-merzky** [comment] 2017-06-12 21:48
Yes, definitely caused by not being able to flush on termination.  But I do not know if that is caused by a bug on our end, or because the system does not allow up to do so during termination - for that I would need to know how the pilot died.  For example, if the pilot times out (exceeds queue time), then the batch system might send a SIG-15 to  signal termination, and a second later a SIG-9 to hard-terminate.  If we don't manage to write all data in that one second, then profiles are cut short.  If the pilot does not time out, but terminates due to user request (`pilot.cancel()`), I would suspect a problem in our code.

**Comment by andre-merzky** [comment] 2017-07-24 08:27
The recent merges to devel are supposed to fix this issue also, by relying less on garbage collection to ensure profile flushing.  Lets see if this pops up again during testing.

**Comment by andre-merzky** [comment] 2017-08-05 22:47
Matteo, is this still a problem?  Otherwise, please do close, if you don't mind.  Thanks!

**Closed** 2017-08-09 11:04 UTC
