### ISSUE TITLE
RP fails on Bluewaters

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1591] opened 2018-03-31 01:05 UTC
Using the following stack on BW:
```
 radical-stack

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/vivek/Research/ves/ve-entk-perf

  radical.entk         : 0.6.1-0.6.0-29-gc2bb40b@devel
  radical.pilot        : 0.47-0.47-7-g6165842@devel
  radical.utils        : 0.47.4
  saga                 : 0.47.3
```

I am running the getting_started example of RP.  Getting the following error for every CU:
```
2018-03-30 19:19:32,496: agent_0             : MainProcess                     : agent_0.idler._check_units_cb: ERROR   : invalid state: {u'_id': u'unit.000016',
 u'client_sandbox': u'/home/vivek/Research/repos/radical.pilot/examples',
 u'cmd': [],
 u'control': u'agent_pending',
 u'description': {u'arguments': None,
                  u'cleanup': False,
                  u'cores': 1,
                  u'environment': None,
                  u'executable': u'/bin/date',
                  u'input_staging': [],
                  u'kernel': None,
                  u'mpi': False,
                  u'name': None,
                  u'output_staging': [],
                  u'pilot': None,
                  u'post_exec': None,
                  u'pre_exec': None,
                  u'restartable': False,
                  u'stderr': None,
                  u'stdout': None},
 u'exit_code': None,
 u'name': None,
 u'pilot': u'pilot.0000',
 u'pilot_sandbox': u'gsisftp://bw.ncsa.illinois.edu/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017621.0000/pilot.0000/',
 u'resource_sandbox': u'gsisftp://bw.ncsa.illinois.edu/scratch/sciteam/balasubr/radical.pilot.sandbox',
 u'state': 'FAILED',
 u'states': [u'NEW',
             u'UMGR_SCHEDULING_PENDING',
             u'UMGR_SCHEDULING',
             u'UMGR_STAGING_INPUT_PENDING',
             u'UMGR_STAGING_INPUT',
             u'FAILED'],
 u'stderr': None,
 u'stdout': None,
 u'type': u'unit',
 u'uid': u'unit.000016',
 u'umgr': u'umgr.0000',
 u'unit_sandbox': u'gsisftp://bw.ncsa.illinois.edu/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017621.0000/pilot.0000//unit.000016/'}
```

Logs attached 
[rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017621.0000.zip](https://github.com/radical-cybertools/radical.pilot/files/1865071/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017621.0000.zip)

**Comment by andre-merzky** [comment] 2018-03-31 08:15
Yeah, I just saw an announcement of new changes to the `bwpy` module - will investigate...

**Comment by andre-merzky** [comment] 2018-03-31 08:28
This might not be Python after all - can you please check if `fix/issue_1591` resolves this?  The Python update may trouble us when any user needs to create a new pilot VE - for existing VEs the change seems backward compatible.

**Comment by andre-merzky** [comment] 2018-05-02 11:28
@vivek-bala : ping

**Comment by vivek-bala** [comment] 2018-05-03 18:52
The bootstrapper fails with the following:
```
################################################################################
## Searching for available TCP port for tunnel in range 23000..23100.
## Found available port: 23000
PYTHON: /sw/bw/bwpy/mnt/bin/python
PIP   : /sw/bw/bwpy/mnt/bin/pip --cert /scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017654.0009/pilot.0000/../cacert.pem
virtenv_create   : TRUE
virtenv_update   : FALSE
rp install sources:  radical.utils-0.47.4/ saga-python-0.47.3/ radical.pilot-0.47.4-v0.47.4-1-ga0e949e-fix-issue-1591/
rp install target : SANDBOX
rp install lock   : FALSE
rp lock for ve create
obtained lock /mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw.0.47.4.lock

# -------------------------------------------------------------------
#
# Download virtualenv tgz
# cmd: curl -k -O 'https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.tar.gz'
#
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100   122  100   122    0     0    321      0 --:--:-- --:--:-- --:--:--   320
#
# SUCCESS
#
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# unpacking virtualenv tgz
# cmd: tar zxmf 'virtualenv-1.9.tar.gz'
#

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't unpack virtualenv! Using systemv version
ERROR: invalid or unusable virtenv_dist option
Error on virtenv creation -- abort
removed `/mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw.0.47.4.lock'
kill: no process ID specified
Try `kill --help' for more information.
```

Related to the changes on pypi, maybe?

**Comment by vivek-bala** [comment] 2018-05-03 19:00
Stack used:
```
$ radical-stack

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/vivek/Research/ves/ve-pytest

  radical.pilot        : 0.47.4-v0.47.4-1-ga0e949e@fix-issue_1591
  radical.utils        : 0.47.4
  saga                 : 0.47.3

```

**Comment by andre-merzky** [comment] 2018-05-07 19:26
This is a duplicate of #1600, which has been fixed.

**Comment by andre-merzky** [comment] 2018-07-02 11:56
fixed and merged.

**Closed by andre-merzky** 2018-07-02 11:56 UTC
Labels: comp:agent:bootstrapper, comp:agent:executor, priority:critical, topic:resource, type:bug
