### ISSUE TITLE
Jobs held indefinitely on osg.xsede-virt-cluster

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1241] opened 2017-02-23 10:25 UTC
```
python            : 2.7.6
virtualenv        : /home/mturilli/ve
radical.utils     : v0.45.RC2@HEAD-detached-at-v0.45.RC2
saga-python       : v0.45.RC2@HEAD-detached-at-v0.45.RC2
radical.pilot     : v0.45.RC2@HEAD-detached-at-v0.45.RC2

$ ./02_failing_units.py osg.xsede-virt-clust                                                                                                                       

================================================================================
 Getting Started (RP version v0.45.RC2)                                         
================================================================================

/home/mturilli/ve/local/lib/python2.7/site-packages/libcloud/utils/py3.py:71: UserWarning: Missing backports.ssl_match_hostname package
  warnings.warn("Missing backports.ssl_match_hostname package")
new session: [rp.session.radical.mturilli.017219.0015]                         \
database   : [mongodb://matteo:matteo@ds035385.mlab.com:35385/aimes-aws]      ok
read config                                                                   ok

--------------------------------------------------------------------------------
submit pilots                                                                   

create pilot manager                                                          ok
create pilot description [osg.xsede-virt-clust:1]                             ok
submit 1 pilot(s) .                                                           ok

--------------------------------------------------------------------------------
submit units                                                                    

create unit manager                                                           ok
add 1 pilot(s)                                                                ok
create 128 unit description(s)
        ........................................................................
        ........................................................              ok
submit 128 unit(s)
        ........................................................................
        ........................................................              ok

--------------------------------------------------------------------------------
gather results                                                                  

wait for 128 unit(s)
        |
```
On osg.xsede-virt-clust
```
$ condorqme


-- Submitter: mturilli@xd-login.opensciencegrid.org : <129.79.53.198:9615?... : xd-login.opensciencegrid.org
 ID      OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD               
36606399.0   mturilli        2/22 23:02   0+00:00:04 H  0   0.0  env /bin/sh -c /bi

1 jobs; 0 completed, 0 removed, 0 idle, 0 running, 1 held, 0 suspended
```
Session is still running in case live debugging could be useful but verbose debug is not enabled.

**Comment by andre-merzky** [comment] 2017-02-23 14:56
Matteo - I am afraid I can't reproduce it.   Could you please try again, to see if this was a fluke on OSG, or is bound to your account?  I'll run a couple more tests to exclude a positive fluke...

**Comment by mturilli** [comment] 2017-02-25 21:53
I tried multiple times and my job is always held indefinitely in the queue. As it does not happen to you, I would assume it is not a code-related problem. I am going to open a ticket with XSEDE and see whether they have some more insight.

**Comment by andre-merzky** [comment] 2017-02-25 22:25
thanks - lets see how far we get there...

**Comment by mturilli** [comment] 2017-02-26 17:41
I did not open a ticket with XSEDE because I was able to run experiments with 128 jobs without any held job. After running my experiments, I was able to run to examples of RP and then the problem presented itself again. I am not sure what is going on. 

If we want to investigate further, here the details of the last session in which I noticed the issue:
```
$ ./04_scheduler_selection.py osg.xsede-virt-clust

================================================================================
 Getting Started (RP version v0.45.RC2)                                         
================================================================================

/home/mturilli/ve/local/lib/python2.7/site-packages/libcloud/utils/py3.py:71: UserWarning: Missing backports.ssl_match_hostname package
  warnings.warn("Missing backports.ssl_match_hostname package")
new session: [rp.session.radical.mturilli.017223.0008]                         \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]                     ok
read config                                                                   ok

--------------------------------------------------------------------------------
submit pilots                                                                   

create pilot manager                                                          ok
create pilot description [osg.xsede-virt-clust:1]                             ok
submit 1 pilot(s) .                                                           ok

--------------------------------------------------------------------------------
submit units                                                                    

select scheduler                                               direct_submission
create unit manager                                                           ok
add 1 pilot(s)                                                                ok
create 256 unit description(s)
        ........................................................................
        ........................................................................
        ........................................................................
        ........................................                              ok
submit 256 unit(s)
        ........................................................................
        ........................................................................
        ........................................................................
        ........................................                              ok

--------------------------------------------------------------------------------
gather results                                                                  

wait for 256 unit(s)
        |
$ condorqme


-- Submitter: mturilli@xd-login.opensciencegrid.org : <129.79.53.198:9615?... : xd-login.opensciencegrid.org
 ID      OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD               
37602430.0   mturilli        2/26 17:12   0+00:00:08 H  0   0.0  env /bin/sh -c /bi

1 jobs; 0 completed, 0 removed, 0 idle, 0 running, 1 held, 0 suspended
```

**Comment by andre-merzky** [comment] 2017-02-26 20:25
Turns out that setting `RADICAL_PILOT_PROFILE=True` will avoid the HOLD state.  Current assumption is that some missing file causes hangs on output staging again, as we have seen that before - but I could not  yet nail that down.

With that info though, I consider this a problem of the RP layer in constructing a JD which is not suitable for OSG -- the SAGA layer seems to do the right things here.  It is a peculiarity of OSG to hang when files for output staging are missing, there is not much on the SAGA side to do in that respect.

If solving that is relevant for v0.45 I am not sure.  FWIW, the respective code paths have largely changed in the split branches, as the bulk support for pilot submission fundamentally changes how the job description is constructed and staging files are handled, specifically in the context of OSG.

Note that #1245 came also up in the context of these tests, but is considered a different problem altogether: there is no `HOLD` state involved.

**Comment by ibethune** [comment] 2017-02-27 15:47
We will document around this for now, as discussed in #1250

**Comment by andre-merzky** [comment] 2017-04-17 11:10
I think I see the problem - can you please give the RP branch `fix/1241` a try?  Thanks!

**Comment by ibethune** [comment] 2017-04-27 08:36
Hi @mturilli please update when you get a chance.

**Comment by mturilli** [comment] 2017-04-27 11:14
Probably unrelated to this specific ticket but the following happens when I try to test this fix branch:

```
$ radical-stack 
python            : 2.7.6
virtualenv        : /home/mturilli/ve/AIMES-EXPERIENCE
radical.utils     : 0.45
saga-python       : v0.44-137-g98a692ed@experiment-aimes
radical.pilot     : split-56-gaabb2eea@fix-1241
```

When running my code:
```
submit 512 pilot(s)
        ........................................................................ 
        ........................................................................
        ........................................................................
        ........................................................................
        ........................................................................
        ........................................................................
        ........................................................................ 
        ........                                                              ok
create unit manager                                                           ok
add 512 pilot(s)                                                              ok
submit 512 unit(s)
        ........................................................................
        ........................................................................ 
        ........................................................................
        ........................................................................
        ........................................................................
        ........................................................................ 
        ........................................................................
        ........                                                              ok
wait for 512 unit(s)
        |Caught exception, exit now: 
closing session rp.session.one.mturilli.017283.0001                   \ 
close unit manager                                                            ok
close pilot manager                                                            \
wait for 512 pilot(s)
                                                                              ok 
                                                                              ok
session lifetime: 97.2s                                                       ok 
modes   : export
db url  : mongodb://matteo:matteo@ds035385.mlab.com:35385/aimes-aws
session : rp.session.one.mturilli.017283.0001
age     : -999999999 days, 0:00:00
check  session rp.session.one.mturilli.017283.0001 + (   2:01:38.073676)
export session rp.session.one.mturilli.017283.0001.json
Traceback (most recent call last):
  File "experiment.py", line 90, in <module>
    aimes.emgr.execute_workload(cfg, run)
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/aimes/emgr/emgr.py", line 734, in execute_workload
    umgr.wait_units()
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 835, in wait_units
    time.sleep (0.1)
KeyboardInterrupt
```

In the logs I see:
```
2017-04-27 13:08:39,275: radical.saga.pty    : pmgr.launching.0                : MainThread     : DEBUG   : read : [  219] [   86] (/bin/sh: .saga/adaptors/shell_job//wrapper.sh: No such file or directo
ry\nPROMPT-127->)
```

**Comment by mturilli** [comment] 2017-04-27 17:21
I tried to upgrade the stack:
```
$ radical-stack                                                                                       
python            : 2.7.6
virtualenv        : /home/mturilli/ve/AIMES-EXPERIENCE
radical.utils     : 0.45
saga-python       : split-15-g41ed411c@devel
radical.pilot     : split-56-gaabb2eea@fix-1241
```

Job failed but without that error:
```
2017-04-27 19:12:04,945: radical.saga.cpi    : pmgr.launching.0                : MainThread     : INFO    : Found Condor tools: {'condor_version': '/usr/bin/condor_version', 'condor_rm': '/usr/bin/condor_rm', 'condor_vacate': '/usr/bin/condor_vacate', 'condor_q': '/usr/bin/condor_q', 'condor_history': '/usr/bin/condor_history', 'condor_submit': '/usr/bin/condor_submit'}
2017-04-27 19:13:08,931: radical.saga        : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
2017-04-27 19:13:08,931: radical.saga        : MainProcess                     : MainThread     : INFO    :                      pid: 7495
2017-04-27 19:13:08,932: radical.saga        : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2017-04-27 19:13:08,932: radical.saga        : MainProcess                     : MainThread     : INFO    : radical.saga         version: split-15-g41ed411c@devel 
2017-04-27 19:13:08,935: radical.pilot       : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.6 (default, Oct 26 2016, 20:30:19
) [GCC 4.8.4]
2017-04-27 19:13:08,935: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      pid: 7495
2017-04-27 19:13:08,935: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2017-04-27 19:13:09,161: radical.saga        : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.6 (default, Oct 26 2016, 20:30:19
) [GCC 4.8.4]
2017-04-27 19:13:09,161: radical.saga        : MainProcess                     : MainThread     : INFO    :                      pid: 7506
2017-04-27 19:13:09,161: radical.saga        : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2017-04-27 19:13:09,161: radical.saga        : MainProcess                     : MainThread     : INFO    : radical.saga         version: split-15-g41ed411c@devel
2017-04-27 19:13:09,164: radical.pilot       : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.6 (default, Oct 26 2016, 20:30:19
) [GCC 4.8.4]
2017-04-27 19:13:09,164: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      pid: 7506
2017-04-27 19:13:09,164: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2017-04-27 19:19:27,741: radical.saga        : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.6 (default, Oct 26 2016, 20:30:19
) [GCC 4.8.4]
2017-04-27 19:19:27,741: radical.saga        : MainProcess                     : MainThread     : INFO    :                      pid: 7761
2017-04-27 19:19:27,741: radical.saga        : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2017-04-27 19:19:27,741: radical.saga        : MainProcess                     : MainThread     : INFO    : radical.saga         version: split-15-g41ed411c@devel
2017-04-27 19:19:27,744: radical.pilot       : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.6 (default, Oct 26 2016, 20:30:19
) [GCC 4.8.4]
2017-04-27 19:19:27,744: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      pid: 7761
2017-04-27 19:19:27,744: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
```

Checking my queue on the machine I see:
```
$ condorqme
Error: Collector has no record of schedd/submitter
```

Maybe `xd-login.opensciencegrid.org` is down at the moment...

**Comment by andre-merzky** [comment] 2017-04-28 07:33
Matteo - I merged #1331 into devel now - independent of this fixing this ticket or not, that PR was a necessary fix.  So, please let me know if that pops up again with the current devel stack (or with the termination stack for that matter, which has the same changes merged).

**Comment by mturilli** [comment] 2017-05-08 16:31
I am not able to test because RP (likely SAGA) is not able to submit pilots to xd-login:
```
$ radical-stack
  python               : 2.7.6
  pythonpath           : 
  virtualenv           : /home/mturilli/ve/AIMES-EXPERIENCE

  radical.pilot        : split-102-g6eb33253@feature-split_termination_4
  radical.utils        : v0.45-45-gce49d06@feature-managed_process 
  saga                 : split-16-g4be5f196@devel
```
Error:
```
\^CCaught exception, exit now: 
closing session rp.session.one.mturilli.017293.0001                   \
close unit manager                                                            ok
close pilot managerTraceback (most recent call last):
  File "experiment.py", line 90, in <module>
    aimes.emgr.execute_workload(cfg, run)
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/aimes/emgr/emgr.py", line 764, in execute_workload
    session.close(cleanup=False, terminate=True)
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/radical/pilot/session.py", line 434, in close
    pmgr.close(terminate=terminate)
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 186, in close
    self.cancel_pilots()
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 631, in cancel_pilots
    'uids' : uids}})
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1359, in publish
    raise RuntimeError("can't route '%s' notification: %s" % (pubsub, msg))
RuntimeError: can't route 'control_pubsub' notification: {'cmd': 'cancel_pilots', 'arg': {'uids': ['pilot.0002', 'pilot.0003', 'pilot.0000', 'pilot.0001', 'pilot.0006', 'pilot.0007', 'pilot.0004', 'pilot.0005'], 'pmgr': 'pmgr.0000'}}
```

**Comment by andre-merzky** [comment] 2017-05-14 19:06
The exception you see is probably not the cause, but a side effect.  It should be gone in latest devel - but that does not mean your original problem is gone.  Can you send me a tarball of the local logfiles, please?  Thanks!

**Comment by andre-merzky** [comment] 2017-05-14 19:06
PS.: wanted to mention that I can run on xd-login all right, FWIW...

**Comment by andre-merzky** [comment] 2017-05-16 14:25
My stack is:

```
  radical.pilot        : split-70-gca882d8@devel
  radical.utils        : v0.45-46-g591b33d@devel
  saga                 : split-18-gc074c76@devel
```

You should be able to re-create this with `radical-stack-clone -v ve -b devel`.

Thanks, Andre.

**Comment by ibethune** [comment] 2017-05-22 08:34
Hi @mturilli did you get a chance to retry this, if not please do so ASAP?

**Comment by mturilli** [comment] 2017-05-30 15:19
Tested and pilots still do not start on `xd-login.opensciencegrid.org`.

Digging into the logs, I see:
```
Sorry, the project you specified (TG-CCR140028) is not valid or 
you are not in the list of allowed users.

Based on your username, here is a list of projects you might have 
access to:

. Script was: 
```
This error was uncaught by RCT. I would leave this ticket open until this (type of) error is not caught and the execution is terminated.

**Comment by andre-merzky** [comment] 2017-05-31 22:38
Thanks, that makes sense now.  I would take this off the 0.46 milestone then though, if that's ok for you?

**Closed** 2019-03-27 13:49 UTC
Labels: layer:saga, priority:high, topic:data, topic:execution, type:bug
