### ISSUE TITLE
Pilot does not become Active

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#494] opened 2015-03-10 22:12 UTC
OK, this does not happen everytime I run my application, but once in while Pilot does not reach Active state - it just keeps hanging in PendingActive state forever. On a resource the job is seen as running and "runs" until the allocated time elapses, while my application waits for a pilot to become Active. I am not sure how to reproduce this.

**Comment by andre-merzky** [comment] 2015-03-10 22:32
Would you please check if there are any log files in the pilot sandbox on the target resource?  if so, could you attache them, please?

**Comment by AntonsT** [comment] 2015-03-10 22:51
I don't think I have anything as of now, but next time I will get the logs. Has anyone experienced something similar or is it just me?

**Comment by AntonsT** [comment] 2015-03-10 23:03
I can add logs from Pilot which was cancelled manually after ten minutes of "running" with ctrl+c, will it be helpful?

**Comment by AntonsT** [comment] 2015-03-10 23:20
Also, why it takes so long for a Pilot to reach Active state? I observe times like 5 mins or so, after the job become "running" on a resource.

**Comment by andre-merzky** [comment] 2015-03-11 06:11
Yes, a local log might also help.

Re startup time: this very much depends on the specific resource and configuration.  For the master branch, ever pilot is creating its own, private virtualenv (on most resources), and that can take some time on some machines.  The devel branch switches to re-using VEs (again, on most resources) -- so only the first pilot on that resources (per user) has that overhead.  If that is really the cause for the delay could again be checked from the agent.out and agent.log, in case you have those around.  What resource are we talking about?

**Comment by AntonsT** [comment] 2015-03-11 12:32
>The devel branch switches to re-using VEs (again, on most resources) -- so only the first pilot on that resources (per user) has that overhead

Great!

This is on Trestles. Will attach logs soon. The thing is, bootstrapping was done previously as well, but it never took so long (consistently).

**Comment by oleweidner** [comment] 2015-03-11 13:05
RE Startup Time: I've seen pip "hanging" for minutes in the past due to bad network connections or heavy load on pypi.python.org. This might just be an one-off glitch...

**Comment by andre-merzky** [comment] 2015-05-05 12:12
Antons, is there any update on this ticket?

**Comment by andre-merzky** [comment] 2015-09-15 08:59
Pilot startup times seem to be normal (ie. as expected) since quite some time.  I'll close this until a specific test case comes up which indicates otherwise.

**Closed by andre-merzky** 2015-09-15 08:59 UTC
Labels: optimization
