### ISSUE TITLE
RP stalls on certain units

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1477] opened 2017-10-20 00:41 UTC
I am running 8 pipelines with 7 stages each. In the third stage (units 32 - units 39) some units finish in the correct time (~ 2 hours) while others end up stalling for well over 8 hours. I check the NAMD logs (STDOUT) for those units and they all return the correct simulation wall time (2 hours). However those NAMD units are executing sequentially. Each NAMD executable is competing for resources, because the units are done executing two hours apart from each other. 

Tried the GPU branch and verified that the units are landing on noncompeting resources (I designated 8 cores for each NAMD unit. BW has 32 logical cores/node. 

```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/jdakka/UCL/gpu_branch_env/venv

  radical.pilot        : 0.47-v0.46.2-93-g379bd68d@feature-gpu
  radical.utils        : 0.47-v0.46-18-g003a153@devel
  saga                 : 0.47-v0.46-23-g21cb4e9d@feature-gpu
```

```
unit.000016/radical_pilot_cu_launch_script.sh:/opt/xalt/0.7.6/sles11.3/bin/aprun -n 8 -N 8 -L 12474 -d 1 -cc 0:1:2:3:4:5:6:7 /u/sciteam/jphillip/NAMD_build.latest/NAMD_2.12_CRAY-XE-MPI-BlueWaters/namd2 "2j6m-a698g/mineq_confs/eq0.conf"  
unit.000017/radical_pilot_cu_launch_script.sh:/opt/xalt/0.7.6/sles11.3/bin/aprun -n 8 -N 8 -L 12474 -d 1 -cc 8:9:10:11:12:13:14:15 /u/sciteam/jphillip/NAMD_build.latest/NAMD_2.12_CRAY-XE-MPI-BlueWaters/namd2 "2j6m-a698g/mineq_confs/eq0.conf"  
unit.000018/radical_pilot_cu_launch_script.sh:/opt/xalt/0.7.6/sles11.3/bin/aprun -n 8 -N 8 -L 12474 -d 1 -cc 16:17:18:19:20:21:22:23 /u/sciteam/jphillip/NAMD_build.latest/NAMD_2.12_CRAY-XE-MPI-BlueWaters/namd2 "2j6m-a698g/mineq_confs/eq0.conf"  
unit.000019/radical_pilot_cu_launch_script.sh:/opt/xalt/0.7.6/sles11.3/bin/aprun -n 8 -N 8 -L 12474 -d 1 -cc 24:25:26:27:28:29:30:31 /u/sciteam/jphillip/NAMD_build.latest/NAMD_2.12_CRAY-XE-MPI-BlueWaters/namd2 "2j6m-a698g/mineq_confs/eq0.conf"  
```

Each NAMD output shows that it lands on `[Partition 0][Node 0]`
However checking the PROF files, it shows that the units are still executing sequentially, two hours apart. 

Given that, is this an `aprun` issue or should I look within NAMD to assign each unit to particular cores?

**Comment by andre-merzky** [comment] 2017-10-20 08:44
Hi Jumana, 

one way to find out what is causing this (RP or aprun) would be to run a pbs script with the same set of aprun commands, like

```
#PBS -l walltime=00:30:00
#PBS -l nodes=16
#PBS -A CSC230
#PBS -o /lustre/atlas/scratch/merzky1/csc230/radical.pilot.sandbox/test.out
#PBS -e /lustre/atlas/scratch/merzky1/csc230/radical.pilot.sandbox/test.err
#PBS -q devel

NODE=`tail -n 1 $PBS_NODEFILE`
SBOX=/lustre/atlas/scratch/merzky1/csc230/radical.pilot.sandbox
SID=rp.session.titan-ext1.merzky1.017458.0003


cd $SBOX/$SID/unit.000000
/opt/xalt/0.7.6/sles11.3/bin/aprun -n 8 -N 8 -L $NODE -d 1 -cc 0:1:2:3:4:5:6:7 /u/sciteam/jphillip/NAMD_build.latest/NAMD_2.12_CRAY-XE-MPI-BlueWaters/namd2 "2j6m-a698g/mineq_confs/eq0.conf" &

cd $SBOX/$SID/unit.000001

unit.000017/radical_pilot_cu_launch_script.sh:/opt/xalt/0.7.6/sles11.3/bin/aprun -n 8 -N 8 -L $NODE -d 1 -cc 8:9:10:11:12:13:14:15 /u/sciteam/jphillip/NAMD_build.latest/NAMD_2.12_CRAY-XE-MPI-BlueWaters/namd2 "2j6m-a698g/mineq_confs/eq0.conf"  &

echo "started: `date`"
wait
echo "stop 1: `date`"
wait
echo "stop 2: `date`"
```
(with a different `$SBOX` and `$SID`).

This will run 2 apruns concurrently, and you should be able to see if they stop approximately at the same time, which would mean they run concurrently; if the runtime is approx. as expected, which would mean they run on their own set of cores.

Does that make sense?  Let me know what you see!

**Comment by jdakka** [comment] 2017-10-31 20:36
Hi Andre,

I executed the following instead because I'm not sure why you asked for -l nodes=16 and not just -l nodes=1 with 16 processes

Output: indeed the 2 apruns still run sequentially from the NAMD logs. Let me know if I ran this correctly. 

```
#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=03:00:00
#PBS -q high
cd scratch/radical.pilot.sandbox/rp.session.two.jdakka.017465.0000/pilot.0000/unit.000037


/opt/xalt/0.7.6/sles11.3/bin/aprun -n 8 -N 8 -d 1 -cc 0,2,4,6,8,10,12,14 /u/sciteam/jphillip/NAMD_build.latest/NAMD_2.12_CRAY-XE-MPI-BlueWaters/namd2 "2j6m-a698g/mineq_confs/eq2.conf" & 

/opt/xalt/0.7.6/sles11.3/bin/aprun -n 8 -N 8 -d 1 -cc 1,3,5,7,9,11,13,15 /u/sciteam/jphillip/NAMD_build.latest/NAMD_2.12_CRAY-XE-MPI-BlueWaters/namd2 "2j6m-a698g/mineq_confs/eq2.conf" &


echo "started: `date`"
wait
echo "stop 1: `date`"
wait
echo "stop 2: `date`"
```

**Comment by andre-merzky** [comment] 2017-10-31 21:07
Thanks, that is what I wanted to look at indeed.  Let me try to reproduce and debug - that should not have happened.

**Comment by andre-merzky** [comment] 2017-11-04 08:25
Hey Jumana, 

I have not been able to reproduce this with simpler workloads.  Can you please pack up that unit sandbox and attach it to the ticket, so that I can run the real thing?  In case this is very long running: do you happen to have shorter running versions (a minute or so)?

Thanks!

**Comment by jdakka** [comment] 2017-11-07 03:00
Hi Andre,

I tried a few things on Friday and received an answer from Blue Waters today about running MPI on compute nodes.

I ran MPI hello_world.c and overloaded both physical and logical cores

```
#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=03:00:00
#PBS -q high

cd /u/sciteam/dakka/stage_5_namd_profiling/64_cores_mpi_2_apruns

aprun -n 8 -N 8 -d 1 -cc 0,2,4,6,8,10,12,14 ./a.out 45 & 

aprun -n 8 -N 8 -d 1 -cc 1,3,5,7,9,11,13,15 ./a.out 52 &

aprun -n 8 -N 8 -d 1 -cc 0,2,4,6,8,10,12,14 ./a.out 70 &

aprun -n 8 -N 8 -d 1 -cc 1,3,5,7,9,11,13,15 ./a.out 81 &

aprun -n 8 -N 8 -d 1 -cc 1,3,5,7,9,11,13,15 ./a.out 100 &
```

What I saw is that these a.out runs ran out of order and it seemed like they were running concurrently (however the task duration as quite low so I cannot verify this). The next step was to ask BW how to run 2 MPI programs on the same node using 8 PHYSICAL cores by pinning each each program to a different socket using the -cc flag. 

Their response was the following:


>There are a variety of ways to accomplish the core placement, and using -cc is a good strategy.  However you may not run 2 MPI applications together on a node.  Only 1 MPI application may run on a compute node.  You can run different applications together in a common MPI_COMM_WORLD in separate compute nodes ( https://bluewaters.ncsa.illinois.edu/launching-mpmd-jobs) , but any given compute node may only run a single MPI application. See "RESTRICTIONS" at the bottom of the URL above.See also:https://bluewaters.ncsa.illinois.edu/using-aprunFrom the aprun description, consider core 0 and 4 to be in 2 distinct processors or NUMA domains (though in the same socket).  This would run a process in each processor / NUMA domain:aprun -cc 0,4,8,12,16,20,24,28

**Comment by andre-merzky** [comment] 2017-11-07 22:26
Well, that's an interesting reply.  If aprun is not able to place 2 CUs on the same node, that pretty much explains what you see, and is a good motivation to use 32 cores.  We are likely able to work around this by using ORTE instead of aprun though. I am not sure if that is an option for you?  ORTE has other limitations, like very limited support for unit pre- and post-exec, and I am not sure exactly how stable it is for your workload... :/

**Comment by jdakka** [comment] 2017-11-08 19:38
Ok I'll resort to 32 cores using `aprun` until further discussion

**Comment by andre-merzky** [comment] 2017-11-09 07:55
If you don't mind, lets leave this ticket open.  I still can't reconcile this with the tests I did, so I want to follow up eventually.  But I would say that you should go ahead with 32 cores: the information from support is sufficient justification for that, IMHO.

**Comment by vivek-bala** [comment] 2019-03-28 13:21
@andre-merzky do you still want to keep this ticket open?

**Comment by andre-merzky** [comment] 2019-03-28 14:26
We may want to document this as a BW limitation.  But since BW is going away soon we might not care.  @mturilli : any opinion?

**Comment by mturilli** [comment] 2019-03-28 16:52
I went through the ticket. We should remember the following from BW documentation:
```
* - We refer to the Bulldozer Core compute unit as a single compute "core" and consider the Interlagos processors as having 8 (floating point) cores each. On the XE nodes there are 2 Interlagos processors and each processor has 8 cores.

** - The Interlagos processor is viewed by the Linux operating system in /proc/cpuinfo as having 16 "processors" per chip. These "processors" are the schedualable integer cores that work with the floating point unit. The moab/torque resource scheduler and Cray ALPS also see the integer cores as the smallest unit.
```
This could explain the observed behavior. 

Said that, I do not think more testing is warrant because, at the moment, the two active use cases we have on BW are not reporting this issue and we are not going to support any new use case on this machine. I would propose to keep this ticket as documentation and close it.

**Comment by andre-merzky** [comment] 2019-03-28 20:22
Thanks for digging this out!  Agree on the proposal - closing.

**Closed by andre-merzky** 2019-03-28 20:22 UTC
Labels: topic:resource, type:enhancement, type:performance
