### ISSUE TITLE
Test RP locally on a Windows machine using the Unix app/process

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1812] opened 2019-02-13 16:25 UTC

**Comment by andre-merzky** [comment] 2019-02-13 18:57
I don't think we'll support windows anytime soon.  At least at the moment, we do too many unix specific things on process and thread management and on polling communication channels which are unix specific.  Well, I do not know the state of POSIX emulation on Windows nowadays, so it *might* just work - but I doubt it, and, honestly, I wouldn't trust it...

Sorry for not having a more positive reply.  Its interesting to see this request, but I don't think we have the resources to consider windows support....

**Comment by iparask** [comment] 2019-02-13 19:01
There is an Ubuntu app for Windows. It is the one I am using to work. The purpose of the issue is for me to remember and run a small example.

I agree that we do a lot of unix specific and that windows support is not guaranteed, but it might be useful if some of the examples do actually run ( out of luck). That would reduce some overheads for tutorials.

**Comment by andre-merzky** [comment] 2019-02-13 19:08
Reduce overhead how?  instead of ssh to a VM, people would have to use the ubuntu or posix layer.  If something goes wrong on the VM, we can help.  If something goes wrong on Windows, we can't.  Well, I can't I should say, but you get my point ;-)

To be blunt: I am somewhat worried that you manage to actually run one of our examples, and suddenly Windows is listed as supported.  Or it is just mentioned to potential users that we have been able to use windows, and this raises expectations as to this being a viable platform...

Don't get me wrong: this is interesting to do, I agree on that - but...

**Comment by andre-merzky** [comment] 2019-04-03 09:12
@iparask : I would suggest we either test this soon or close it - otherwise it has a high likelihood to become a stale ticket very quickly...

**Comment by iparask** [comment] 2020-05-05 20:30
I would say close it.

**Closed by iparask** 2020-05-05 20:30 UTC
Labels: layer:rct, priority:low, topic:resource, type:feature
