### ISSUE TITLE
2048 cores pilot unclean exit/cancel

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#466] opened 2015-01-02 09:32 UTC
Branch: master

When running a 2048 core pilot with 2048 concurrent tasks, I see the following error in AGENT.LOG:
```
2015-01-02 00:15:59,465 - radical.pilot.agent - INFO - Received Cancel Pilot command.
2015-01-02 00:15:59,466 - radical.pilot.agent - WARNING - CANCEL received. Terminating.
2015-01-02 00:15:59,642 - radical.pilot.agent - ERROR - ERROR in agent main loop: command document too large. Traceback (most recent call last):
  File "radical-pilot-agent.py", line 2058, in run
    pilot_CANCELED(self._p, self._pilot_id, self._log, "CANCEL received. Terminating.")
  File "radical-pilot-agent.py", line 205, in pilot_CANCELED
    "finished"    : ts}
  File "/work/02855/mturilli/radical.pilot.sandbox/pilot-54a6278523769c0c95ecdf71/virtualenv/lib/python2.7/site-packages/pymongo/collection.py", line 551, in update
    docs, check_keys, self.uuid_subtype, client)
DocumentTooLarge: command document too large
```
And in AGENT.STDERR:
```
2015:01:02 00:15:59 115636 Thread-1     radical.pilot.agent   : [INFO    ] Received Cancel Pilot command.
2015:01:02 00:15:59 115636 Thread-1     radical.pilot.agent   : [WARNING ] CANCEL received. Terminating.
2015:01:02 00:15:59 115636 Thread-1     radical.pilot.agent   : [ERROR   ] ERROR in agent main loop: command document too large. Traceback (most recent call last):
  File "radical-pilot-agent.py", line 2058, in run
    pilot_CANCELED(self._p, self._pilot_id, self._log, "CANCEL received. Terminating.")
  File "radical-pilot-agent.py", line 205, in pilot_CANCELED
    "finished"    : ts}
  File "/work/02855/mturilli/radical.pilot.sandbox/pilot-54a6278523769c0c95ecdf71/virtualenv/lib/python2.7/site-packages/pymongo/collection.py", line 551, in update
    docs, check_keys, self.uuid_subtype, client)
DocumentTooLarge: command document too large

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/apps/python/epd/7.3.2/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "radical-pilot-agent.py", line 2164, in run
    "ERROR in agent main loop: %s. %s" % (str(ex), traceback.format_exc()))
  File "radical-pilot-agent.py", line 172, in pilot_FAILED
    "finished"    : ts}
  File "/work/02855/mturilli/radical.pilot.sandbox/pilot-54a6278523769c0c95ecdf71/virtualenv/lib/python2.7/site-packages/pymongo/collection.py", line 551, in update
    docs, check_keys, self.uuid_subtype, client)
DocumentTooLarge: command document too large
```
Meanwhile, in the debug log of the script I see a 'never ending' :
```
[...]
2015:01:02 09:01:22 radical.pilot.MainProcess: [ERROR   ] pmgr    54a6276823769c0c95ecdf70 wait for pilot  54a6278523769c0c95ecdf71 (Active)
2015:01:02 09:01:23 radical.pilot.MainProcess: [ERROR   ] pmgr    54a6276823769c0c95ecdf70 wait for pilot  54a6278523769c0c95ecdf71 (Active)
2015:01:02 09:01:24 radical.pilot.MainProcess: [ERROR   ] pmgr    54a6276823769c0c95ecdf70 wait for pilot  54a6278523769c0c95ecdf71 (Active)
2015:01:02 09:01:25 radical.pilot.MainProcess: [ERROR   ] pmgr    54a6276823769c0c95ecdf70 wait for pilot  54a6278523769c0c95ecdf71 (Active)
2015:01:02 09:01:26 radical.pilot.MainProcess: [ERROR   ] pmgr    54a6276823769c0c95ecdf70 wait for pilot  54a6278523769c0c95ecdf71 (Active)
2015:01:02 09:01:27 radical.pilot.MainProcess: [ERROR   ] pmgr    54a6276823769c0c95ecdf70 wait for pilot  54a6278523769c0c95ecdf71 (Active)
2015:01:02 09:01:28 radical.pilot.MainProcess: [ERROR   ] pmgr    54a6276823769c0c95ecdf70 wait for pilot  54a6278523769c0c95ecdf71 (Active)
[...]
```
Notes:
* All the tasks appear to have been completed successfully.
* An explicit kill of the python interpreter is required to exit the application script.

**Comment by andre-merzky** [comment] 2015-01-02 11:40
Hi Matteo, 

this is a real bug -- the MongoDB docs should not grow that large.  My hunch is that this is caused by the slot bookkeeping, which generates quite some data.  I'll add some safeguard for the doc size, but it may result in incomplete statistics... :/  Let me ponder over that...

**Comment by andre-merzky** [comment] 2015-01-08 20:50
This should be addressed in the feature/aimes-experiments branch -- please give it a try!

**Comment by andre-merzky** [comment] 2015-05-05 14:36
Slot bookeeping has been changed in the context of this ticket, and is now released.

**Closed by andre-merzky** 2015-05-05 14:36 UTC
Labels: Bug, HOTFIX
