### ISSUE TITLE
RP (devel) fails on archer

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#838] opened 2015-10-14 23:59 UTC
I tried Ensemblemd with RP devel branch (with 0.36 saga, 0.36.RC1-10-g19b336e@feature-demo radical utils). The Pilot goes to 'Done' state after 'PendingActive'.

agent_0.err:
```
2015-10-14 23:58:48,777: radical.saga        : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.6 (default, Mar 10 2014, 14:13:45) [GCC 4.8.1 20130531 (Cray Inc.)]
2015-10-14 23:58:48,777: radical.saga        : MainProcess                     : MainThread     : INFO    :                      pid: 21196
2015-10-14 23:58:48,778: radical.saga        : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2015-10-14 23:58:48,778: radical.saga        : MainProcess                     : MainThread     : INFO    : radical.saga         version: 0.36
2015-10-14 23:58:48,788: radical.pilot       : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.6 (default, Mar 10 2014, 14:13:45) [GCC 4.8.1 20130531 (Cray Inc.)]
2015-10-14 23:58:48,788: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      pid: 21196
2015-10-14 23:58:48,788: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2015-10-14 23:58:48,788: radical.pilot       : MainProcess                     : MainThread     : INFO    : radical.pilot        version: v0.36-80-g8b8e1ea@devel-vivek
Traceback (most recent call last):
  File "/work/e290/e290/vb224/radical.pilot.sandbox/rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.016722.0012-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 6230, in <module>
    bootstrap_3()
  File "/work/e290/e290/vb224/radical.pilot.sandbox/rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.016722.0012-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 6181, in bootstrap_3
    agent.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
Exception KeyError: KeyError(140484230231904,) in <module 'threading' from '/work/y07/y07/cse/python/2.7.6/lib/python2.7/threading.pyc'> ignored
``` 

I have tested this stack of rp, saga, ru on stampede and it seems to be working fine.
Note: I have branched off rp devel as devel-vivek (I was using docs_am branch previously, I have created devel-vivek after docs_am got merged with devel).

**Comment by andre-merzky** [comment] 2015-10-15 00:03
that specific error (`'NoneType' object has no attribute 'stop'`) is fixed in `feature/radical_undebug`, but that error only hides another error beneath.  Would you mind trying that branch and reporting what that underlying error is for you?  Thanks!

**Comment by vivek-bala** [comment] 2015-10-15 00:10
Now the pilot goes from 'PendingActive' to 'Failed'.

agent_0.err:
```
2015-10-15 01:08:45,331: radical.saga        : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.6 (default, Mar 10 2014, 14:13:45) [GCC 4.8.1 20130531 (Cray Inc.)]
2015-10-15 01:08:45,332: radical.saga        : MainProcess                     : MainThread     : INFO    :                      pid: 25282
2015-10-15 01:08:45,332: radical.saga        : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2015-10-15 01:08:45,332: radical.saga        : MainProcess                     : MainThread     : INFO    : radical.saga         version: 0.36
2015-10-15 01:08:45,342: radical.pilot       : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.6 (default, Mar 10 2014, 14:13:45) [GCC 4.8.1 20130531 (Cray Inc.)]
2015-10-15 01:08:45,342: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      pid: 25282
2015-10-15 01:08:45,342: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2015-10-15 01:08:45,342: radical.pilot       : MainProcess                     : MainThread     : INFO    : radical.pilot        version: v0.36-82-g6ba881f@feature-radical_undebug
Traceback (most recent call last):
  File "/work/e290/e290/vb224/radical.pilot.sandbox/rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.016723.0000-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 6236, in <module>
    bootstrap_3()
  File "/work/e290/e290/vb224/radical.pilot.sandbox/rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.016723.0000-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 6176, in bootstrap_3
    if not agent.final_cause:
AttributeError: 'NoneType' object has no attribute 'final_cause'
Exception KeyError: KeyError(140706681919328,) in <module 'threading' from '/work/y07/y07/cse/python/2.7.6/lib/python2.7/threading.pyc'> ignored
```

**Comment by marksantcroos** [comment] 2015-10-15 08:23
This is fixed now, but this was not the root cause either. Can you run again and make the whole sandbox available? Thanks!

**Comment by vivek-bala** [comment] 2015-10-15 12:43
> Can you run again and make the whole sandbox available?

Which branch should I be using to run again ?

**Comment by marksantcroos** [comment] 2015-10-15 12:44
Branch release/v0.37 has the fix.

**Comment by marksantcroos** [comment] 2015-10-15 13:58
```raise RuntimeError('LRMS has no nodes left to run units')```

**Closed by marksantcroos** 2015-10-15 13:58 UTC
Labels: bug
