### ISSUE TITLE
RP-v0.36.RC1@devel fails on Blue Waters

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#781] opened 2015-10-01 17:26 UTC
with:
```
Traceback (most recent call last):
  File "/home/antons/rp36/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 328, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/antons/rp36/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 249, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "getting_started_remote.py", line 115, in pilot_state_cb
    sys.exit (1)
SystemExit: 1
```

I can see pilot being in the queue and then running on remote machine. [terminal output](https://gist.github.com/AntonsT/3e491811c75a181ecb3e)

**Comment by andre-merzky** [comment] 2015-10-01 17:30
Would you mind posting a tarball of the pilot sandbox somewhere?  Thanks!

**Comment by marksantcroos** [comment] 2015-10-01 19:07
wtf
```
2015-10-01 13:08:54,884: radical.saga.cpi    : MainProcess                     : Thread-8       : INFO    : Job monitoring thread updating Job [torque+gsissh://bw.ncsa.illinois.edu]-[2294985] (state: Running)
2015-10-01 13:09:10,601: radical.pilot       : MainProcess                     : Thread-1       : INFO    : ComputePilot 'pilot.0000' state changed from 'PendingActive' to 'Failed'.
```

**Comment by marksantcroos** [comment] 2015-10-01 19:07
Oh wait, there was time in between :)

**Comment by AntonsT** [comment] 2015-10-01 19:28
> Would you mind posting a tarball of the pilot sandbox somewhere? Thanks!

sure, [tarball](https://github.com/AntonsT/rp-logs/blob/master/rp.session.antons-pc.antons.016709.0010-pilot.0000.tar.gz)

**Comment by andre-merzky** [comment] 2015-10-01 20:28
The logfiles contain this exception:

```
agent_0.out:Error running agent: LRMS has no nodes left to run units
```

That means that all the nodes you specify as 'pilot size' are consumed by the pilot itself, and there is nothing left for the unit execution.  That should not happen with the test examples?  The remote examples uses 64 core, if I am not mistaken that translates to 4 nodes on BW.  The default cray agent config consumes one additional node (see https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/agent_cray.json#L24: agent_0 as target 'local', it runs on the mom-node; agent_1 has target 'node', it consumes a compute node).

So either you played with the pilot  size, or with the agent config.  Either is fine, of course, but you need to make sure that there are nodes left for execution.

But also, I guess we have to raise a better error message,  something more easily visible than a log entry on the target resource.  That is something which we need to address better in general...

**Comment by AntonsT** [comment] 2015-10-01 20:55
Thanks for your response Andre. 

>you need to make sure that there are nodes left for execution

Sorry, but I disagree. In case if pilot consumes one additional node why this node is not added to what is specified in a pilot description? When user specifies pilot size, assumption is that that number of cores is available. If this assumption is not valid how user can plan execution of his workload? For example, user may specify in a pilot description 64 cores and submit a bunch of 64 core CU's but none of which will execute.

**Comment by marksantcroos** [comment] 2015-10-01 21:01
> Sorry, but I disagree.

There is unfortunately no silver bullet here. Adding one node by default might make other users unhappy, as they will then allocate 1025 nodes, fall into a different allocation class, and wait 3 weeks longer than anticipated.

I have no opinion on which is better in general, as it really depends on the use case.

FWIW, we've had this discussion before, and one thing to take home from that is that this needs to be clearly documented.

I can even see us adding a flag to the pilot_desc, "agent_nodes_inclusive/exclusive = true/false" or so. Although that might just belong on the application level.

**Comment by marksantcroos** [comment] 2015-10-01 21:03
ps. can you acknowledge that the number of cores requested is the cause of the failure? Because then we can focus the discussion on the inclusive/exclusive issue.

**Comment by AntonsT** [comment] 2015-10-01 21:04
> can you acknowledge that the number of cores requested is the cause of the failure?

yes, pilot size was 32

**Comment by andre-merzky** [comment] 2015-10-01 23:13
Thanks - I'll close this issue then.

**Closed by andre-merzky** 2015-10-01 23:13 UTC
Labels: bug
