### ISSUE TITLE
Run fails with error in forking.py

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1280] opened 2017-03-13 19:57 UTC
```
$ radical-stack                                                               
python            : 2.7.6
virtualenv        : /home/mturilli/ve/AIMES-EXPERIENCE-XSEDE
radical.utils     : v0.45-2-g82050c5@devel
saga-python       : split-9-gf9b04d83@devel
radical.pilot     : split-27-g8e6be2ba@devel
```
Trace:
```
Traceback (most recent call last):
  File "experiment.py", line 90, in <module>
    aimes.emgr.execute_workload(cfg, run)
  File "/home/mturilli/ve/AIMES-EXPERIENCE-XSEDE/local/lib/python2.7/site-packages/aimes/emgr/emgr.py", line 767, in execute_workload
    session.close(cleanup=False, terminate=True)
  File "/home/mturilli/ve/AIMES-EXPERIENCE-XSEDE/local/lib/python2.7/site-packages/radical/pilot/session.py", line 369, in close
    umgr.close()
  File "/home/mturilli/ve/AIMES-EXPERIENCE-XSEDE/local/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 190, in close
    self._controller.stop()
  File "/home/mturilli/ve/AIMES-EXPERIENCE-XSEDE/local/lib/python2.7/site-packages/radical/pilot/utils/controller.py", line 229, in stop
    t.stop()
  File "/home/mturilli/ve/AIMES-EXPERIENCE-XSEDE/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 798, in stop
    self.join()
  File "/home/mturilli/ve/AIMES-EXPERIENCE-XSEDE/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 848, in join
    mp.Process.join(self, timeout)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

**Comment by andre-merzky** [comment] 2017-03-13 21:34
Thanks Matteo.  Does the code finish anyway, or is it stuck at this point?  Also, this looks like its happening during `session.close()`, so either the application is done, or failed due to some other error, thus shutting down.

Either way, this looks like part of our termination problem, I'm afraid :/

**Comment by mturilli** [comment] 2017-03-13 22:11
This was after submitting the pilot, when starting to execute CUs. Never saw this error before at that point of the execution. The error was fatal, the whole script (and RP) crashed and the shell was returned.

**Comment by ibethune** [comment] 2017-04-27 08:32
Cannot reproduce to debug. To close when termination code is merged.

**Comment by andre-merzky** [comment] 2017-05-14 19:33
is merged now....

**Closed by andre-merzky** 2017-05-14 19:33 UTC
Labels: termination
