### ISSUE TITLE
09_mpi_units.py fails when run localhost on the VM: Missing Python module

### ISSUE THREAD

**Issue by statho** [radical-cybertools/radical.pilot#1081] opened 2016-07-14 20:48 UTC
In the execution of 09_mpi_units.py each unit fails and I get the following result for each pilot:
* unit.000000: Fail, exit:  1, MPI ranks:

When I check the sandbox I face the following error:

Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py

**Comment by marksantcroos** [comment] 2016-07-14 20:51
Duplicate of #1067

**Comment by marksantcroos** [comment] 2016-07-14 20:55
Btw, what is "the vm" ?

**Comment by statho** [comment] 2016-07-14 22:04
It's the radical vm.

**Comment by marksantcroos** [comment] 2016-07-14 22:13
I installed mpi4py there, can you try again?

**Comment by statho** [comment] 2016-07-15 01:16
I have tried it again, yet it fails again giving me the same error.
When I go to the /usr/include directory to figure out the problem, I see 
that the mpi4py module is an orphan symlink.

**Comment by marksantcroos** [comment] 2016-07-16 10:28
Hmm, thanks for trying again, but lets step back.

Who are you actually? The account name is not very descriptive ;)

Not even sure we are talking about the same machine now, so what is the hostname of the machine that you are trying this?

I dont understand what /usr/include has to do with it.

**Comment by statho** [comment] 2016-07-16 16:23
My name is Anastasis Stathopoulos and I am in RADICAL Lab for an internship this summer.
The machine I used for testing is at 144.76.72.175 and I am the user statho.

**Comment by marksantcroos** [comment] 2016-07-16 18:08
Thanks, nice to "meet" you, and enjoy summer!

Now for the issue, then we are indeed talking about the same system. Believe it or not, not all the world is cloud, and this machine is just real hardware, so no VM or the like.

So when you login to the machine, whats the output of the following?
```
python -c "import mpi4py; print mpi4py.__version__"
```

**Comment by statho** [comment] 2016-07-16 18:41
Thank you!
The output is 2.0.0

**Comment by marksantcroos** [comment] 2016-07-16 18:57
Can you remove `/home/statho/radical.pilot.sandbox/ve_localhost` and then try again? You probably get a different error then, but at least then I understand why you are still getting the import error.

**Comment by statho** [comment] 2016-07-16 21:26
Mark, in my virtualenv there is no mpi4py module. 

(ve)statho@radical:~/testing/ve/share/radical.pilot/examples$ python -c "import mpi4py; print mpi4py.__version__"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named mpi4py

**Comment by marksantcroos** [comment] 2016-07-26 13:54
Did you try my suggestion?

**Comment by statho** [comment] 2016-07-26 15:57
I did Mark, yet upon checking the sandbox I face the same error:

Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
--------------------------------------------------------------------------
mpiexec noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------

**Comment by statho** [comment] 2016-07-26 16:00
I did Mark, yet upon checking the sandbox I face the same error:

Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py

--------------------------------------------------------------------------
mpiexec noticed that the job aborted, but has no info as to the process
that caused that situation.

--------------------------------------------------------------------------

**Comment by marksantcroos** [comment] 2016-07-27 19:42
Ok, well, I dont understand then why it would work for me and not for you. Do you need MPI on that machine?

**Comment by statho** [comment] 2016-07-27 22:46
No, I do not need MPI on that machine. I just raised this issue for the tutorial testing, which took place 2 weeks ago.

**Comment by marksantcroos** [comment] 2016-07-27 22:47
Ok, cool, thanks. The testing is much appreciated!

I'll close this ticket now though, until somebody really needs mpi there.

**Closed by marksantcroos** 2016-07-27 22:47 UTC
