### ISSUE TITLE
Couldn't call callback function 'NoneType' object has no attribute 'uid'

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#508] opened 2015-03-19 01:57 UTC
OK, this has troubled me for a while now. I am getting this error on both Trestles and Stampede. Often. The first errors are:
```
015:03:19 01:44:08 radical.pilot.MainProcess: [DEBUG   ] Completing entry '{'action': 'Copy', 'source': u'ala10_minimized.inpcrd', 'flags': ['CreateParents', 'SkipFailed'], 'target': u'staging:///replica_1_0/ala10_minimized.inpcrd', 'priority': 0}'
2015:03:19 01:44:08 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '550a29e823769c726c84561a' state changed from 'None' to 'New'.
2015:03:19 01:44:08 radical.pilot.MainProcess: [ERROR   ] Couldn't call callback function 'NoneType' object has no attribute 'uid'
2015:03:19 01:44:08 radical.pilot.MainProcess: [ERROR   ] uworker Thread-3 stops   itransfer InputFileTransferWorker-1
2015:03:19 01:44:08 radical.pilot.MainProcess: [ERROR   ] itransfer InputFileTransferWorker-1 stopping
2015:03:19 01:44:08 radical.pilot.MainProcess: [INFO    ] Scheduled ComputeUnits [] for execution on ComputePilot '550a297d23769c726c845617'.
2015:03:19 01:44:08 radical.pilot.MainProcess: [ERROR   ] itransfer InputFileTransferWorker-1 stopped
2015:03:19 01:44:08 radical.pilot.MainProcess: [ERROR   ] uworker Thread-3 stopped itransfer InputFileTransferWorker-1
2015:03:19 01:44:08 radical.pilot.MainProcess: [ERROR   ] uworker Thread-3 stops   itransfer InputFileTransferWorker-2
2015:03:19 01:44:08 radical.pilot.MainProcess: [ERROR   ] itransfer InputFileTransferWorker-2 stopping
2015:03:19 01:44:08 radical.pilot.MainProcess: [INFO    ] 0 units remain unscheduled
```

The rest can be found at (with debug flag):
https://gist.github.com/AntonsT/2fde8a7f755cfe402567

**Comment by marksantcroos** [comment] 2015-03-19 08:40
Duplicate of #449.

**Closed by marksantcroos** 2015-03-19 08:40 UTC
