### ISSUE TITLE
getting_started_osg.py - Unable to execute past 8 pilots

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#990] opened 2016-03-27 20:12 UTC
I have tried to run getting_started_osg.py with 8 pilots, each with 1 CU. However, the script stalls and the pmgr does not close correctly.

**Comment by andre-merzky** [comment] 2016-03-27 20:33
Let me try to reproduce this.  Are you running some version of the OSG example?

**Comment by mingtaiha** [comment] 2016-03-30 08:27
I am running the getting_started_osg.py that comes with the installation of RP.

**Comment by andre-merzky** [comment] 2016-03-30 09:41
Are you also using the backfilling scheduler in the case where the pilots time out prematurely (#989)?  Because, the BF scheduler currently adds some significant runtime overhead.

**Comment by andre-merzky** [comment] 2016-03-30 11:30
Hey Ming, 

when  changing the OSG example to run 8 pilots and 160 units, I get a runtime of about 1200s, i.e. about 20 min.  Usually, all 8 pilots come alive -- in one run, one of the pilots crashed or got disconnected, and the code then hangs, because the units don't get resubmitted, but the wait() still waits for them.  The example code is too simplistic/stupid to catch that case.

In what stage of the execution do you see the hanging?  What is the state of the pilots at that point?  Did any units complete at that point?

**Comment by andre-merzky** [comment] 2016-03-30 11:31
I should add that the unclean shutdown of the pmr in case of failures and user interrupts is a known problem -- sorry for that, but you will have to live with it for a little longer...

**Comment by andre-merzky** [comment] 2016-03-30 20:04
I am inclined to also see this as a duplicate of #989 - would you agree?

**Comment by mingtaiha** [comment] 2016-03-30 22:13
I see this hanging when after I execute some of the CUs. So some of the pilots finish, but the others do not launch.

Also I am curious: why do you think that this error is the same as the #989? Is it because the execution proceeds as it should and then hangs?

**Comment by andre-merzky** [comment] 2016-03-30 22:41
>  Also I am curious: why do you think that this error is the same as the #989? Is it because the execution proceeds as it should and then hangs?

Yes, indeed...

**Comment by mingtaiha** [comment] 2016-03-31 02:52
I'm ok with this for now. We can split the case up if we find that it is indeed not the case later.

**Comment by andre-merzky** [comment] 2016-03-31 20:34
ack

**Closed by andre-merzky** 2016-03-31 20:34 UTC
Labels: bug
