### ISSUE TITLE
Unit requires different MPI flavor from configured

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2128] opened 2020-04-23 16:50 UTC
Task description :
```
t.name = 'Preprocessing'       
t.executable = 'python'         
t.arguments = ['~/iwp_preprocessing.py'] 
t.cpu_reqs = {'processes': 28,
              'thread_type': 'OpenMP', 
              'threads_per_process': 1,
              'process_type': 'MPI'}
```

RADICAL-Stack
```
  python               : 3.7.0
  pythonpath           :
  virtualenv           : /home/aymen/iwp

  radical.entk         : 1.0.2
  radical.pilot        : 1.3.0
  radical.saga         : 1.3.0
  radical.utils        : 1.3.1
```

Pre_bootstrap loaded modules:
```
"module purge",
"module load gcc",
"module load mpi/gcc_openmpi",
"module load slurm",
"module load anaconda3
```
# Pre-exec commands and modules to load:
"module unload intel/19.5"
"module load intel/18.4"
"
In `unit000000.sh`  under `# The command to run`  my command look like the following:

```
mpirun  -np 28  -host r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351,r351 -x "LD_LIBRARY_PATH" -x "PATH" -x "PYTHONPATH" -x "OMP_NUM_THREADS" -x "CUDA_VISIBLE_DEVICES" -x "RP_AGENT_ID" -x "RP_GTOD" -x "RP_PILOT_ID" -x "RP_PILOT_STAGING" -x "RP_PROF" -x "RP_SESSION_ID" -x "RP_SPAWNER_ID" -x "RP_TMP" -x "RP_UNIT_ID" -x "RP_UNIT_NAME" -x "CUDA_VISIBLE_DEVICES"  python "~/iwp_preprocessing.py" 
```

The `STDERR` : 

```
[mpiexec@r351.pvt.bridges.psc.edu] match_arg (../../utils/args/args.c:254): unrecognized argument x
[mpiexec@r351.pvt.bridges.psc.edu] HYDU_parse_array (../../utils/args/args.c:269): argument matching returned error
[mpiexec@r351.pvt.bridges.psc.edu] parse_args (../../ui/mpich/utils.c:4773): error parsing input array
[mpiexec@r351.pvt.bridges.psc.edu] HYD_uii_mpx_get_parameters (../../ui/mpich/utils.c:5109): unable to parse user arguments
```

Based on Andre's preliminary analysis this is might happen because of :
```The switch between Hydra and Orte based MPIs is not working```

Next steps: 

- [x] Find out how `environment variables` are set in that version of `mpirun`
- [x] Check (https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/launch_method/mpirun.py#L101)
- [x] Check ( https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/launch_method/base.py#L369)

**Comment by iparask** [comment] 2020-04-30 18:48
Apparently, there is an issue when a unit tries to use a different MPI flavor from the one RP has discovered during launching the agent. One quick and dirty way to fix this is to change the RP's configuration before launching the agent, to point to the desired by the user MPI flavor. Although, this may be problematic for upper layers.

EnTK can configure RP as desired, since it is just above it. I am not sure though if we want to expose this capability to upper layers. I'm starting to think that the correct solution would be the nested configurations @mtitov has mentioned multiple times. 

What may be a solution is to expose something like `mpi_flavor` on the pilot's description, that will allow the agent to be launched with the correct MPI flavor. @andre-merzky, what do you think? Also, is it safe to assume that an application that has MPI units will always require the same MPI flavor for all?

I think that the environment is correct, that is `which mpirun` will return the Intel MPI path, not the gcc one.

@aymen or @SrinivasMushnoori , can you run a test where there is a `which mpirun` after the Intel module is loaded in the pre-exec and let us know what path is outputted?

**Comment by SrinivasMushnoori** [comment] 2020-04-30 18:50
On it. Might take a bit since queue times on bridges are INSANE.

**Comment by andre-merzky** [comment] 2020-04-30 18:53
I would like not to loose the ability to launch tasks with incompatible module loads, so one task requiring gcc, another requiring intel compiler.  Not that the problem does not only affect MPI tasks, but any task which depends on a specific compiler chain.  Also note that RP may not always be able to use a specific compiler chain, as we depend on a functional Python which in  turn may depend on a specific compiler.  

Ultimately I consider this a problem of isolation, not a problem of configuration.

**Comment by AymenFJA** [comment] 2020-04-30 19:00
I've been working on this problem with Andre. Please check [here](https://github.com/radical-cybertools/radical.pilot/blob/b66a60e59f66117c4a223e19a581821a63fc1f0f/src/radical/pilot/agent/launch_method/base.py#L392). Intel MPI check is now added to the base class as an attempt to fix it, but the problem still occurs. I will continue looking at it and it is definitely something need to be discussed during the devel call.

**Comment by iparask** [comment] 2020-04-30 19:09
> I would like not to loose the ability to launch tasks with incompatible module loads, so one task requiring gcc, another requiring intel compiler. Not that the problem does not only affect MPI tasks, but any task which depends on a specific compiler chain. Also note that RP may not always be able to use a specific compiler chain, as we depend on a functional Python which in turn may depend on a specific compiler.

I see. 

> Ultimately I consider this a problem of isolation, not a problem of configuration.

With you there. The question then becomes how the launch method configures the launch command based on the MPI flavor the user wants. The first is decided during launching the agent, and the latter during the CU description. Would it make sense the MPI launch method to probe the `pre_execs` and check the type of MPI after all pre_execs for each specific unit? This adds the overhead of running something on the terminal, probing stdout, stderr and making an on the fly decision.

**Comment by AymenFJA** [comment] 2020-04-30 19:15
BTW, I did run some tests before and they are the following:
If the user did not load any `MPI libraries ` then `which mpirun` is :

 `/usr/mpi/gcc/openmpi-2.1.2-hfi/bin/mpirun`
else:
`/opt/intel/compilers_and_libraries_2018.5.274/linux/mpi/intel64/bin/mpirun`

**Comment by andre-merzky** [comment] 2020-04-30 19:50
> MPI launch method to probe the pre_execs

Switching LMs per task is certainly an option, and one which has been discussed several time.  I would be in favor of that.  I though expect it comes with a significant performance penalty: loading modules per task is very expensive at scale.  Caching of environments might help.

I should mention that we have two LM options which do not suffer from that problem: (a) launch methods like (archived) `ORTE_LIB` or (prototyped) `FLUX` use python function calls to talk to the system layer, and thus by definition don't encounter shell level env conflicts.  And (b), launch methods which use a `hop` command (such as `SSH`) cleanly separate the environment on the executor side from the task environment on the target node.  

(a) will remain limited to certain systems, but we could switch mpirun and friends to use the hop-cmd mechanism.  That would essentially wrap the task into a shell script which is executed on the target node (that option was mentioned above, here it's done automatically for every task).  I am uncertain about the performance penalty.

BTW, a 3rd option comes to mind: the task is actually not interested in running the module load before task execution.  Instead, the task is interested to see the *environment effects* of the module load being active upon execution.  If we were able to capture that environment (for example, by comparing the env after module load to the original env we found on the batch node when starting), then we could pass the env via `-x / --environ` to mpirun (OpenMPI vs. Hydra), but the mpirun itself would run in an unaltered environment.

Not sure what option would be best.  Also, for the current tickets we should look for a fast workaround, as any of the approaches above (and likely any other fundamental fix) will take quite some time.

Sorry for the wall of text, probably should have dumped this elsewhere...

**Comment by SrinivasMushnoori** [comment] 2020-05-14 18:00
Hi everyone,
has there been movement on this? Two of my projects (RepEx science experiments and PACE: domain specific workflow) are stalling due to this...

**Comment by andre-merzky** [comment] 2020-05-15 08:30
@SrinivasMushnoori : please try the `features/bridges_mpirun` branch in RP again, and used the `bridges_mpiexec` (!) resource label.  Please use the following modules when installing any application or python modules:
```
  1) cuda/9.0              
  2) gromacs/2018_gpu       
  3) mpi/intel_openmpi/19.3 
  4) intel/19.3            
  5) slurm/default          
  6) anaconda3/2019.10
```
I actually think that this is not completely necessary, but for now please start with this set.  Let me know if the modules give you any conflict with your application requirements!

**Comment by SrinivasMushnoori** [comment] 2020-05-15 16:29
I will try this. The one thing that worries me here is: 

```gromacs/2018_gpu```

We're explicitly NOT using the GPU version, it's the CPU version.

**Comment by andre-merzky** [comment] 2020-05-15 17:28
Ok, then please replace that module and leave the others in place.  Thanks!

**Comment by SrinivasMushnoori** [comment] 2020-05-15 17:30
If not using GPU then why are we loading `  cuda/9.0  ` ?

**Comment by andre-merzky** [comment] 2020-05-15 19:10
That was auto-loaded as dependency for gromacs I think, so it won't be needed either...

**Comment by SrinivasMushnoori** [comment] 2020-05-18 17:26
Loading the modules exactly as prescribed gives the following error:
```/pylon5/mr560ip/mushnoor/radical.pilot.sandbox/re.session.McEwan.scm177.018400.0000/pilot.0000/rep.0000.0000.md//unit.000000.sh: line 38: mpi/intel_openmpi/19.3: No such file or dire\
ctory
```

Was there a typo?

**Comment by andre-merzky** [comment] 2020-05-19 10:24
Hi Srinivas - I can't get onto bridges right now, apologies.  Would you mind checking what mpi/intel_openmpi module is closest to that version, and use that one?  Yes, that's likely a typo :-(  Thanks!

**Comment by SrinivasMushnoori** [comment] 2020-05-19 17:42
Well there is a module named `mpi/intel_openmpi/19.3` when I do `module avail`
So looks like this isn't a typo...

**Comment by SrinivasMushnoori** [comment] 2020-05-20 03:51
Okay. Still fails with:
```Currently Loaded Modulefiles:
  1) slurm/default            4) mpi/intel_openmpi/19.3
  2) anaconda3/2019.10        5) gromacs/2018_cpu
  3) intel/19.3
mpiexec: Error: unknown option "-pmi_args"
Type 'mpiexec --help' for usage.
```

This is in the `STDERR` file.

In the `unit.000000.sh` file, the `pre exec` section looks like:

```
# Pre-exec commands                                                                                                                                                                    
prof cu_pre_start
module load mpi/intel_openmpi/19.3 ||  (echo "pre_exec failed"; false) || exit
module load intel/19.3 ||  (echo "pre_exec failed"; false) || exit
module load slurm/default ||  (echo "pre_exec failed"; false) || exit
module load anaconda3/2019.10 ||  (echo "pre_exec failed"; false) || exit
source /opt/packages/gromacs-CPU-2018/bin/GMXRC.bash ||  (echo "pre_exec failed"; false) || exit
module load gromacs/2018_cpu ||  (echo "pre_exec failed"; false) || exit
echo all-modules-loaded ||  (echo "pre_exec failed"; false) || exit
module list ||  (echo "pre_exec failed"; false) || exit
which mpirun ||  (echo "pre_exec failed"; false) || exit
which mpiexec ||  (echo "pre_exec failed"; false) || exit
mpirun --version ||  (echo "pre_exec failed"; false) || exit
/opt/packages/gromacs-CPU-2018/bin/gmx_mpi grompp -f mdin.mdp -c inpcrd.gro -o sys.tpr -p sys.top ||  (echo "pre_exec failed"; false) || exit
prof cu_pre_stop
```

Correspondingly, the `STDOUT` look like this:

```
all-modules-loaded
/usr/mpi/intel/openmpi-2.1.2-hfi/bin/mpirun
/usr/mpi/intel/openmpi-2.1.2-hfi/bin/mpiexec
mpirun (Open MPI) 2.1.2

Report bugs to http://www.open-mpi.org/community/help/
```

So modules load fine, but the error is triggered on the `grompp` line:

```
/opt/packages/gromacs-CPU-2018/bin/gmx_mpi grompp -f mdin.mdp -c inpcrd.gro -o sys.tpr -p sys.top ||  (echo "pre_exec failed"; false) || exit
```

**Comment by andre-merzky** [comment] 2020-05-20 05:13
Uh, that command line looks wrong - that should be something like `mpiexec -.... gmx_mpi ....`.  What is the resource label you use, and what is the radical-stack?  Thanks.

**Comment by SrinivasMushnoori** [comment] 2020-05-20 05:52
`radical-stack` is

```
(rct_py3.6) scm177@McEwan:~/RCT/repex.gmx$ radical-stack

  python               : 3.6.10
  pythonpath           : 
  virtualenv           : /home/scm177/Virtual_Envs/rct_py3.6

  radical.entk         : 1.0.1-v1.0.1-4-g6cb2f7e@user-repex
  radical.pilot        : 1.4.0-v1.4.0-8-gdcdd0e4@feature-bridges_mpirun
  radical.repex        : 0.72.0-0d0178b@user-repex
  radical.saga         : 1.2.0-v1.2.0@user-repex
  radical.utils        : 1.2.2-v1.2.2@user-repex
```

Resource label is `xsede.bridges_mpiexec`

The thing is, the command it fails on is still in pre exec. Unsure if you need mpiexec to run that command...I can actually even run that command in the login node.

**Comment by andre-merzky** [comment] 2020-05-20 06:00
Why is it in pre_exec?  It should be the task executable, right?  Otherwise it won't land on the compute node but runs on the agent node, and it won't be started with the right mpiexec command.

**Comment by SrinivasMushnoori** [comment] 2020-05-20 06:08
It's in pre_exec because it's not the actual md run. it is required _to begin_ the md run.
It's always been in pre_exec, in every single iteration of repex (or anything written in EnTK) that supports gromacs...

**Comment by SrinivasMushnoori** [comment] 2020-05-20 06:13
Elaborating a bit: that command runs the gromacs pre processor (hence the name "grompp"), a tool that is invoked by calling `gmx_mpi` but not actually running any MD. What `grompp` does is that is simply converts the necessary simulation files to a machine readable format that is then used to execute the MD run. Where the task lands is less important than the files it generates, which should simply be the unit sandbox.

**Comment by andre-merzky** [comment] 2020-05-20 07:09
If that task is not running MD, then I assume it does not need MPI - can you just use `gmx` instead of `gmx_mpi`?  If it does need MPI, it will need to be started via RP, and then needs to be in it's own task.

**Comment by andre-merzky** [comment] 2020-05-20 07:15
Srinivas, can you please add one more `pre_exec` command just before the gmx_mpi call (if just calling gmx is not an option): `ldd /opt/packages/gromacs-CPU-2018/bin/gmx_mpi`,  and send the output?  Thanks.

**Comment by SrinivasMushnoori** [comment] 2020-05-20 15:11
1) I think `gmx_mpi` is simply the name of the executable. I do not think there even _is_ a `gmx` but let me check. 
2) Let me add `ldd` and get back to you

**Comment by SrinivasMushnoori** [comment] 2020-05-20 15:45
Okay. Adding `ldd` gies the following:

`STDOUT` :

```
all-modules-loaded
/usr/mpi/intel/openmpi-2.1.2-hfi/bin/mpirun
/usr/mpi/intel/openmpi-2.1.2-hfi/bin/mpiexec
mpirun (Open MPI) 2.1.2

Report bugs to http://www.open-mpi.org/community/help/
/opt/packages/gromacs-CPU-2018/bin/gmx_mpi:
        linux-vdso.so.1 =>  (0x00007ffcd9821000)
        libmpifort.so.12 => /opt/intel/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib/libmpifort.so.12 (0x00007fd53af29000)
        libmpi.so.12 => /opt/intel/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib/release/libmpi.so.12 (0x00007fd539d9b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fd539b97000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fd53998f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd539773000)
        libfftw3f.so.3 => /lib64/libfftw3f.so.3 (0x00007fd5393fa000)
        libopenblas.so.0 => /lib64/libopenblas.so.0 (0x00007fd536f06000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd536bff000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fd5368fd000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fd5366d7000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd5364c1000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fd5360f4000)
        libfabric.so.1 => /opt/intel/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/lib/libfabric.so.1 (0x00007fd535ebc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd53b2e7000)
        libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007fd535b9a000)
        libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007fd53595e000)
grompp:
-f:
mdin.mdp:
        not a dynamic executable
-c:
inpcrd.gro:
        not a dynamic executable
-o:
sys.tpr:
-p:
sys.top:
        not a dynamic executable
pre_exec failed
```

`STDERR`

```
Currently Loaded Modulefiles:
  1) slurm/default            4) mpi/intel_openmpi/19.3
  2) anaconda3/2019.10        5) gromacs/2018_cpu
  3) intel/19.3
ldd: ./grompp: No such file or directory
ldd: ./-f: No such file or directory
ldd: warning: you do not have execution permission for `./mdin.mdp'
ldd: ./-c: No such file or directory
ldd: warning: you do not have execution permission for `./inpcrd.gro'
ldd: ./-o: No such file or directory
ldd: ./sys.tpr: No such file or directory
ldd: ./-p: No such file or directory
ldd: warning: you do not have execution permission for `./sys.top'
```

**Comment by SrinivasMushnoori** [comment] 2020-05-21 01:19
Update: I tried to move the `/opt/packages/gromacs-CPU-2018/bin/gmx_mpi grompp -f mdin.mdp -c inpcrd.gro -o sys.tpr -p sys.top ` line before the mpi module is loaded. In principle, this should work: since the grompp command can absolutely be executed on the login node on a single core. I still get the `mpiexec: Error: unknown option "-pmi_args"` error.

**Comment by andre-merzky** [comment] 2020-05-21 12:44
Can you please paste the pre_exec which resulted in the above output?  Thanks!

**Comment by SrinivasMushnoori** [comment] 2020-05-21 16:19
Essentially the same thing Andre.
```
module load intel/19.3 
source /opt/packages/gromacs-CPU-2018/bin/GMXRC.bash
/opt/packages/gromacs-CPU-2018/bin/gmx_mpi grompp -f mdin.mdp -c inpcrd.gro -o sys.tpr -p sys.top
module load mpi/intel_openmpi/19.3 
module load slurm/default 
module load anaconda3/2019.10 
module load gromacs/2018_cpu 
echo all-modules-loaded 
module list 
which mpirun 
which mpiexec 
mpirun --version 
```

Just moved the `source` and `grompp` commands BEFORE loading the openmpi module.
To reiterate, `ldd` before `gmx_mpi` gives:
```/opt/packages/gromacs-CPU-2018/bin/gmx_mpi:
        linux-vdso.so.1 =>  (0x00007ffcd9821000)
        libmpifort.so.12 => /opt/intel/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib/libmpifort.so.12 (0x00007fd53af29000)
        libmpi.so.12 => /opt/intel/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib/release/libmpi.so.12 (0x00007fd539d9b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fd539b97000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fd53998f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd539773000)
        libfftw3f.so.3 => /lib64/libfftw3f.so.3 (0x00007fd5393fa000)
        libopenblas.so.0 => /lib64/libopenblas.so.0 (0x00007fd536f06000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd536bff000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fd5368fd000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fd5366d7000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd5364c1000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fd5360f4000)
        libfabric.so.1 => /opt/intel/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/lib/libfabric.so.1 (0x00007fd535ebc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd53b2e7000)
        libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007fd535b9a000)
        libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007fd53595e000)
```

**Comment by andre-merzky** [comment] 2020-05-21 16:28
This pre_exec produced this error?
```
grompp:
-f:
mdin.mdp:
        not a dynamic executable
-c:
inpcrd.gro:
        not a dynamic executable
-o:
sys.tpr:
-p:
sys.top:
        not a dynamic executable
pre_exec failed
```
I don't understand how that can happened :-(  The only thing that looks strange is that ytou sourcre the GMXRC before loading the module.  Is that on purpose?  Do you need to source that file when using modules?

**Comment by SrinivasMushnoori** [comment] 2020-05-21 16:40
Okay so that happened because I accidentally typed the following:
```ldd /opt/packages/gromacs-CPU-2018/bin/gmx_mpi grompp -f mdin.mdp -c inpcrd.gro -o sys.tpr -p sys.top```

Instead of:

```ldd /opt/packages/gromacs-CPU-2018/bin/gmx_mpi```

It treats ALL the characters in the string separated by spaces as separate executables, that's all.
I have removed that and reproduced it. This is what I get:

```
        linux-vdso.so.1 =>  (0x00007ffcd9821000)
        libmpifort.so.12 => /opt/intel/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib/libmpifort.so.12 (0x00007fd53af29000)
        libmpi.so.12 => /opt/intel/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib/release/libmpi.so.12 (0x00007fd539d9b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fd539b97000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fd53998f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd539773000)
        libfftw3f.so.3 => /lib64/libfftw3f.so.3 (0x00007fd5393fa000)
        libopenblas.so.0 => /lib64/libopenblas.so.0 (0x00007fd536f06000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd536bff000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fd5368fd000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fd5366d7000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd5364c1000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fd5360f4000)
        libfabric.so.1 => /opt/intel/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/lib/libfabric.so.1 (0x00007fd535ebc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd53b2e7000)
        libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007fd535b9a000)
        libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007fd53595e000)
```

**Comment by SrinivasMushnoori** [comment] 2020-05-21 16:43
Let me elaborate: 
I tried sourcing and grompping before loading the mpi module because grompping is a single core operation. My hypothesis was that trying to source and grompp before loading the `openmpi` module would resolve what looked to my eyes/brain like a conflict in `intel` libraries. 

...and I was wrong. I got the same error.

**Comment by SrinivasMushnoori** [comment] 2020-05-21 16:53
Here's another shot in the dark: It still look like a conflict to me, and clearly in the resource config file down at the RP level, there is clearly some flavour of MPI being loaded. Perhaps removing that line and then loading the module in the `pre_exec` at the RepEx level could potentially fix this?

**Comment by andre-merzky** [comment] 2020-05-21 19:40
Ok, lets  give it another try (I hope to get back on Bridges over the weekend, FWIW - sorry for the cumbersome back-and-forth...).  Please try this set of pre_execs:

```
module reset
module load intel/19.3 
module load mpi/intel_openmpi/19.3 
module load slurm/default 
module load gromacs/2018_cpu 
module list 
which mpirun 
which mpiexec 
mpirun --version 
/opt/packages/gromacs-CPU-2018/bin/gmx_mpi grompp -f mdin.mdp -c inpcrd.gro -o sys.tpr -p sys.top
```

I don't think you need the anaconda module rerally, since you don't activate a conda env, right?
Thanks for your patience...

**Comment by SrinivasMushnoori** [comment] 2020-05-21 21:15
Understood. It's on the queue. Will update ASAP. Queue times are awful.
Thank you very much! I understand these are generally stressful times, so not to worry.

**Comment by SrinivasMushnoori** [comment] 2020-05-23 00:43
Same issue: `mpiexec: Error: unknown option "-pmi_args"`

**Comment by andre-merzky** [comment] 2020-05-25 09:34
thanks @SrinivasMushnoori .  Can you please try once more without sourcing the GMXRC (would you mind attaching that file)?  Also, what was the output for `module list` in the case above (that should be part of the pre_exec output)?

**Comment by SrinivasMushnoori** [comment] 2020-05-25 16:05
I ran the new run as requested by commenting out the `source` command.

The output of `module list` seems to be spit out into `STDERR`, which looks identical even with the new run with the `source` command commented out:
```
Currently Loaded Modulefiles:
  1) intel/19.3               3) slurm/default
  2) mpi/intel_openmpi/19.3   4) gromacs/2018_cpu
mpiexec: Error: unknown option "-pmi_args"
Type 'mpiexec --help' for usage.
```

The `STDOUT` look like this:

```
modules-purged
all-modules-loaded
/usr/mpi/intel/openmpi-2.1.2-hfi/bin/mpirun
/usr/mpi/intel/openmpi-2.1.2-hfi/bin/mpiexec
mpirun (Open MPI) 2.1.2

Report bugs to http://www.open-mpi.org/community/help/
```

The relevant portion of the `unit.000000.sh` script:

```
module purge ||  (echo "pre_exec failed"; false) || exit
echo modules-purged ||  (echo "pre_exec failed"; false) || exit
module load intel/19.3 ||  (echo "pre_exec failed"; false) || exit
module load mpi/intel_openmpi/19.3 ||  (echo "pre_exec failed"; false) || exit
module load slurm/default ||  (echo "pre_exec failed"; false) || exit
module load gromacs/2018_cpu ||  (echo "pre_exec failed"; false) || exit
echo all-modules-loaded ||  (echo "pre_exec failed"; false) || exit
module list ||  (echo "pre_exec failed"; false) || exit
which mpirun ||  (echo "pre_exec failed"; false) || exit
which mpiexec ||  (echo "pre_exec failed"; false) || exit
mpirun --version ||  (echo "pre_exec failed"; false) || exit
/opt/packages/gromacs-CPU-2018/bin/gmx_mpi grompp -f mdin.mdp -c inpcrd.gro -o sys.tpr -p sys.top ||  (echo "pre_exec failed"; false) || exit
```

Attaching the `GMXRC.bash` file shortly.

**Comment by SrinivasMushnoori** [comment] 2020-05-27 19:18
Gentle ping. Has there been movement on this?

**Comment by shantenujha** [comment] 2020-06-05 16:02
escalating to not so gentle ping :)

**Comment by SrinivasMushnoori** [comment] 2020-06-11 02:55
Ping: are we still waiting for @andre-merzky Andre to get back his XSEDE credentials?
Really sorry to push this hard for this, but this is making two of my projects stall.

Thanks, and terribly sorry.

**Comment by shantenujha** [comment] 2020-06-16 12:58
I see @AymenFJA  is assigned to this ticket. @andre-merzky @mturilli is that correct ?

**Comment by andre-merzky** [comment] 2020-06-17 08:04
@shantenujha : @AymenFJA  initially looked into the problems with our Hydra detection code.  Kt turned out that this code is actually not at fault, but rather the mpi version compiled into gmx_mpi, and it's back on my table now.

**Closed** 2020-11-02 18:15 UTC
Labels: layer:rp, priority:critical, topic:configuration, type:bug
