### ISSUE TITLE
RP on archer fails as project e290 is unavailable

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1288] opened 2017-03-23 21:55 UTC
From Charlie:

Hope one of you two can help me with this: I am trying to run ensemblemd jobs on Archer, but they are failing because (I think) they are trying to use a pre-installed virtual environment that is in a now-closed down account (e290) – it seems to be hard-wired into a configuration file somewhere.
a)  Can you explain to me how I can override this setting in my job script/ resource configuration file?
b)  Can something be done to remove this hard-wired ve as it’s not going to work anymore, anyway.

**Comment by vivek-bala** [comment] 2017-03-23 22:02
> a) Can you explain to me how I can override this setting in my job script/ resource configuration file?

The hardwiring comes from line https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_epsrc.json#L27.
I don't exactly remember why the shared VE approach was chosen for Archer. @marksantcroos, @andre-merzky ? I think the RP installation on archer would need to be rebuilt.

> b) Can something be done to remove this hard-wired ve as it’s not going to work anymore, anyway.

I think this should be possible either by moving from the shared VE approach or keeping/maintaining the shared VE in a world-readable location. I'll check if the latter exists.

**Comment by andre-merzky** [comment] 2017-03-23 23:54
Hey Charlie, Vivek, 

archer makes it difficult to install python modules on the compute nodes, IIRC - thus the use of a pre-populated virtualenv.  I think easiest is to create a new VE.  IIRC, there is no globally shared file system available on archer, so we'll need to use some project space again I guess :/

**Comment by ibethune** [comment] 2017-03-24 08:51
Actually, we already have a ticket open #1222 for me to do this.  I propose that I install a new shared VE in the y07 (software packages) space, since this will always exist.  Then this ticket can be used to track updating the config to point to the new VE.

**Comment by andre-merzky** [comment] 2017-03-24 09:04
Ah, right - thanks for taking this on!

**Comment by ibethune** [comment] 2017-03-24 12:23
Question for @CharlieLaughton - I am able to run simple examples on ARCHER (not ensemble toolkit, just RP directly), and the shared VE is still accessible for the next few weeks anyway, so I don't believe this is the problem.  I am installing a new one at the moment, but it would be good to see what the error message you are actually getting is.  Can you also confirm what versions of the RADICAL stack (ensemblemd, pilot, utils, saga-python) you are using?

**Comment by CharlieLaughton** [comment] 2017-03-24 14:42
For me things fail at bootstrap_1. The contents of bootstrap_1.err is as follows:

```
charlie@eslogin006:~/work/radical.pilot.sandbox/rp.session.fletcher.pharm.nottingham.ac.uk.charlie.017248.0006-pilot.0000> more bootstrap_1.err
ModuleCmd_Switch.c(172):ERROR:152: Module 'PrgEnv-cray' is currently not loaded
ModuleCmd_Switch.c(172):ERROR:152: Module 'PrgEnv-cray' is currently not loaded
ModuleCmd_Switch.c(172):ERROR:152: Module 'PrgEnv-cray' is currently not loaded
--------------------------------------------------------------------------------
This is a private computing facility. Access to this service is limited to those
who have been granted access by the operating service provider on behalf of the
contracting authority and use is restricted to the purposes for which access was
granted. All access and usage are governed by the terms and conditions of access
agreed to by all registered users and are thus subject to the provisions of the
Computer Misuse Act, 1990 under which unauthorised use is a criminal offence.

If you are not authorised to use this service you must disconnect immediately.
--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/work/e290/shared/shared_pilot_ve_20150924/bin/pip", line 8, in <module>
    load_entry_point('pip==1.3', 'console_scripts', 'pip')()
  File "/work/e290/shared/shared_pilot_ve_20150924/lib/python2.7/site-packages/pip-1
.3-py2.7.egg/pip/__init__.py", line 149, in main
    return command.main(args[1:], options)
  File "/work/e290/shared/shared_pilot_ve_20150924/lib/python2.7/site-packages/pip-1
.3-py2.7.egg/pip/basecommand.py", line 183, in main
    log_fp.close()
IOError: [Errno 122] Disk quota exceeded
Python 2.7.6
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pilot
charlie@eslogin006:~/work/radical.pilot.sandbox/rp.session.fletcher.pharm.nottingham.ac.uk.charlie.017248.0006-pilot.0000> 
```
I am assuming it is the 'Disk quota exceeded'  message that is the problem. I have no problem with disk quotas on the account on Archer I am using to run the job (e280-Laughton), so I thought it might be because e290 is on the way out, but I guess not.

**Comment by CharlieLaughton** [comment] 2017-03-24 14:45
Here's my output from radical-stack:

python            : 2.7.13
virtualenv        : /users/charlie/ve
radical.utils     : 0.45
saga-python       : 0.45.1
radical.pilot     : 0.45.1

**Comment by ibethune** [comment] 2017-03-24 15:01
I think you might be on the right track with the disk quota problem (although I don't then understand why it was working for me, and not you).  You can try the new shared VE I just installed and see if that fixes things:

Edit the file ```/users/charlie/velib/python2.7/site-packages/radical/pilot/configs/resource_epsrc.json``` and replace both instances of ```/work/e290/shared/shared_pilot_ve_20150924/``` with ```/work/y07/y07/cse/radical.pilot/shared_pilot_ve_20170324/```

**Comment by CharlieLaughton** [comment] 2017-03-25 03:24
I think I have got it fixed.  To begin with I just got the same error message, then it turned out that although I am under quota on the Archer /work filesystem, I was over- (or at-) quota on the /home filesystem. Considering everything RP does looks like it ought to happen on /work this seems odd, but the fact is that once I cleared some space on /home things moved forward.

I did however still run into a different problem (bootstrap_1.sh failing when it could not seem to find or install the correct version of pymongo), but once I nuked all definitions of PYTHONPATH in my .bashrc file - it all works!

It it possible to add an 'unset PYTHONPATH command somewhere at the very start of the bootstrapping process, so this gets sorted out automatically? This is not the first time I have run into odd errors with Radical Pilot due to having PYTHONPATH set - and I need it for other work I do on Archer so the current fix (unsetting it in .bashrc) is far from ideal.

**Comment by andre-merzky** [comment] 2017-03-25 13:42
PYTHONPATH: it is difficult for us to distinguish between good and bad settings: simply unsetting PYTHONPATH may or may not be the right thing to do for a specific system.  Additionally, we are starting subshells in many places in the pilot, and those will also evaluate your startup scripts, which are likely to lead to similar problems (we try to stick to /bin/sh in most places though, but still, the point remains).

What I would suggest is to not set PYTHONPATH in your bashrc, but instead to use a virtualenv to install your modules, or to set the PYTHONPATH in a separate script which you would then source before using the respective application.  Would that work in your case?

Charlie, I am not sure, but seem to remember that we discussed this before - apologies if I am iterating old stuff... :/

**Comment by CharlieLaughton** [comment] 2017-03-25 15:20
I spoke too soon - it appeared to run through to completion but there were errors. As far as I can see the parts of the CoCo-MD workflow that used Gromacs were fine, but when the script got to the first step where it had to run pyCoCo, it couldn't find it (presumably because I had previously unset PYTHONPATH). I have struggled all morning to find a way round this but I am currently defeated: if I leaver PYTHONPATH in place it fails to bootstrap (because it thinks it has to install the right version of pymongo, and pip seems to fail (no internet access?). If I use PYTHONPATH I only have access to python libraries that are within the radical.pilot virtualenv (it seems) and that does not include pyCoCo. I tried adding a "pre exec" command to the coco.py kernel definition that would load a custom virtualenv just for this step, but that doesn't work because if PYTHONPATH has been unset then I can't install extasy.coco in this virtual environment because it has a dependency on scipy, and I can't install a local version of scipy because it has dependencies to the system lapack and blas libraries and I don't know how to cope with that...

Over to you!

**Comment by andre-merzky** [comment] 2017-03-25 15:54
`ComputeUnitDescriptions` allow to specify `pre_exec` commands, and any env variables can safely set there.  @vivek-bala: does EnTK provide the option to pass the `PYTHONPATH` with this mechanism?

**Comment by andre-merzky** [comment] 2017-03-25 15:59
Sorry, I read only part of your message it seems - you are aware of `pre_exec`...

I am not sure I understand your comment about the separate VE, but that is what we actually do frequently.  I assume you do something like the following:

in your login shell:
```sh
$ virtualenv $HOME/ve_coco
$ source $HOME/ve_coco/bin/activate
$ export PYTHONPATH=/o/brother/where/are/thou
$ pip install pycoco
```

in your pre_exec:
```sh
$ source $HOME/ve_coco/bin/activate
$ export PYTHONPATH=/o/brother/where/are/thou
$ pycoco --do-magic
```

?

**Comment by CharlieLaughton** [comment] 2017-03-25 20:18
Hi Andre

Yes, that's just what I tried to do. The problem is that - on Archer - I can't find a way to make a ve that includes pyCoCo without (as far as I can work out) also giving that ve access to system-installed libraries. 

 Maybe Iain can give me a recipe to cope with this.

**Comment by CharlieLaughton** [comment] 2017-03-25 22:57
I think maybe this ought to be a new ticket - I don't think its to do with e290 any more...

**Comment by CharlieLaughton** [comment] 2017-03-26 00:25
Me again, I seem to managed to sort it out. As far as I can see it goes a bit like this:

1. The original error, relating to disk quotas, still seems odd, but it's easy to fix.
2. With that fixed, the next problem was that bootstrap_1.sh failed because it was trying to pip install the "correct" version of pymongo and couldn't.
3, But the right version, 2.8, is in Iain's newly created virtualenv, so what;'s the problem? There must be another version somewhere that is taking precedence over it (found earlier in the oder pip searches for packages).
4. That's why things got better when I nuked my PYTHONPATH - the "rogue" pymongo went away. But in the end that just caused more problems than it solved.
5. How can a 'rogue' pymongo take precedence over one in a virtualenv? If the rogue has been installed as an egg, and the one in the virtualenv is not, as eggs always take precedence over non-eggs, whatever the order of paths in $PYTHONPATH - see http://stackoverflow.com/questions/5984523/eggs-in-path-before-pythonpath-environment-variable
6. Sure enough, when you load Archer's python-compute module, you get pymongo 2.7.2 - as an egg. If you install your own version in the standard way with pip, you get a flat file, and it gets ignored, even if it's a newer version - if you look in Ian's new virtualenv, you will see that is what has happened.
7. So I ran 'pip install --upgrade --user pymongo==2.8 --egg', and then 'pip list' reports the active version is indeed now 2.8.
8. I return to my Nottingham workstation and run the CoCo-MD job again, and hallelujah it works.
9. I suggest Iain that you re-install pymongo as an egg in the virtualenv, then this should fix it for anyone - fingers crossed.

**Comment by ibethune** [comment] 2017-03-27 08:33
My lack of python / pip knowledge is showing here.  Is there any disadvantage to installing the deps in the static env as eggs, @andre-merzky ?  If not then we should probably do so in the create-static-ve script.

**Comment by andre-merzky** [comment] 2017-03-27 11:32
Another gem of Python deployment learnt! :D  : I was not aware about egg-precedence.  

I would like to look into the implications, specifically with respect to python versions and distributions, and to portability, of switching from plain modules to eggs before commenting.

**Comment by andre-merzky** [comment] 2017-04-17 10:48
The is merged by now and seems to work ok - closing.

**Comment by andre-merzky** [comment] 2017-04-17 10:49
Sorry, this was the wrong ticket...

**Comment by ibethune** [comment] 2017-04-27 08:10
The initial issue (that Charlie can't run on ARCHER) is resolved.  Modifying the shared VE to deploy as eggs rather is a bit of a bigger change that we might consider in the next release, but not in this release cycle.

**Comment by andre-merzky** [comment] 2017-08-24 10:56
closing per last comment.

**Closed by andre-merzky** 2017-08-24 10:56 UTC
Labels: bug, resource
