### ISSUE TITLE
Need jsrun flag to be parsed into command before executable

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1830] opened 2019-03-13 21:21 UTC
This ticket relates to both INSPIRE and Arvind use-cases:

The `OpenMM` executables will not be able to run using `CUDA` without an additional flag in `jsrun`. `OpenMM` needs `--smpiargs="none"` to be passed to the `jsrun` command. Without it, the following error is produced:

```
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
```

I verified with this test: 

```
(openmm) bash-4.2$ jsrun --smpiargs="none" -n 1 -a 1 -c 1 -g 1 python -m simtk.testInstallation

OpenMM Version: 7.3
Git Revision: 7ada5dd064f45a8b1a38ae79742e4c11fce0a0a6

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 1.94168e-06
Reference vs. CUDA: 6.72257e-06
CPU vs. CUDA: 6.2195e-06

All differences are within tolerance.

```
```
(openmm) bash-4.2$ jsrun -n 1 -a 1 -c 1 -g 1 python -m simtk.testInstallation
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region

OpenMM Version: 7.3
Git Revision: 7ada5dd064f45a8b1a38ae79742e4c11fce0a0a6

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces


```

**Comment by andre-merzky** [comment] 2019-03-13 22:42
Interesting.  The value of `none` is unexpected though: the arguments to `smpiargs` are passed to the MPI implementation *as arguments*, so what this basically results in is something like `mpirun -n 1 none -host node_1 /bin/date`, i.e., a stray `none` is now in the argument list.  I am surprised this fixes something...  But either way, I understand that we need to address this.  Could you please check if `--smpiargs="--gpu"` would also result in a correct execution?  That is an arg I would not mind passing in all cases, which would make a special handling for certain tasks unnecessary.

**Comment by andre-merzky** [comment] 2019-03-13 22:43
PS.: where did you find the setting `none` documented or used?

**Comment by jdakka** [comment] 2019-03-13 22:44
[Here](https://github.com/kokkos/kokkos/issues/1985#issuecomment-463491300) it appears to be an IBM issue

**Comment by jdakka** [comment] 2019-03-13 22:49
`--gpu` doesn't work 
```
(openmm) bash-4.2$ jsrun --smpiargs="--gpu" -n 1 -a 1 -c 1 -g 1 python -m simtk.testInstallation
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region

OpenMM Version: 7.3
Git Revision: 7ada5dd064f45a8b1a38ae79742e4c11fce0a0a6

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
```

**Comment by andre-merzky** [comment] 2019-03-13 23:10
The page you reference seems to advise `--smpiargs="off"` instead of `none` - which is indeed a documented value which disables all MPI-related env settings.  But you seem to have success with `none`, which still puzzles me.  Can you please do one more test and try `off` instead?  If that still doesn't work, I'll implement `none`.  

Your application is not an MPI  application, correct?

**Comment by jdakka** [comment] 2019-03-14 03:18
`"off"` fixes the problem as well. I saw `"none"` used in another thread and didn't know it would make it a difference. Thanks for clearing that up. 

```
(openmm) bash-4.2$ jsrun --smpiargs="off" -n 1 -a 1 -c 1 -g 1 python -m simtk.testInstallation

OpenMM Version: 7.3
Git Revision: 7ada5dd064f45a8b1a38ae79742e4c11fce0a0a6

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 1.94422e-06
Reference vs. CUDA: 6.7295e-06
CPU vs. CUDA: 6.22805e-06

All differences are within tolerance.
```

**Comment by andre-merzky** [comment] 2019-03-14 05:44
Thanks, then we will pass `off` for non-MPI tasks.

**Comment by andre-merzky** [comment] 2019-03-14 09:40
Jumana, can you please test the branch `fix/issue_1830`?   You will need to set
```
cud['gpu_process_type'] = rp.POSIX
cud['gpu_thread_type']  = rp.CUDA
```
to trigger the `spmiargs` parameter.

**Comment by iparask** [comment] 2019-03-14 15:42
May I suggest something? 

Jumana's test does not use `erf` files as the resource setup. @andre-merzky wouldn't it make sense to see how the erf_file looks like for such a case and then implement it in the launch method?

@jdakka can you run what ever works and add `--erf_output=working.erf` and paste the contents of that file?

**Comment by jdakka** [comment] 2019-03-14 18:19
@iparask 

```
app 0: python -m simtk.testInstallation
cpu_index_using: logical
overlapping_rs: warn
skip_missing_cpu: warn
skip_missing_gpu: allow
skip_missing_mem: allow
oversubscribe_cpu: warn
oversubscribe_gpu: allow
oversubscribe_mem: allow
launch_distribution: packed
rank: 0: { host: 1; cpu: {0-3} ; gpu: {0} ; mem: {0-999} } : app 0
```

**Comment by andre-merzky** [comment] 2019-03-14 19:25
I don't think that the problem is on the jsrun level (this time), but rather on the CUDA initialization which seems to take different code paths in the MPI vs. non-MPI case.  The flag controls what information is passed to the MPI layer.

**Comment by iparask** [comment] 2019-03-14 20:36
Apparently, it is not. I was wondering since it is passed as a `jsrun` argument is it would appear in the resource file.

**Comment by andre-merzky** [comment] 2019-03-14 20:56
Ah, I see - makes sense.  Thanks for checking.

**Comment by jdakka** [comment] 2019-03-15 21:18
This has been resolved.

**Comment by mturilli** [comment] 2019-03-19 20:08
@andre-merzky to open a PR for this.

**Comment by mturilli** [comment] 2019-03-26 21:16
Merged into summit_am

**Closed by mturilli** 2019-03-26 21:16 UTC
Labels: comp:agent:executor, priority:high, topic:resource:summit, type:enhancement
