### ISSUE TITLE
RAPTOR: worker registration timed out 

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#3241] opened 2024-10-21 16:43 UTC
This issue is happening on RIVANNA with the latest `radical-stack`:
```sh
  python               : /sfs/gpfs/tardis/home/vaf8uz/ve/rct_latest/bin/python3
  pythonpath           : 
  version              : 3.11.6
  virtualenv           : /sfs/gpfs/tardis/home/vaf8uz/ve/rct_latest
  radical.gtod         : 1.81.0
  radical.pilot        : 1.83.0
  radical.utils        : 1.83.0
```

We are requesting 1 node with 1 GPU. Session logs are attached to @arupcsedu comment below.

**Comment by arupcsedu** [comment] 2024-10-21 16:44
RuntimeError: registration with master timed out
RuntimeError: registration with master timed out
Traceback (most recent call last):
  File "/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/bin/radical-pilot-raptor-worker", line 52, in <module>
Traceback (most recent call last):
  File "/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/bin/radical-pilot-raptor-worker", line 52, in <module>
    run(sys.argv[1], sys.argv[2], sys.argv[3])
    run(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/bin/radical-pilot-raptor-worker", line 30, in run
  File "/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/bin/radical-pilot-raptor-worker", line 30, in run
    worker = cls(raptor_id)
    worker = cls(raptor_id)
             ^^^^^^^^^^^^^^
  File "/sfs/gpfs/tardis/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/lib/python3.11/site-packages/radical/pilot/raptor/worker_default.py", line 42, in __init__
             ^^^^^^^^^^^^^^
  File "/sfs/gpfs/tardis/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/lib/python3.11/site-packages/radical/pilot/raptor/worker_default.py", line 42, in __init__
    super().__init__(manager=manager, rank=rank, raptor_id=raptor_id)
  File "/sfs/gpfs/tardis/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/lib/python3.11/site-packages/radical/pilot/raptor/worker.py", line 134, in __init__
    super().__init__(manager=manager, rank=rank, raptor_id=raptor_id)
  File "/sfs/gpfs/tardis/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/lib/python3.11/site-packages/radical/pilot/raptor/worker.py", line 134, in __init__
Traceback (most recent call last):
  File "/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/bin/radical-pilot-raptor-worker", line 52, in <module>
    run(sys.argv[1], sys.argv[2], sys.argv[3])
    raise RuntimeError('registration with master timed out')
RuntimeError: registration with master timed out
    raise RuntimeError('registration with master timed out')
RuntimeError: registration with master timed out
  File "/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/bin/radical-pilot-raptor-worker", line 30, in run
    worker = cls(raptor_id)
             ^^^^^^^^^^^^^^
  File "/sfs/gpfs/tardis/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/lib/python3.11/site-packages/radical/pilot/raptor/worker_default.py", line 42, in __init__
    super().__init__(manager=manager, rank=rank, raptor_id=raptor_id)
  File "/sfs/gpfs/tardis/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/lib/python3.11/site-packages/radical/pilot/raptor/worker.py", line 134, in __init__
    raise RuntimeError('registration with master timed out')
RuntimeError: registration with master timed out
Traceback (most recent call last):
  File "/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/bin/radical-pilot-raptor-worker", line 52, in <module>
Traceback (most recent call last):
  File "/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/bin/radical-pilot-raptor-worker", line 52, in <module>
    run(sys.argv[1], sys.argv[2], sys.argv[3])
    run(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/bin/radical-pilot-raptor-worker", line 30, in run
  File "/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/bin/radical-pilot-raptor-worker", line 30, in run
    worker = cls(raptor_id)
             ^^^^^^^^^^^^^^
    worker = cls(raptor_id)
  File "/sfs/gpfs/tardis/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/lib/python3.11/site-packages/radical/pilot/raptor/worker_default.py", line 42, in __init__
             ^^^^^^^^^^^^^^
  File "/sfs/gpfs/tardis/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/lib/python3.11/site-packages/radical/pilot/raptor/worker_default.py", line 42, in __init__
    super().__init__(manager=manager, rank=rank, raptor_id=raptor_id)
    super().__init__(manager=manager, rank=rank, raptor_id=raptor_id)
  File "/sfs/gpfs/tardis/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/lib/python3.11/site-packages/radical/pilot/raptor/worker.py", line 134, in __init__
  File "/sfs/gpfs/tardis/project/bii_dsc_community/djy8hg/arupcsedu/cylonplus/cy-rp-env/lib/python3.11/site-packages/radical/pilot/raptor/worker.py", line 134, in __init__
    raise RuntimeError('registration with master timed out')
    raise RuntimeError('registration with master timed out')
RuntimeError: registration with master timed out
RuntimeError: registration with master timed out

**Comment by andre-merzky** [comment] 2024-10-21 21:42
Thank's for opening the ticket.  Could you also point me to the code you are running, please?

**Comment by AymenFJA** [comment] 2024-10-21 23:04
@andre-merzky the code is below: 
```python
#!/usr/bin/env python3

import radical.pilot as rp

# Task state callback to print task status updates
def task_state_cb(task, state):
    print('  task %-30s: %s' % (task.uid, task.state))

# Define the NBEATS model training task
@rp.pythontask
def train_nbeats():
    import time
    from neuralforecast import NeuralForecast
    from neuralforecast.models import NBEATS
    from neuralforecast.utils import AirPassengersDF
    try:
        nf = NeuralForecast(
            models=[NBEATS(input_size=24, h=12, max_steps=100)],
            freq='M'
        )
        start_time = time.time()
        nf.fit(df=AirPassengersDF)
        nf.predict()
        end_time = time.time()

        task_time = end_time - start_time
        print(f"NBEATS model training completed in {task_time:.2f} seconds")
        return str(task_time)
    except Exception as e:
        print(f"Error during NBEATS model training: {str(e)}")
        return str(e)


# Define the DEEPAR model training task
@rp.pythontask
def train_deepar():
    import time
    from neuralforecast import NeuralForecast
    from neuralforecast.models import DEEPAR
    from neuralforecast.utils import AirPassengersDF
    try:
        nf = NeuralForecast(
            models=[DEEPAR(input_size=24, h=12, max_steps=100)],
            freq='M'
        )
        start_time = time.time()
        nf.fit(df=AirPassengersDF)
        nf.predict()
        end_time = time.time()

        task_time = end_time - start_time
        print(f"DEEPAR model training completed in {task_time:.2f} seconds")
        return str(task_time)
    except Exception as e:
        print(f"Error during DEEPAR model training: {str(e)}")
        return str(e)


# Define the THETA model training task
@rp.pythontask
def train_theta():
    import time
    from neuralforecast import NeuralForecast
    from neuralforecast.models import THETA
    from neuralforecast.utils import AirPassengersDF
    try:
        nf = NeuralForecast(
            models=[THETA(h=12)],
            freq='M'
        )
        start_time = time.time()
        nf.fit(df=AirPassengersDF)
        nf.predict()
        end_time = time.time()

        task_time = end_time - start_time
        print(f"THETA model training completed in {task_time:.2f} seconds")
        return str(task_time)
    except Exception as e:
        print(f"Error during THETA model training: {str(e)}")
        return str(e)


# Define the Transformer model training task
@rp.pythontask
def train_transformer():
    import time
    from neuralforecast import NeuralForecast
    from neuralforecast.models import Transformer
    from neuralforecast.utils import AirPassengersDF
    try:
        nf = NeuralForecast(
            models=[Transformer(input_size=24, h=12, max_steps=100)],
            freq='M'
        )
        start_time = time.time()
        nf.fit(df=AirPassengersDF)
        nf.predict()
        end_time = time.time()

        task_time = end_time - start_time
        print(f"Transformer model training completed in {task_time:.2f} seconds")
        return str(task_time)
    except Exception as e:
        print(f"Error during Transformer model training: {str(e)}")
        return str(e)


if __name__ == '__main__':

    session = rp.Session()
    try:
        # Pilot description
        pd = rp.PilotDescription()
        pd.access_schema = 'interactive' # <=======
        pd.resource = 'uva.rivanna' # <============ do not use local.locahost on HPC
        pd.runtime = 60  # pilot runtime (minutes)
        pd.cores = 30  # number of cores

        # Initialize PilotManager and TaskManager
        pmgr = rp.PilotManager(session=session)
        tmgr = rp.TaskManager(session=session)
        tmgr.register_callback(task_state_cb)

        # Submit the pilot
        pilot = pmgr.submit_pilots([pd])[0]
        tmgr.add_pilots(pilot)

        # Set up RAPTOR master and workers
        raptor = pilot.submit_raptors(rp.TaskDescription({'mode': rp.RAPTOR_MASTER, 'cpu_processes': 1}))[0] 
        workers = raptor.submit_workers(rp.TaskDescription({'mode': rp.RAPTOR_WORKER, 'cpu_processes': 27})) # add cpu_processes to worker

        # Define tasks for all four models
        tasks = []
        models = [train_nbeats, train_deepar, train_theta, train_transformer]
        for model_task in models:
            # Create multiple instances if needed
            for i in range(2):  # Adjust the range as needed for more tasks
                td = rp.TaskDescription({
                    'mode': rp.TASK_FUNCTION,
                    'function': model_task,  # Pass the function without calling it
                })
                tasks.append(td)

        # Submit tasks to RAPTOR
        submitted_tasks = raptor.submit_tasks(tasks)

        # Wait for tasks to complete
        tmgr.wait_tasks([task.uid for task in submitted_tasks])

        # Print task output (model training times)
        for task in submitted_tasks:
            print('%s [%s]: Task completed in %s seconds' % (task.uid, task.state, task.return_value))

        # Stop the RAPTOR master and wait for it to complete
        raptor.rpc('stop')
        tmgr.wait_tasks(raptor.uid)
        print('%s [%s]: %s' % (raptor.uid, raptor.state, raptor.stdout))

    finally:
        # Clean up the session
        session.close(download=False)
```

**Comment by andre-merzky** [comment] 2024-10-21 23:57
Hmm, that code seems to work for me (or at least Raptor comes up), with that same stack.  Aymen, any indication that MPI is acting up or something?

**Comment by AymenFJA** [comment] 2024-11-14 23:42
Hey @andre-merzky, any updates on this?

**Comment by andre-merzky** [comment] 2024-11-25 10:57
So, good news and bad news.  The bad first: I have no clue what's up with your run.  Good news: it works for me out of the box (tm) :-) Well, that is good news because I am confident that we'll get this to work for your case also.

What exactly did I try:
  - `module load gcc`
  - `module load openmpi`
  - `module load python`                     
  - `python3 -m venv ve3`
  - `git clone git@github.com:radical-cybertools/radical.pilot.git; cd radical.pilot; pip install .`
  - `git clone git@github.com:radical-cybertools/radical.utils.git; cd radical.pilot; pip install .`
  - `pip install mpi4py`
  - execute the attached script
  
The only change I made is to add `"cores_per_node": 40` to the rivanna resource config so that we can specify number of nodes in the pilot description.  I'll create a pull request for that change.

[raptor_simple.txt](https://github.com/user-attachments/files/17901732/raptor_simple.txt)

**Comment by AymenFJA** [comment] 2024-12-05 22:16
@arupcsedu, please see below the updates. I confirm that following the above steps works for Rivanna, as I tested them as well.

**Comment by arupcsedu** [comment] 2024-12-06 01:40
Thanks Aymen.
I will check.

**Comment by arupcsedu** [comment] 2024-12-11 22:04
Local schema works fine. Issue occurs with interactive schema.

**Comment by arupcsedu** [comment] 2024-12-12 03:30
[rp.session.udc-aj33-10.djy8hg.020069.0002.zip](https://github.com/user-attachments/files/18105144/rp.session.udc-aj33-10.djy8hg.020069.0002.zip)
with bii-gpu partition.

**Comment by arupcsedu** [comment] 2024-12-12 03:34
Here is the source Code: 
[neural-forecast_source.zip](https://github.com/user-attachments/files/18105156/neural-forecast_source.zip)

**Comment by andre-merzky** [comment] 2024-12-12 08:57
Minor thing: from your slurm error files:
```
Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "openmpi/4.1.6", "scalapack/2.2.0"
   Try: "module spider openmpi/4.1.6 scalapack/2.2.0" to see how to load the
module(s).
```

You need to load `nvhpc/24.5` before loading the openmpi module.  Also, please make sure that the virtualenv (or conda-env)  you are using had the exact same modules loaded during creation when it was created.

**Comment by andre-merzky** [comment] 2024-12-12 09:02
@arupcsedu : apart from the above, I am afraid I still can't reproduce your problem.  Please run the following slurm script (with the respective path changes):
```sh
#!/bin/bash
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=40
#SBATCH --time=0:30:00
#SBATCH --partition=bii
## #SBATCH -A bii_dsc_community
#SBATCH --output=rp-%x-%j.out
#SBATCH --error=rp-%x-%j.err
##SBATCH --gres=gpu:1


ENV_PATH=/sfs/gpfs/tardis/home/mma8rn/radical.pilot/ve3
SCRIPT_PATH=/sfs/gpfs/tardis/home/mma8rn/radical.pilot/raptor_simple.py

module load anaconda
module load intel
module load gcc/11.4.0
module load nvhpc/24.5
module load openmpi/4.1.6

source $ENV_PATH/bin/activate

export RADICAL_LOG_LVL="DEBUG"
export RADICAL_PROFILE="TRUE"

python $SCRIPT_PATH
```

where `raptor_simple.py` is this:
```py
#!/usr/bin/env python3

import radical.pilot as rp

# ------------------------------------------------------------------------------
#
def task_state_cb(task, state):

  # print('  task %-30s: %s' % (task.uid, task.state))
    pass


# ------------------------------------------------------------------------------
#
@rp.pythontask
def hello_world(msg, sleep):
    import time
    print('hello %s: %.3f' % (msg, time.time()))
    time.sleep(sleep)
    print('hello %s: %.3f' % (msg, time.time()))
    return 'hello %s' % msg


# ------------------------------------------------------------------------------
#
if __name__ == '__main__':

    session = rp.Session()
    try:
        pd_init = {'access_schema' : 'interactive',
                   'cores'         : 16,
                   'resource'      : 'uva.rivanna',
                   'runtime'       : 15}
        pd = rp.PilotDescription(pd_init)

        pmgr = rp.PilotManager(session=session)
        tmgr = rp.TaskManager(session=session)
        tmgr.register_callback(task_state_cb)

        pilot = pmgr.submit_pilots([pd])[0]
        tmgr.add_pilots(pilot)

        raptor = pilot.submit_raptors(rp.TaskDescription({'mode': rp.RAPTOR_MASTER}))[0]
        worker = raptor.submit_workers(rp.TaskDescription({'mode': rp.RAPTOR_WORKER, 'ranks': 26}))[0]

        td_func_1 = rp.TaskDescription({'mode': rp.TASK_FUNCTION,
                                        'function': hello_world('client', 3)})

        td_func_2 = rp.TaskDescription({'mode': rp.TASK_FUNCTION,
                                        'function': 'hello',
                                        'args'    : ['raptor', 3]})
        tasks = raptor.submit_tasks([td_func_1, td_func_2] * 256)
        tmgr.wait_tasks([task.uid for task in tasks])

        for task in tasks:
            print('%s [%s]:\n%s' % (task.uid, task.state, task.stdout))

        raptor.rpc('stop')
        tmgr.wait_tasks(raptor.uid)
        print('%s [%s]: %s' % (raptor.uid, raptor.state, raptor.stdout))

    finally:
        session.close(download=False)

# ------------------------------------------------------------------------------
```

**Comment by arupcsedu** [comment] 2024-12-17 20:39
The issue is fixed. You can close this issue.

**Closed as completed** 2024-12-17 21:10 UTC
Labels: type:bug, priority:critical, topic:configuration, comp:raptor, external
