### ISSUE TITLE
Serialization issue (affects Proxy)

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#3209] opened 2024-07-08 17:07 UTC
This run was made on Polaris (ALCF)

```
  radical.analytics    : 1.61.0
  radical.gtod         : 1.61.0
  radical.pilot        : 1.62.0-v1.61.0-1-g45b2a3a55@devel
  radical.saga         : 1.60.0
  radical.utils        : 1.61.0
```

```
 % cat rp.session.polaris-login-04.eyildirim.019909.0000.reg.log  
1720193845.733 : rp.session.polaris-login-04.eyildirim.019909.0000.reg : 3205717 : 139831830701824 : ERROR    : command failed: None
Traceback (most recent call last):
  File "/home/eyildirim/venvs/2024-04-29/lib/python3.11/site-packages/radical/utils/zmq/server.py", line 287, in _work
    req  = as_string(from_msgpack(data))
                     ^^^^^^^^^^^^^^^^^^
  File "/home/eyildirim/venvs/2024-04-29/lib/python3.11/site-packages/radical/utils/serialize.py", line 169, in from_msgpack
    return msgpack.unpackb(data, object_hook=_msgpack_decoder, raw=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
```

```
% cat server.0000.log 
1720146461.686 : server.0000          : 3205717 : 139829265327872 : ERROR    : command failed: None
Traceback (most recent call last):
  File "/home/eyildirim/venvs/2024-04-29/lib/python3.11/site-packages/radical/utils/zmq/server.py", line 287, in _work
    req  = as_string(from_msgpack(data))
                     ^^^^^^^^^^^^^^^^^^
  File "/home/eyildirim/venvs/2024-04-29/lib/python3.11/site-packages/radical/utils/serialize.py", line 169, in from_msgpack
    return msgpack.unpackb(data, object_hook=_msgpack_decoder, raw=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_unpacker.pyx", line 205, in msgpack._cmsgpack.unpackb
ValueError: Unpack failed: incomplete input
1720146461.703 : server.0000          : 3205717 : 139829265327872 : ERROR    : command failed: None
Traceback (most recent call last):
  File "/home/eyildirim/venvs/2024-04-29/lib/python3.11/site-packages/radical/utils/zmq/server.py", line 287, in _work
    req  = as_string(from_msgpack(data))
                     ^^^^^^^^^^^^^^^^^^
  File "/home/eyildirim/venvs/2024-04-29/lib/python3.11/site-packages/radical/utils/serialize.py", line 169, in from_msgpack
    return msgpack.unpackb(data, object_hook=_msgpack_decoder, raw=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
1720159156.751 : server.0000          : 3205717 : 139829265327872 : ERROR    : command failed: {'cmd': 'lookup', 'args': [{'sid': 'rp.session.polaris-login-04.eyildirim.019909.0000'}], 'kwargs': {}}
Traceback (most recent call last):
  File "/home/eyildirim/venvs/2024-04-29/lib/python3.11/site-packages/radical/utils/zmq/server.py", line 305, in _work
    rep = self._success(self._cbs[cmd](*args, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eyildirim/venvs/2024-04-29/lib/python3.11/site-packages/radical/pilot/proxy.py", line 299, in _lookup
    raise RuntimeError('client %s not registered' % sid)
RuntimeError: client rp.session.polaris-login-04.eyildirim.019909.0000 not registered
1720366668.974 : server.0000          : 3205717 : 139829265327872 : ERROR    : command failed: None
Traceback (most recent call last):
  File "/home/eyildirim/venvs/2024-04-29/lib/python3.11/site-packages/radical/utils/zmq/server.py", line 287, in _work
    req  = as_string(from_msgpack(data))
                     ^^^^^^^^^^^^^^^^^^
  File "/home/eyildirim/venvs/2024-04-29/lib/python3.11/site-packages/radical/utils/serialize.py", line 169, in from_msgpack
    return msgpack.unpackb(data, object_hook=_msgpack_decoder, raw=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_unpacker.pyx", line 205, in msgpack._cmsgpack.unpackb
ValueError: Unpack failed: incomplete input
1720366668.980 : server.0000          : 3205717 : 139829265327872 : ERROR    : command failed: None
Traceback (most recent call last):
  File "/home/eyildirim/venvs/2024-04-29/lib/python3.11/site-packages/radical/utils/zmq/server.py", line 287, in _work
    req  = as_string(from_msgpack(data))
                     ^^^^^^^^^^^^^^^^^^
  File "/home/eyildirim/venvs/2024-04-29/lib/python3.11/site-packages/radical/utils/serialize.py", line 169, in from_msgpack
    return msgpack.unpackb(data, object_hook=_msgpack_decoder, raw=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_unpacker.pyx", line 205, in msgpack._cmsgpack.unpackb
ValueError: Unpack failed: incomplete input
```

**Comment by andre-merzky** [comment] 2024-07-16 22:32
@mtitov : was this resolved, and/or is there a way to reproduce the problem?

**Comment by andre-merzky** [comment] 2024-07-25 07:13
@mtitov : ping :-)

**Comment by mtitov** [comment] 2024-07-26 12:44
related PSI/J PR https://github.com/ExaWorks/psij-python/pull/490

**Comment by andre-merzky** [comment] 2024-08-28 12:39
Since the PSI/J PR is merged, can this be closed?

**Comment by andre-merzky** [comment] 2024-09-02 09:01
Closed as PSI/J is fixed now.

**Closed by andre-merzky** 2024-09-02 09:01 UTC
Labels: type:bug, layer:utils, topic:communication, layer:rp, priority:high, internal
