### ISSUE TITLE
RP does not recognize finished long running CUs

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1463] opened 2017-09-26 15:36 UTC
I have a CU that runs for 12 hours at least. Although the CU has finished from the agent side it remains to ```UMGR_STAGING_OUTPUT_PENDING``` and I get the following errors from the client:

umgr.0000.log:
```2017-09-25 23:21:55,281: umgr.0000           : MainProcess                     : umgr.0000.subscriber._state_sub_cb: ERROR   : abort: ZMQError('Socket operation on non-socket')
Traceback (most recent call last):
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/utils/threads.py", line 375, in _run
    if not self.work_cb():
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1088, in work_cb
    topic, msg = self._q.get_nowait(500)  # timout in ms
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/utils/pubsub.py", line 352, in get_nowait
    if _uninterruptible(self._q.poll, flags=zmq.POLLIN, timeout=timeout):
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/utils/pubsub.py", line 50, in _uninterruptible
    return f(*args, **kwargs)
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/zmq/sugar/socket.py", line 558, in poll
    evts = dict(p.poll(timeout))
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2186)
  File "zmq/backend/cython/_poll.pyx", line 116, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2036)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:2811)
    raise ZMQError(errno)
ZMQError: Socket operation on non-socket
2017-09-25 23:21:55,283: umgr.0000           : MainProcess                     : umgr.0000.subscriber._state_sub_cb: INFO    : put message: [umgr.0000.subscriber._state_sub_cb.thread] ZMQError('Socket operation on non-socket')
```

pmgr.launching.queue.bridge.0000:
```
2017-09-25 13:32:32,692: pmgr.launching.queue.bridge.0000: MainProcess                     : MainThread     : DEBUG   : process class started child
2017-09-25 23:21:53,713: pmgr.launching.queue.bridge.0000: pmgr.launching.queue.bridge.0000.child: MainThread     : ERROR   : abort: ExtraData()
Traceback (most recent call last):
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/utils/process.py", line 599, in _run
    if not self.work_cb():
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 351, in work_cb
    msg = msgpack.unpackb(data)
  File "msgpack/_unpacker.pyx", line 143, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2143)
ExtraData: unpack(b) received extra data.
2017-09-25 23:21:53,720: pmgr.launching.queue.bridge.0000: pmgr.launching.queue.bridge.0000.child: MainThread     : INFO    : send message: [pmgr.launching.queue.bridge.0000.child] abort: ExtraData()
```

umgr.scheduling.queue.bridge.0000:
```
2017-09-25 23:21:53,747: umgr.scheduling.queue.bridge.0000: umgr.scheduling.queue.bridge.0000.child: MainThread     : ERROR   : abort: ExtraData()
Traceback (most recent call last):
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/utils/process.py", line 599, in _run
    if not self.work_cb():
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 351, in work_cb
    msg = msgpack.unpackb(data)
  File "msgpack/_unpacker.pyx", line 143, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2143)
ExtraData: unpack(b) received extra data.
2017-09-25 23:21:53,749: umgr.scheduling.queue.bridge.0000: umgr.scheduling.queue.bridge.0000.child: MainThread     : INFO    : send message: [umgr.scheduling.queue.bridge.0000.child] abort: ExtraData()
```

**Comment by iparask** [comment] 2017-09-26 15:37
My stack is:
```
  python               : 2.7.13
  pythonpath           :
  virtualenv           :

  radical.pilot        : 0.47-v0.46.2-17-g589063c@fix-ibrun_cpn
  radical.utils        : 0.47-v0.46-10-gc515db1@devel
  saga                 : 0.47-v0.46-5-g74fc381@devel
```

**Comment by iparask** [comment] 2017-10-04 15:39
Andre, any ideas on this?

**Comment by iparask** [comment] 2017-10-05 15:08
Hello @andre-merzky , this is replicated on Stampede. What log files do you require?

**Comment by iparask** [comment] 2017-10-05 15:42
While running on Stampede:

pmgr.launching.queue.bridge.0000:
```
2017-10-04 20:32:47,992: pmgr.launching.queue.bridge.0000: MainProcess                     : MainThread     : DEBUG   : process class started child
2017-10-04 23:38:20,565: pmgr.launching.queue.bridge.0000: pmgr.launching.queue.bridge.0000.child: MainThread     : ERROR   : abort: ExtraData()
Traceback (most recent call last):
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/utils/process.py", line 599, in _run
    if not self.work_cb():
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 351, in work_cb
    msg = msgpack.unpackb(data)
  File "msgpack/_unpacker.pyx", line 143, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2143)
ExtraData: unpack(b) received extra data.
```

umgr.0000:
```
2017-10-04 23:37:30,780: umgr.0000           : MainProcess                     : umgr.0000.subscriber._state_sub_cb: ERROR   : abort: ZMQError('Socket operation on non-socket')
Traceback (most recent call last):
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/utils/threads.py", line 375, in _run
    if not self.work_cb():
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1088, in work_cb
    topic, msg = self._q.get_nowait(500)  # timout in ms
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/utils/pubsub.py", line 352, in get_nowait
    if _uninterruptible(self._q.poll, flags=zmq.POLLIN, timeout=timeout):
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/utils/pubsub.py", line 50, in _uninterruptible
    return f(*args, **kwargs)
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/zmq/sugar/socket.py", line 558, in poll
    evts = dict(p.poll(timeout))
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2186)
  File "zmq/backend/cython/_poll.pyx", line 116, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2036)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:2811)
    raise ZMQError(errno)
ZMQError: Socket operation on non-socket
```
umgr.staging.input.queue.bridge.0000:
```
2017-10-04 20:32:54,770: umgr.staging.input.queue.bridge.0000: MainProcess                     : MainThread     : DEBUG   : process class started child
2017-10-04 23:37:29,402: umgr.staging.input.queue.bridge.0000: umgr.staging.input.queue.bridge.0000.child: MainThread     : ERROR   : abort: ExtraData()
Traceback (most recent call last):
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/utils/process.py", line 599, in _run
    if not self.work_cb():
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 351, in work_cb
    msg = msgpack.unpackb(data)
  File "msgpack/_unpacker.pyx", line 143, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2143)
ExtraData: unpack(b) received extra data.
2017-10-04 23:37:29,407: umgr.staging.input.queue.bridge.0000: umgr.staging.input.queue.bridge.0000.child: MainThread     : INFO    : send message: [umgr.staging.input.queue.bridge.0000.child] abort: ExtraData()
```

**Comment by iparask** [comment] 2017-10-06 16:21
radical-stack:
```
  python               : 2.7.13
  pythonpath           :
  virtualenv           :

  radical.pilot        : 0.47-v0.46.2-17-g589063c@fix-ibrun_cpn
  radical.utils        : 0.47-v0.46-10-gc515db1@devel
  saga                 : 0.47-v0.46-5-g74fc381@devel
```

[logs.zip](https://github.com/radical-cybertools/radical.pilot/files/1363282/logs.zip)

**Comment by andre-merzky** [comment] 2017-10-15 11:19
This is considered a duplicate of #1433.

**Closed by andre-merzky** 2017-10-15 11:19 UTC
