### ISSUE TITLE
Bootstrap failure with pip errors

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#1976] opened 2019-10-21 17:43 UTC
I am tracing a possible problem for this now but I create the issue for the record:

```
# -------------------------------------------------------------------
#
# update radical.pilot-0.90.1/ via pip
# cmd: /gpfs/alpine/bip179/scratch/hrlee/radical.pilot.sandbox/ve.ornl.summit.0.90.1/bin/pip --cert /gpfs/alpine/scratch/hrlee/bip179/radical.pilot.sandbox/re.session.login4.hrlee.018190.0005/pilot
.0000/../cacert.pem install  --src '/gpfs/alpine/scratch/hrlee/bip179/radical.pilot.sandbox/re.session.login4.hrlee.018190.0005/pilot.0000/rp_install/src' --build '/gpfs/alpine/scratch/hrlee/bip179
/radical.pilot.sandbox/re.session.login4.hrlee.018190.0005/pilot.0000/rp_install/build' --install-option='--prefix=/gpfs/alpine/scratch/hrlee/bip179/radical.pilot.sandbox/re.session.login4.hrlee.01
8190.0005/pilot.0000/rp_install' --no-deps radical.pilot-0.90.1/
#
Traceback (most recent call last):
  File "/gpfs/alpine/bip179/scratch/hrlee/radical.pilot.sandbox/ve.ornl.summit.0.90.1/bin/pip", line 6, in <module>
    from pip._internal.main import main
ImportError: No module named main
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't install radical.pilot-0.90.1/! Lets see how far we get ...
purge install source at radical.pilot-0.90.1/
```

**Comment by andre-merzky** [comment] 2019-10-21 17:49
This is likely a problem in the used combination of python and pip versions.   Can you make sure the correct Py3 modules are loaded for the pilot agent (assuming this is in the context of Py3 testing)?

**Comment by lee212** [comment] 2019-10-21 19:13
I assume this is about `pre_bootstrap_0` and `1` in the resource configuration file. I replaced the four modules with py3 like:
```
 "module load   python/3.7.0",
 "module load   py-virtualenv/16.0.0-py3",
 "module load   py-pip/10.0.1-py3",
 "module load   py-setuptools/40.2.0-py3",
```

I checked the tools which I have in the virtualenv (radical.pilot.sandbox/ve.ornl.summit.0.90.1):
```
pip 19.3.1 
Python 3.7.0 (default, Oct 12 2018, 15:17:16) 
```

**Comment by iparask** [comment] 2019-10-25 18:21
I am trying to run the tests on Bridges with python3 and I see the same error.

The modules, I load are:
```
        "pre_bootstrap_0"             : ["module purge",
                                         "module load gcc",
                                         "module load mpi/gcc_openmpi",
                                         "module load slurm",
                                         "module load python/3.6.4_gcc5_np1.14.5"
```

Python packages such as future install correctly, but the stack fails with a pip error I do not understand:
```
# -------------------------------------------------------------------
#
# install future
# cmd: /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/ve.xsede.bridges.0.90.1/bin/pip install future
#
Processing /home/paraskev/.cache/pip/wheels/74/bc/50/ae030267a192919b289f84661cfeb5573cf383841c543e8696/future-0.18.1-cp36-none-any.whl
Installing collected packages: future
Successfully installed future-0.18.1
#
# SUCCESS
#
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# install regex
# cmd: /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/ve.xsede.bridges.0.90.1/bin/pip install regex
#
Collecting regex
  Using cached https://files.pythonhosted.org/packages/ff/60/d9782c56ceefa76033a00e1f84cd8c586c75e6e7fea2cd45ee8b46a386c5/regex-2019.08.19-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: regex
Successfully installed regex-2019.8.19
#
# SUCCESS
#
# -------------------------------------------------------------------
911.9856,ve_create_stop,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
removed ‘/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/ve.xsede.bridges.0.90.1.lock’
912.0345,ve_activate_start,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
do not update virtenv /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/ve.xsede.bridges.0.90.1
912.0407,rp_install_start,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
Using RADICAL-Pilot install sources ' radical.utils-0.90.3-v0.90.3-90-gb10b5d8-python3-devel/ radical.saga-0.90.0-bv0.72.0-42-g8a55532-fix-issue-745/ radical.pilot-0.90.1-v0.90.1-47-g8eb152c-fix-pthon3-bridges/'
VE_MOD_PREFIX: /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/ve.xsede.bridges.0.90.1/lib/python3.6/site-packages
VIRTENV      : /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/ve.xsede.bridges.0.90.1
SANDBOX      : /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/rp.session.js-169-248.jetstream-cloud.org.iparask.018194.0007/pilot.0000
VE_LOC_PREFIX:
using local install tree
PYTHONPATH: /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/rp.session.js-169-248.jetstream-cloud.org.iparask.018194.0007/pilot.0000/rp_install/lib/python3.6/site-packages::/opt/packages/python/gnu_openmpi/3.6.4_np1.14.5/lib/python3.6/site-packages
rp_install: /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/rp.session.js-169-248.jetstream-cloud.org.iparask.018194.0007/pilot.0000/rp_install/lib/python3.6/site-packages
radicalmod: /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/rp.session.js-169-248.jetstream-cloud.org.iparask.018194.0007/pilot.0000/rp_install/lib/python3.6/site-packages/radical/
created radical namespace in /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/rp.session.js-169-248.jetstream-cloud.org.iparask.018194.0007/pilot.0000/rp_install/lib/python3.6/site-packages/radical//__init__.py

# -------------------------------------------------------------------
#
# update radical.utils-0.90.3-v0.90.3-90-gb10b5d8-python3-devel/ via pip
# cmd: /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/ve.xsede.bridges.0.90.1/bin/pip install  --src '/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/rp.session.js-169-248.jetstream-cloud.org.iparask.018194.0007/pilot.0000/rp_install/src' --build '/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/rp.session.js-169-248.jetstream-cloud.org.iparask.018194.0007/pilot.0000/rp_install/build' --install-option='--prefix=/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/rp.session.js-169-248.jetstream-cloud.org.iparask.018194.0007/pilot.0000/rp_install' --no-deps radical.utils-0.90.3-v0.90.3-90-gb10b5d8-python3-devel/
#
Traceback (most recent call last):
  File "/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/ve.xsede.bridges.0.90.1/bin/pip", line 6, in <module>
    from pip._internal.main import main
ModuleNotFoundError: No module named 'pip._internal'
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't install radical.utils-0.90.3-v0.90.3-90-gb10b5d8-python3-devel/! Lets see how far we get ...
purge install source at radical.utils-0.90.3-v0.90.3-90-gb10b5d8-python3-devel/
```

My stack is:
```
  python               : 3.5.2
  pythonpath           :
  virtualenv           : /home/iparask/test_rp

  radical.pilot        : 0.90.1-v0.90.1-47-g8eb152c@fix-pthon3_bridges
  radical.saga         : 0.90.0-bv0.72.0-42-g8a55532@fix-issue_745
  radical.utils        : 0.90.3-v0.90.3-90-gb10b5d8@python3-devel
```

the fix/pthon3_bridges is a branch I created locally to fix Bridges configuration

**Comment by andre-merzky** [comment] 2019-10-30 10:54
I have no good suggestion on those pip errors.  Essentially I would propose to open an interactive session toward a compute node, load the modules you have specified in `pre_bootstrap_*`, and try to create a virtualenv with that setup.  An install with `pip` should then reproduce the problem.  Then one can try to fiddle with pip upgrades or other module versions etc, and if that fails open a ticket toward XSEDE support for advice.

**Comment by mturilli** [comment] 2019-10-30 11:11
As shown in EnTK ticket #384, I successfully got around that error with: `python -m pip install radical.entk`. We should open a ticket with ORNL.

**Comment by andre-merzky** [comment] 2019-10-30 12:59
Thanks @mturilli !  @lee212 , @iparask : can you give this a try, please?  This seems to indicate an invalid pip executable / script somewhere in your path or in the virtualenv.  Pip itself does not do much besides loading the module and running it's main method:

```shell
 rivendell  merzky  ~  [master ▲] $ cat /usr/bin/pip
#!/usr/bin/python
# GENERATED BY DEBIAN

import sys

# Run the main entry point, similarly to how setuptools does it, but because
# we didn't install the actual entry point from setup.py, don't use the
# pkg_resources API.
from pip._internal import main
if __name__ == '__main__':
    sys.exit(main())
```

so it's likely that either the pip script differs in module version and API, or has an incorrect shebang.

**Comment by lee212** [comment] 2019-11-07 22:06
The `ImportError` for pip is raised by version changes according to [Release Notes](https://pip.pypa.io/en/stable/news/). For example, [pip 10.0.0b1](https://pip.pypa.io/en/stable/news/#b1-2018-03-31) introduced `_internal` where earlier versions (e.g. 9.0.1) do not have. 
There are explanations why we didn't encounter this issue before the python3 transition. `pip` in your `$PATH` tries to import the latest version but `module load` for python3 breaks `sys.path` to find a correct module location by `$PYTHONPATH`. FYI, sys.path` is `= $PYTHONPATH + $VIRTUAL_ENV` for module search. 
IMO, this can be fixed either by removing redundant `module load` or clearing `$PYTHONPATH` in each `pip` command line. For example, new virtualenv (ve.ornl.summit.0.90.1) has the latest `pip 19.3.1` but `module load py-pip` sets `$PYTHONPATH` with `pip 10.0.1`, and removing `module load py-pip` works. On bridges, there are no pip modules but all modules for python3 including `python/3.6.4_gcc5_np1.14.5` contain pip 9.0.1. One trick I can think of is like `PYTHONPATH= pip install xxx` in a shell clears the precedence of the path to search.

**Comment by andre-merzky** [comment] 2019-11-07 22:14
the `fix/py3_summit` now works on summit (needs RU devel).  The pip problem can be resolved by unloading the pip module - it conflicts with the default pip from the python module.  I would not be  surprised if a similar conflict exists on bridges.

**Comment by andre-merzky** [comment] 2019-11-12 09:42
To recapture the discussion from the last call:
this points to a version problem in PIP.  Please try to reproduce this interactively on Bridges, and if that fails on the compute nodes, open a ticket.  If it works we need to understand the difference (in modules?) to what the bootstrapper uses.

**Comment by andre-merzky** [comment] 2019-11-12 20:12
TODO IP: try conda config.

**Comment by lee212** [comment] 2019-11-14 19:12
Test on Bridges fails:

```
Traceback (most recent call last):
  File "/pylon5/mc3bggp/hrlee/radical.pilot.sandbox/ve.xsede.bridges.0.90.1/bin/
pip", line 6, in <module>
    from pip._internal.main import main
ImportError: No module named 'pip._internal.main'
```

I guess this can be avoided by asking administrator to upgrade `pip` to 19.3.1 or latest, OR
`bootstrap_0.sh` clears wrong `$PYTHONPATH` to search a module.

**Comment by andre-merzky** [comment] 2020-02-03 15:50
Late update on that issue: pip released a version which caused the referenced problem in several different circumstances.  While that pip version was replaced fairly shortly, it made it into several downstream packages and installations.  Our recent problems on travis were also caused by this.

An update of the pip installation should in principle help.  If not, its likely worthwhile to open a ticket with the resource admin.

Closing as out of scope for RP.

**Closed by andre-merzky** 2020-02-03 15:50 UTC
Labels: comp:agent:bootstrapper, layer:rp, priority:high, topic:deployment, type:bug
