### ISSUE TITLE
Radical Pilot issue with Anaconda

### ISSUE THREAD

**Issue by mkzia** [radical-cybertools/radical.pilot#434] opened 2014-11-16 00:13 UTC
Hi,
I usually install Ananconda in my local work space and then use that as my Python distribution.

One issue that crops up with using Radical Pilot with Anaconda is that you have to specify the LD_LIBRARY_PATH in the bash profile to point to ~*/anaconda/lib.

Otherwise,  AGENT.STDOUT file will show the following error
V################################################################################
## CMDLINE: /home/mzia/anaconda/bin/python virtualenv-1.9/virtualenv.py /home/mzia/radical.pilot.sandbox/pilot-5467e2d6e1382338aa374327/virtualenv/
New python executable in /home/mzia/radical.pilot.sandbox/pilot-5467e2d6e1382338aa374327/virtualenv/bin/python
ERROR: The executable /home/mzia/radical.pilot.sandbox/pilot-5467e2d6e1382338aa374327/virtualenv/bin/python is not functioning
ERROR: It thinks sys.prefix is u'/home/mzia/radical.pilot.sandbox/pilot-5467e2d6e1382338aa374327' (should be u'/home/mzia/radical.pilot.sandbox/pilot-5467e2d6e1382338aa374327/virtualenv')
ERROR: virtualenv is not compatible with this system or executable
Couldn't bootstrap virtualenv! ABORTING
(END) 

This mesage isn't very helpful. But if I try to launch the python in the virtualenv (/virtualenv/bin/python), I get the following error:
./python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

This issue is resolved by adding the following to one's bash_profile 
export LD_LIBRARY_PATH=path_to_anaconda/lib

Maybe this work around should be added to the RP documentation. 

Thanks,
--Mohammad

**Comment by andre-merzky** [comment] 2015-09-15 09:29
This is a duplicate of #669 and #716.

**Closed by andre-merzky** 2015-09-15 09:29 UTC
Labels: documentation
