### ISSUE TITLE
Python module not loaded on stampede

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1276] opened 2017-03-11 14:16 UTC
I tested for 16 CUs on Comet and this branch works, and am going to submit 256 CUs to see how the branch performs. However, I now get the following problem on Stampede. It seems that Python was not loaded on Stampede

```
/home1/03662/tg829619/bin/ve.synapse/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory\n
```

radical-stack
```
python            : 2.7.6
virtualenv        : /home/mingtha/ve/ve.exec_model_exp_devel
radical.utils     : v0.45-2-g82050c5@devel
saga-python       : split-4-gaa285ca4@devel
radical.pilot     : split-22-g3624734d@HEAD-detached-at-origin-feature-comet_ortelib
radical.analytics : v0.1-137-g05f47f3@devel
```

**Comment by andre-merzky** [comment] 2017-03-11 20:35
Can you please retry with the devel branch?  This looks as if the resource config points to a python module which is not available on Stampede anymore - 2.7.12 should be the current one.

**Comment by mingtaiha** [comment] 2017-03-11 22:17
I **need** to run with the `feature/comet_ortelib` so I can run on OSG and XSEDE HPC resources using the same stack for my experiments and compare results. Using the `devel` branch will mean that I can't properly run my experiments.

**Comment by andre-merzky** [comment] 2017-03-12 00:57
I am not sure I understand that -- devel does everything what `feature/comet_ortelib` does - apart from supporting ortelib on comet, as the branch name says.  Or do you mean you need `experiment/aimes`?  That also has the correct python module for stampede configured.  I am not sure why you want to test a comet specific branch on stampede - what am I missing?

**Comment by mingtaiha** [comment] 2017-03-12 19:06
Perhaps I am missing something... After testing the `feature/comet_ortelib`, will the `feature/comet_ortelib` branch be merged back to `devel`?

**Comment by andre-merzky** [comment] 2017-03-12 19:49
yes.

**Comment by mingtaiha** [comment] 2017-03-12 19:51
I thought the `feature/comet_ortelib` changes would not be immediately merged back. Sorry for the misudnerstanding.

**Comment by andre-merzky** [comment] 2017-03-12 19:52
np :)

**Comment by mingtaiha** [comment] 2017-03-17 03:26
This problem occurs on Gordon and SuperMIC after the `feature/comet_ortelib` has been merged into `devel`. I will keep you posted on whether this error occurs on Stampede again (but on `devel`).

Current `radical-stack`:
```
ython            : 2.7.6
virtualenv        : /home/mingtha/ve/ve.exec_model_exp_devel
radical.utils     : v0.45-2-g82050c5@devel
saga-python       : split-4-gaa285ca4@devel
radical.pilot     : split-28-gae1602f6@devel
radical.analytics : v0.1-137-g05f47f3@devel
```

**Comment by andre-merzky** [comment] 2017-03-17 09:37
Hmm, the merge should not have affected Supermic and Gordon.  Are you sure that did not happen before the merge on those machines?

Thanks, Andre.

**Comment by mingtaiha** [comment] 2017-03-17 14:43
I am very sure.

**Comment by andre-merzky** [comment] 2017-03-17 14:51
Thanks  for checking.

**Comment by andre-merzky** [comment] 2017-03-19 21:46
I am really sorry Ming, but I don't get it: the `feature/comet_ortelib` only affected the comet configuration - how can that influenced non-comet on stampede?

So I tried the following workload:

```
        cuds = list()
        for i in range(0, n):
            cud = rp.ComputeUnitDescription()
            cud.pre_exec   = ['module load python']
            cud.executable = 'python'
            cud.arguments  = '-V'
            cuds.append(cud)
            report.progress()

        report.ok('>>ok\n')
        units = umgr.submit_units(cuds)

        report.header('gather results')
        umgr.wait_units()

        report.info('\n')
        for unit in units:
            report.plain('  * %s: %s, exit: %3s, out: %s\n' \
                    % (unit.uid, unit.state[:4],
                        unit.exit_code, unit.stderr.strip()[:35]))
        report.info('\n')
``` 

and that seems to work as expected:

```
...
--------------------------------------------------------------------------------
gather results                                                                  

wait for 128 unit(s)
        +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++|
        +++++++++++++++++++++++++++++++++++++++++++++++++++++++++             ok

  * unit.000000: DONE, exit: None, out: Python 2.6.6
  * unit.000001: DONE, exit: None, out: Python 2.6.6
  * unit.000002: DONE, exit: None, out: Python 2.6.6
  * unit.000003: DONE, exit: None, out: Python 2.6.6
...
```

Can you provide a script which illustrates your problem?

**Comment by mingtaiha** [comment] 2017-03-20 18:17
Which machine did you use to run this script? I thought `pre_exec` is currently broken

Also, the workload I am running CUs which use Synapse emulator.
```
        pdescs.append(rp.ComputePilotDescription(pd_init))
        pilots = pmgr.submit_pilots(pdescs)
    
        umgr = rp.UnitManager(session=session)
        umgr.add_pilots(pilots)
    
        cuds = list()
        
        for task in range(CORES * UTIL):
            cud = rp.ComputeUnitDescription()
            #cud.pre_exec = ['source $HOME/bin/ve.synapse/bin/activate']
            cud.executable = 'source $HOME/bin/ve.synapse/bin/activate; aimes-skeleton-synapse.py serial flops 1 1715750072310 65536 65536 0 0 0'
            cuds.append(cud)
    
        umgr.submit_units(cuds)
        umgr.wait_units()
```

**Comment by iparask** [comment] 2017-03-20 19:59
Just as a reminder.

On Stampede, specifically me, Andre & Mark had a long discussion about the environment that a CU has. The discussion was initiated because modules could not be loaded from the CU ```pre_exec```. 

Reference Ticket #1043, which was fixed with #1134. 

When using resources with ORTE run at least the environment that is offered is not "clean", thus module loading is not possible (Ticket #1190 )

**Comment by mingtaiha** [comment] 2017-03-20 20:05
I see. I'll try again with including `module load python` before running my script

**Comment by iparask** [comment] 2017-03-20 21:06
I re-opened #1043

**Comment by andre-merzky** [comment] 2017-03-21 09:11
Thanks both - there was indeed a botched merge, and my test showed a false positive.  The fix is now in  #1284.  Please give the `fix/issue_1276` branch a try, I'll merge as soon as that is confirmed to work.

**Comment by iparask** [comment] 2017-03-21 16:01
No it does not work. It still does not reset the CU environment to the default one

**Comment by mingtaiha** [comment] 2017-03-21 16:08
On Supermic and Gordon, it seemed that adding `module load python` in the pre-exec resolved the issue. On Stampede, the `fix/issue_1276` and including `module load python` was needed. I tested for 16 CUs. I am assuming this will work for more CUs.

**Comment by iparask** [comment] 2017-03-21 16:22
It worked.

**Comment by andre-merzky** [comment] 2017-03-21 18:04
> I am assuming this will work for more CUs.

Yes, the fix is scale-independent.

Thanks to both of you for testing!

**Closed by andre-merzky** 2017-03-21 18:04 UTC
Labels: bug
