### ISSUE TITLE
Data staging to pilot broken?

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#2392] opened 2021-05-12 20:44 UTC
```
  python               : /home/scm177/Virtual_Envs/repex_env_2/bin/python3
  pythonpath           : 
  version              : 3.6.10
  virtualenv           : /home/scm177/Virtual_Envs/repex_env_2

  radical.entk         : 1.6.5
  radical.gtod         : 1.5.0
  radical.pilot        : 1.6.5-v1.6.5-180-g7c5cb93@devel
  radical.repex        : 0.72.0-3222e61@user-repex
  radical.saga         : 1.6.5
  radical.utils        : 1.6.5
```

Above is the stack I am using. I seemed fine last week, but today morning I find that there are no input files in the agent sandbox. Only broken symbolic links. 

Grep does not reveal anything, for some reason. Please advise.

**Comment by SrinivasMushnoori** [comment] 2021-05-17 15:35
Quick ping!

**Comment by andre-merzky** [comment] 2021-05-17 15:38
Just wanted to ping back also :-)  I tried to reproduce the problem, but could not so far.  Can you please provide the resource and workflow configs you are using?  Thanks!

**Comment by SrinivasMushnoori** [comment] 2021-05-17 16:05
Resource config looks like:

```
{
    "rmq_host" : "localhost",
    "rmq_port" : 32769,

    "resource" : "xsede.bridges2",
    "walltime" : 10,
    "cpus"     : 32,
    "gpus_per_node" : 0,
        "access_schema" : "gsissh",
        "queue"         : "RM",
        "project"       : "dmr170002p"
}
```

Workflow config is as follows:

```
{
    "config" : {
        "min_temp"       : 300,
        "max_temp"       : 400,
        "timesteps"      : 1000,
        "replicas"       : 8,
        "cycles"         : 5
    },

    "data" : {
        "inputs"         : "inputs/",
        "outputs"        : "outputs/"
    },

    "prepare"            : {
        "algorithm"      : "workload_md.py:prepare_md",
        "basename"       : "FF-FNF-20%"
    },

                       ### FF.itp  FNF.itp  inpcrd.gro  inp.ener  martini_v2.2.itp  mdin.mdp  sys.top  WF.itp
    "md" : {"inputs" : ["mdin.mdp.%(rid)s > mdin.mdp",
                        "sys.top          > sys.top",
                        "FF.itp           > ff.itp",
                        "FNF.itp          > fnf.itp",
                        "inp.ener         > inp.ener",
                        "martini_v2.2.itp > martini_v2.2.itp"],

            # only linked for cycle 0
            #                    inputs         > cycle 0
            "inputs_0": ["inpcrd.gro.%(rid)s > inpcrd.gro"],
            "ex_2_md"        : ["outcrd.gro.%(rid)s > inpcrd.gro"],

            # stage back output from all cycles
            # FIXME: not enacted yet
            "outputs"        : ["outcrd.gro         > outcrd.gro.%(rid)s.%(cycle)04d"],
# only staged back from last cycle (n/a)
            "outputs_n"      : ["outcrd.gro         > outcrd.gro.%(rid)s.last"],
            "description": [{ "executable"     : "gmx_mpi",
                              "arguments"      : [ "grompp",
                                                  "-f", "mdin.mdp",
                                                  "-c", "inpcrd.gro",
                                                  "-o", "sys.tpr",
                                                  "-p", "sys.top"
                                                ],
                           "cpu_reqs"       : {"cpu_processes"    : 1,
                                               "cpu_threads"      : 1,
                                               "cpu_thread_type"  : null,
                                               "cpu_process_type" : "MPI"
                                              },
                           "pre_exec"       : ["module load gromacs/2020.2-cpu"]

                          },
                          {
                            "executable"     : "gmx_mpi",
                            "arguments"      : [ "mdrun",
                                                "-s",      "sys.tpr",
                                                "-deffnm", "sys",
                                                "-c",      "outcrd.gro",
                                                 "-e",      "sys.edr", "-cpt", "10000"

                                            ],
                            "cpu_reqs"       : {"cpu_processes"    : 4,
                                                "cpu_threads"      : 1,
                                                "cpu_thread_type"  : null,
                                                "cpu_process_type" : "MPI"
                                            },
                            "pre_exec"       : ["module load gromacs/2020.2-cpu"]
                        },
                        {
                            "executable"     : "gmx_mpi",
                            "arguments"      : [ "energy",
                                                "-f", "sys.edr",
                                                "-b", 0.25,
                                                "<", "inp.ener", ">",
                                                "mdinfo"
                                            ],
                            "cpu_reqs"       : {"cpu_processes"    : 1,
                                                "cpu_threads"      : 1,
                                                "cpu_thread_type"  : null,
                                                "cpu_process_type" : "MPI"
                                            },
                            "pre_exec"       : ["module load gromacs/2020.2-cpu"]
                        }]},
    "selection" : {
        "algorithm"      : "algorithm_select_all.py:select_replicas_all",
        "exchange_size"  : 4
    },

    "exchange" : {
        "algorithm"      : "algorithm_exchange_random.py:exchange_by_temperature",
        "md_2_ex"        : ["mdinfo  > mdinfo.%(rid)s",
                            "outcrd.gro  > outcrd.gro.%(rid)s"],
        "ex_data"        : ["outcrd.gro.%(rid)s"]
    }
}

```

**Comment by SrinivasMushnoori** [comment] 2021-05-17 16:26
Also, I just saw this in `tmgr_scheduling.0000.log`


```
1621267975.693 : tmgr_scheduling.0000 : 7225  : 140284118271744 : ERROR    : task schedule preparation failed
Traceback (most recent call last):
  File "/home/scm177/Virtual_Envs/repex_env_2/lib/python3.6/site-packages/radical/pilot/tmgr/scheduler/round_robin.py", line 163, in _schedule_tasks
    self._assign_pilot(task, pilot)
  File "/home/scm177/Virtual_Envs/repex_env_2/lib/python3.6/site-packages/radical/pilot/tmgr/scheduler/base.py", line 346, in _assign_pilot
    task['resource_sandbox'] = str(self._session._get_resource_sandbox(pilot))
  File "/home/scm177/Virtual_Envs/repex_env_2/lib/python3.6/site-packages/radical/pilot/session.py", line 736, in _get_resource_sandbox
    shell = self.get_js_shell(resource, schema)
  File "/home/scm177/Virtual_Envs/repex_env_2/lib/python3.6/site-packages/radical/pilot/session.py", line 782, in get_js_shell
    shell = rsup.PTYShell(js_url, self)
  File "/home/scm177/Virtual_Envs/repex_env_2/lib/python3.6/site-packages/radical/saga/utils/pty_shell.py", line 248, in __init__
    self.pty_shell  = self.factory.run_shell  (self.pty_info)
  File "/home/scm177/Virtual_Envs/repex_env_2/lib/python3.6/site-packages/radical/saga/utils/pty_shell_factory.py", line 464, in run_shell
    self._initialize_pty (sh_slave, info)
  File "/home/scm177/Virtual_Envs/repex_env_2/lib/python3.6/site-packages/radical/saga/utils/pty_shell_factory.py", line 427, in _initialize_pty
    raise ptye.translate_exception (e) from e
  File "/home/scm177/Virtual_Envs/repex_env_2/lib/python3.6/site-packages/radical/saga/utils/pty_shell_factory.py", line 300, in _initialize_pty
    raise rse.NoSuccess("Could not detect shell prompt (timeout)")
radical.saga.exceptions.NoSuccess: Could not detect shell prompt (timeout) (/home/scm177/Virtual_Envs/repex_env_2/lib/python3.6/site-packages/radical/saga/utils/pty_shell_factory.py \
+300 (_initialize_pty)  :  raise rse.NoSuccess("Could not detect shell prompt (timeout)"))
```
[Full logs here.](https://github.com/radical-cybertools/radical.pilot/files/6495342/tarball.tar.gz)

**Comment by andre-merzky** [comment] 2021-05-17 19:04
That pty error will result in failed tasks, but will not cause the invalid symlinks you encounter.  Does the pty error happen every time?

**Comment by SrinivasMushnoori** [comment] 2021-05-17 19:05
Testing.

**Comment by SrinivasMushnoori** [comment] 2021-05-17 19:58
Appears to be consistent. The tasks fail explicitly because the gromacs kernel cannot find any input files to run, i.e. broken links.

**Comment by SrinivasMushnoori** [comment] 2021-05-24 17:24
Ping!

**Comment by mtitov** [comment] 2021-05-24 19:16
hi @SrinivasMushnoori, I'm going through logs and would need your help to understand experiment setup - so I see that tasks do staging, but that staging is going from the pilot-sandbox to every task-sandbox
e.g.,
```
         {'_id': 'task.0006',
          'description': {.....
                          'input_staging': [{'action': 'Link',
                                             'flags': 64,
                                             'priority': 0,
                                             'source': 'pilot:///inputs//mdin.mdp.rep.0002',
                                             'target': 'task:///mdin.mdp',
                                             'uid': 'sd.0022'},
                          .....
```
but I don't see that you would set staging to the pilot-sandbox
e.g.,
```
{.....
 'description': {'access_schema': 'gsissh',
                 .....
                 'input_staging': [],
                 'output_staging': [],
                 'project': 'dmr170002p',
                 'queue': 'RM',
                 'resource': 'xsede.bridges2',
                 'runtime': 10,
                 .....},
.....
 'type': 'pilot',
 'uid': 'pilot.0000'}
```
Should that be setup with `appman.shared_data`?

**Comment by mturilli** [comment] 2021-06-29 09:08
Ping.

**Comment by SrinivasMushnoori** [comment] 2021-07-01 17:26
Apologies for the temporary disengagement. I was busy with job interviews. 
Now that I am done with that, I am re-engaging. 
`appman.shared_data` is not something that was ever there in RepEx before, is this a new API element that was added to EnTK?

**Comment by mtitov** [comment] 2021-07-01 17:41
hi @SrinivasMushnoori not the new one (https://radicalentk.readthedocs.io/en/stable/user_guide/adding_shared_data.html), looks like I was confused that you use "plain" EnTK. How do you define data staging? (or it is not overwritten and you re-use corresponding EnTK's method?)

**Comment by SrinivasMushnoori** [comment] 2021-07-01 17:58
By "Data staging" I simply mean data moving from the client to the agent sandbox. 
When I run a job, I find the job fails: because it cannot find any of the required files in the agent/unit sandboxes.
I have triple checked that the file names are correctly referenced in the config files and are in the right directory.

**Comment by mtitov** [comment] 2021-07-01 18:01
sorry, I meant within the code (and within RepEx)

**Comment by SrinivasMushnoori** [comment] 2021-07-01 18:07
It is defined here:
https://github.com/radical-cybertools/radical.repex/blob/devel/src/radical/repex/replica.py#L78

That method defines the replica's MD stage, where the required files are used to perform MD.

**Comment by mtitov** [comment] 2021-07-01 18:42
Thank you for the link, for pilot staging it sets here then: https://github.com/radical-cybertools/radical.repex/blob/devel/src/radical/repex/exchange.py#L81
(1st data staged to the pilot sandbox, and then, what your link points out, from pilot to task sandbox)

**Comment by SrinivasMushnoori** [comment] 2021-07-01 18:46
Yes, that should be it!

**Comment by SrinivasMushnoori** [comment] 2021-07-07 20:43
Quick ping!

**Comment by mtitov** [comment] 2021-07-07 22:04
hi @SrinivasMushnoori , I thought you will check that you do set that and will get back with updates

**Comment by SrinivasMushnoori** [comment] 2021-07-07 22:16
Apologies for the miscommunication: yes I do set it, here:
https://github.com/radical-cybertools/radical.repex/blob/devel/bin/radical-repex#L92

**Comment by SrinivasMushnoori** [comment] 2021-07-08 22:58
Hi @mtitov 
Just so we're on the same page, and to ensure that I am not misunderstanding anything, does this answer your question?

**Comment by mtitov** [comment] 2021-07-09 00:04
hi @SrinivasMushnoori yes, it does, I'll go through it (sorry for previous confusions)

**Comment by SrinivasMushnoori** [comment] 2021-07-09 00:05
No worries!

**Comment by SrinivasMushnoori** [comment] 2021-07-13 22:51
Gentle ping! This is the more pressing of the repex issues at the moment

**Comment by andre-merzky** [comment] 2021-07-14 09:54
Sorry for the silence on this issue thread, but we are actually working on this issue, and hope to have it resolved in the next days.

**Comment by SrinivasMushnoori** [comment] 2021-07-14 17:46
No worries! I look forward to the fix!

**Comment by mtitov** [comment] 2021-07-14 19:53
hi @SrinivasMushnoori , can you please try RP branch `fix/stager` as an early fix attempt
```
pip install git+https://github.com/radical-cybertools/radical.pilot.git@fix/stager
```

**Comment by SrinivasMushnoori** [comment] 2021-07-14 19:54
On it

**Comment by SrinivasMushnoori** [comment] 2021-07-14 21:10
Unsure what went wrong, but repex itself breaks now...
```
(repex_env) scm177@McEwan:~/RCT/repex.gmx$ radical-repex resource_bridges.json workflow_gromacs.json 
Traceback (most recent call last):
  File "/home/scm177/Virtual_Envs/repex_env/bin/radical-repex", line 7, in <module>
    import radical.repex as rx
  File "/home/scm177/Virtual_Envs/repex_env/lib/python3.6/site-packages/radical/repex/__init__.py", line 6, in <module>
    from .exchange   import Exchange
  File "/home/scm177/Virtual_Envs/repex_env/lib/python3.6/site-packages/radical/repex/exchange.py", line 15
    import .states as rxs
           ^
SyntaxError: invalid syntax
```

@andre-merzky did something happen during merge? I tested the PR branch before I approved, seemed fine...

**Comment by mtitov** [comment] 2021-07-14 21:38
@SrinivasMushnoori seems like that line is in `devel` branch only, and is not used later in a code, thus could be removed

**Comment by SrinivasMushnoori** [comment] 2021-07-14 23:24
```
(repex_env) scm177@McEwan:~/RCT/repex.gmx$ radical-repex resource_bridges.json workflow_gromacs.json 
Traceback (most recent call last):
  File "/home/scm177/Virtual_Envs/repex_env/bin/radical-repex", line 36, in <module>
    resource=rs)
  File "/home/scm177/Virtual_Envs/repex_env/lib/python3.6/site-packages/radical/repex/exchange.py", line 46, in __init__
    assert(self._workload.config.replicas or self._replicas)
AttributeError: 'NoneType' object has no attribute 'replicas'
```
Is there a specific stack I should be using? 

```

  python               : /home/scm177/Virtual_Envs/repex_env/bin/python3
  pythonpath           : 
  version              : 3.6.10
  virtualenv           : /home/scm177/Virtual_Envs/repex_env

  radical.entk         : 1.5.7-v1.5.7-30-g5a3af3a@user-repex
  radical.gtod         : 1.6.7
  radical.pilot        : 1.6.7-v1.6.7-1-g70be180@fix-stager
  radical.repex        : 0.72.0-544c128@devel
  radical.saga         : 1.6.8
  radical.utils        : 1.6.7
```

**Comment by mtitov** [comment] 2021-07-14 23:58
@SrinivasMushnoori for the run from the first message here, you used repex branch `user/repex`, maybe try that? as well for entk better to use either `master` (v1.6.5) or `devel` branch (l guess `devel` is preferable)

**Comment by SrinivasMushnoori** [comment] 2021-07-15 17:30
It gives me the same error, unfortunately...

**Comment by mtitov** [comment] 2021-07-15 18:05
@SrinivasMushnoori sorry that fix didn't help, maybe it triggers something else... can you please upload logs (with pilot and client sandboxes)

**Comment by SrinivasMushnoori** [comment] 2021-07-15 19:25
There are no logs. This seems to be a python level failure where the RCT stack does not even get triggered.

**Comment by SrinivasMushnoori** [comment] 2021-07-15 20:21
[logs from latest run](https://github.com/radical-cybertools/radical.pilot/files/6826038/logs.tar.gz)

**Comment by SrinivasMushnoori** [comment] 2021-07-15 20:45
[Corrected logs](https://github.com/radical-cybertools/radical.pilot/files/6826148/logs.tar.gz)

**Comment by SrinivasMushnoori** [comment] 2021-07-16 04:25
```
  python               : /home/scm177/Virtual_Envs/repex_env/bin/python3
  pythonpath           : 
  version              : 3.6.10
  virtualenv           : /home/scm177/Virtual_Envs/repex_env

  radical.entk         : 1.6.7-v1.6.7@master
  radical.gtod         : 1.6.7
  radical.pilot        : 1.6.7-v1.6.7-5-g25a42e3@fix-stager
  radical.repex        : 0.72.0-3222e61@user-repex
  radical.saga         : 1.6.8
  radical.utils        : 1.6.7

```
[logs with the stack above](https://github.com/radical-cybertools/radical.pilot/files/6827804/logs.tar.gz)

**Comment by SrinivasMushnoori** [comment] 2021-07-16 19:52
[logs with SAGA staging fix](https://github.com/radical-cybertools/radical.pilot/files/6833067/logs.tar.gz)

**Comment by SrinivasMushnoori** [comment] 2021-07-16 21:55
[logs with stack given below](https://github.com/radical-cybertools/radical.pilot/files/6833538/logs.tar.gz)

```
(repex_env) scm177@McEwan:~/RCT/repex.gmx$ radical-stack 
WARNING: You are using radical.entk version 1.6.5, however version 1.6.7 is available.

  python               : /home/scm177/Virtual_Envs/repex_env/bin/python3
  pythonpath           : 
  version              : 3.6.10
  virtualenv           : /home/scm177/Virtual_Envs/repex_env

  radical.entk         : 1.6.5
  radical.gtod         : 1.6.7
  radical.pilot        : 1.6.7-v1.6.7-5-g25a42e3@fix-stager
  radical.repex        : 0.72.0-3222e61@user-repex
  radical.saga         : 1.6.7-v1.6.7-8-g15865a5@fix-staging
  radical.utils        : 1.6.7

```

**Comment by SrinivasMushnoori** [comment] 2021-07-16 23:10
[logs with stack below](https://github.com/radical-cybertools/radical.pilot/files/6833695/logs.tar.gz)

```
(repex_env) scm177@McEwan:~/RCT/repex.gmx$ radical-stack
WARNING: You are using radical.entk version 1.6.5, however version 1.6.7 is available.

  python               : /home/scm177/Virtual_Envs/repex_env/bin/python3
  pythonpath           : 
  version              : 3.6.10
  virtualenv           : /home/scm177/Virtual_Envs/repex_env

  radical.entk         : 1.6.5
  radical.gtod         : 1.6.7
  radical.pilot        : 1.6.7-v1.6.7-5-g25a42e3@fix-stager
  radical.repex        : 0.72.0-3222e61@user-repex
  radical.saga         : 1.6.7-v1.6.7-10-g5e0a50b@fix-staging
  radical.utils        : 1.6.7

```

**Comment by mtitov** [comment] 2021-07-17 00:44
Srinivas confirmed that issue was resolved

**Closed** 2021-07-17 00:45 UTC
Labels: layer:entk, layer:rp, type:bug

**Comment by andre-merzky** [comment] 2021-07-20 17:34
Hi @SrinivasMushnoori - is this issue resolved with the last fixes from @mtitov or does it persist?  I am not sure if the last logs were attached before or after :-/
