### ISSUE TITLE
RP unstable on BW - 0.46.RC1

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1394] opened 2017-07-24 23:46 UTC
Almost 1 out of 3 of the runs are failing on BW. All units are reported failed. I have attached the log files with this ticket form one of the failed runs.
[rp.session.js-172-77.jetstream-cloud.org.vivek91.017371.0036.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1171527/rp.session.js-172-77.jetstream-cloud.org.vivek91.017371.0036.tar.gz)

Error (agent_0.err):
```
Traceback (most recent call last):
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.js-172-77.jetstream-cloud.org.vivek91.017371.0036/pilot.0000/rp_install/bin/radical-pilot-agent", line 26, in <module>
    rp.agent.bootstrap_3(agent_name)
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.js-172-77.jetstream-cloud.org.vivek91.017371.0036/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/bootstrap_3.py", line 47, in bootstrap_3
    agent.start(spawn=False)
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.js-172-77.jetstream-cloud.org.vivek91.017371.0036/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/process.py", line 491, in start
    self._ru_initialize()
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.js-172-77.jetstream-cloud.org.vivek91.017371.0036/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/process.py", line 802, in _ru_initialize
    self.ru_initialize_common()
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.js-172-77.jetstream-cloud.org.vivek91.017371.0036/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 537, in ru_initialize_common
    self._log)
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.js-172-77.jetstream-cloud.org.vivek91.017371.0036/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 252, in start_components
    comp.start()
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.js-172-77.jetstream-cloud.org.vivek91.017371.0036/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/process.py", line 495, in start
    self.stop()
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.js-172-77.jetstream-cloud.org.vivek91.017371.0036/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 707, in stop
    super(Component, self).stop(timeout)
  File "/scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.js-172-77.jetstream-cloud.org.vivek91.017371.0036/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/process.py", line 766, in stop
    raise RuntimeError(errors)
RuntimeError: ['could not join child process 27561']
```

```
  python               : 2.7.6
  pythonpath           : /home/vivek91/packages/seisflows
  virtualenv           : /home/vivek91/ves/test_rp

  radical.pilot        : 0.46-v0.46.RC1@detached-v0.46.RC1
  radical.utils        : 0.46-v0.46.RC1@detached-v0.46.RC1
  saga                 : 0.46-v0.46.RC1@detached-v0.46.RC1
```

The same script completed successfully the next two times.

**Comment by andre-merzky** [comment] 2017-07-25 05:28
Closed as duplicate of #1390

**Closed by andre-merzky** 2017-07-25 05:28 UTC

**Comment by andre-merzky** [comment] 2017-07-25 06:54
Apologies, this was not a duplicate after all.  What happened here is that a sanity check tripped over some apparent Python multiprocessing inconsistency or timing issue: a child process appeared alive after calling `terminate()` on it, which should happen.  I made this a warning now in the `fix/issue_1394` branch, and this will go into the next RC or the release.

Thanks Vivek!

**Comment by vivek-bala** [comment] 2017-07-25 13:04
Hey Andre, thanks for the fix. I am a bit confused on how to proceed with testing: should I continue testing with 0.46.RC1 (which will keep producing these errors) on BW or should I switch to fix/issue_1394 branch for BW?
