### ISSUE TITLE
agent 0 fails on titan

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1197] opened 2017-01-31 18:23 UTC
agent_0.err (tail):

```
2017-01-31 13:09:11,105: radical.utils       : MainProcess                     : MainThread     : DEBUG   : lm new manager
Traceback (most recent call last):
  File "/lustre/atlas2/csc230/scratch/vivekb/radical.pilot.sandbox/ve_titan/rp_install/bin/radical-pilot-agent", line 42, in <module>
    rp.agent.bootstrap_3(agent_name)
  File "/lustre/atlas2/csc230/scratch/vivekb/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/agent/bootstrap_3.py", line 48, in bootstrap_3
    agent.start(spawn=False)
  File "/lustre/atlas2/csc230/scratch/vivekb/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 724, in start
    ru.cancel_main_thread()
  File "/lustre/atlas2/csc230/scratch/vivekb/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/utils/threads.py", line 285, in cancel_main_thread
    thread.interrupt_main()
TypeError: 'int' object is not callable
```

Uploading sandbox: [rp.session.titan-ext2.vivekb.017197.0002.zip](https://github.com/radical-cybertools/radical.pilot/files/742803/rp.session.titan-ext2.vivekb.017197.0002.zip)

Let me know how I can help debug/fix.

**Comment by vivek-bala** [comment] 2017-01-31 18:24
versions:
```
> radical-stack 
python            : 2.7.9
virtualenv        : /autofs/nccs-svm1_home1/vivekb/ves/test_rp
radical.utils     : v0.44-13-ge86642c@no-branch
saga-python       : v0.44-124-gc1dbe1d@no-branch
radical.pilot     : v0.44.RC1-651-gd514e48@no-branch
```

**Comment by vivek-bala** [comment] 2017-01-31 18:42
No cu submission occurs even though the titan job is running. Fails about 10 mins after titan job starts. Pilot seems to remain in pending_active state.

**Comment by andre-merzky** [comment] 2017-01-31 19:53
Hey Vivek - I am afraid this is a duplicate of #1188.  I am debugging this right now, but so far its elusive...

**Closed by andre-merzky** 2017-01-31 19:53 UTC

**Comment by vivek-bala** [comment] 2017-01-31 20:17
Ok, I'll follow that ticket. FWIW I wasn't facing this issue last week and used the same radical stack.

**Comment by andre-merzky** [comment] 2017-01-31 20:19
Yes, the problem intermittent - a message gets sometimes lost.  Seems to be a timing issue or race condition...
