### ISSUE TITLE
cannot stage shared data using devel

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1285] opened 2017-03-22 23:04 UTC
I get the following error when trying to stage in data with the pilot: ```caught Exception: 'NoneType' object has no attribute 'endswith'```

I think the source of the error might be https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/compute_pilot.py#L549 where ```self.sandbox``` has the value ```None```.

This can be reproduced by running examples/07_shared_unit_data.py.

Stack:
```
$ radical-stack 
python            : 2.7.6
virtualenv        : /home/vivek91/repos/ee_super_4c/myenv
radical.utils     : v0.45-2-g82050c5@devel
saga-python       : split-11-g807713c@devel
radical.pilot     : split-28-gae1602f@devel
```

**Comment by andre-merzky** [comment] 2017-03-23 07:30
Thanks, that looks like a bug, I'll check it out.

**Comment by iparask** [comment] 2017-03-24 19:47
Hello Andre, I came up to the same issue.

**Comment by iparask** [comment] 2017-04-02 20:09
Hello Andre,

example 07 failed with the following:

```
create pilot manager                                                          ok
create pilot description [xsede.stampede:64]                                  ok
submit 1 pilot(s)
        .                                                                     ok
stage shared datacaught Exception: invalid dir '/work/03170/tg824689/radical.pilot.sandbox/rp.session.js-172-81.jetstream-cloud.org.iparask.017258.0000/pilot.0000/staging_area': mkdir: cannot create directory ‘/work’: Permission denied
/bin/sh: 2: cd: can't cd to /work/03170/tg824689/radical.pilot.sandbox/rp.session.js-172-81.jetstream-cloud.org.iparask.017258.0000/pilot.0000/staging_area
 (/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +352 (initialize)  :  raise saga.BadParameter ("invalid dir '%s': %s" % (self.url.path, out)))

--------------------------------------------------------------------------------
finalize
```

radical-stack:

```
(RadicalDevel)iparask@js-172-81:~/Repositories/RadicalPilotDevel/examples$ radical-stack
python            : 2.7.6
virtualenv        : /home/iparask/Virtualenv/RadicalDevel
radical.utils     : v0.45-2-g82050c5@devel
saga-python       : split-9-gf9b04d8@devel
radical.pilot     : split-30-g5523e96@fix-issue_1285
radical.analytics : v0.1-115-g31b5065@master
```

Please tell what else you may need

**Comment by andre-merzky** [comment] 2017-04-02 20:19
is `/work/03170/tg824689/` a valid directory on the target resource?  What is the target resource?

**Comment by iparask** [comment] 2017-04-02 20:26
Sorry for not mentioning it earlier. Yes, it is. It is my work directory on Stampede.

The path exists up to ```pilot.0000```. I can give you access if you want

**Comment by andre-merzky** [comment] 2017-04-02 20:28
No, don't need access, thanks.  Seems like this is a `mkdir` instead of a `mkdir -p` somewhere.  Can you please check if any logfile contains the full backtrace, to see where that comes from?

**Comment by iparask** [comment] 2017-04-02 20:36
from bootstrap_1.out:

```
SANDBOX      : /work/03170/tg824689/radical.pilot.sandbox/rp.session.js-172-81.jetstream-cloud.org.iparask.017258.0000/pilot.0000
```

agent_0.log and agent_1.log:
```
 'pilot_sandbox': '/work/03170/tg824689/radical.pilot.sandbox/rp.session.js-172-81.jetstream-cloud.org.iparask.017258.0000/pilot.0000/',
```
Is there any other place I should be looking?

**Comment by andre-merzky** [comment] 2017-04-02 20:44
Hmm, the error seemed to appear originally on the client side, right?  Can you check wherever you store the client logs, please?  Or, if you don't have them, rerun with `RADICAL_VERBOSE=DEBUG`?  Thanks!

**Comment by iparask** [comment] 2017-04-02 20:55
I have the client logs. Which one should I check?

**Comment by andre-merzky** [comment] 2017-04-02 20:56
`grep ERROR *.log` should give you some idea which ones are interesting.

**Comment by iparask** [comment] 2017-04-02 20:58
```
pmgr.0000.log:2017-04-02 16:07:27,282: pmgr.0000           : MainProcess                     : pmgr.0000.ctrl.watcher: ERROR   : pmgr.launching.0 died - shutting down
pmgr.launching.0.child.log:2017-04-02 16:07:27,209: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : TERM : pmgr.launching.0.child run intr
pmgr.launching.0.child.log:2017-04-02 16:07:27,209: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : TERM : pmgr.launching.0.child run final
rp.session.js-172-81.jetstream-cloud.org.iparask.017258.0000.log:2017-04-02 16:07:27,252: rp.session.js-172-81.jetstream-cloud.org.iparask.017258.0000: MainProcess                     : rp.session.js-172-81.jetstream-cloud.org.iparask.017258.0000.ctrl.watcher: ERROR   : control.pubsub.bridge died - shutting down
update.0.child.log:2017-04-02 16:07:27,205: update.0.child      : update.0                        : MainThread     : ERROR   : TERM : update.0.child run intr
update.0.child.log:2017-04-02 16:07:27,205: update.0.child      : update.0                        : MainThread     : ERROR   : TERM : update.0.child run final
```

It also hanged when it tried to close the pilot, so I killed it

**Comment by andre-merzky** [comment] 2017-04-02 21:30
Alas, that error is unrelated...

Let me try to reproduce this.

**Comment by iparask** [comment] 2017-04-02 21:54
I also run it on Comet. It did not produce the same error. The staging_area folder exists in the pilot folder, but there is nothing there.

Client side errors:
```
(RadicalDevel)iparask@js-172-81:~/Repositories/RadicalPilotDevel/examples/rp.session.js-172-81.jetstream-cloud.org.iparask.017258.0002$ grep ERROR *.*
pmgr.launching.0.child.log:2017-04-02 17:49:10,984: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : TERM : pmgr.launching.0.child run exit
pmgr.launching.0.child.log:2017-04-02 17:49:10,984: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : TERM : pmgr.launching.0.child run final
umgr.scheduling.0.child.log:2017-04-02 17:47:33,217: umgr.scheduling.0.child: umgr.scheduling.0               : MainThread     : ERROR   : TERM : umgr.scheduling.0.child run exit
umgr.scheduling.0.child.log:2017-04-02 17:47:33,217: umgr.scheduling.0.child: umgr.scheduling.0               : MainThread     : ERROR   : TERM : umgr.scheduling.0.child run final
umgr.staging.input.0.child.log:2017-04-02 17:47:31,400: umgr.staging.input.0.child: umgr.staging.input.0            : MainThread     : ERROR   : TERM : umgr.staging.input.0.child run exit
umgr.staging.input.0.child.log:2017-04-02 17:47:31,400: umgr.staging.input.0.child: umgr.staging.input.0            : MainThread     : ERROR   : TERM : umgr.staging.input.0.child run final
umgr.staging.output.0.child.log:2017-04-02 17:47:32,207: umgr.staging.output.0.child: umgr.staging.output.0           : MainThread     : ERROR   : TERM : umgr.staging.output.0.child run exit
umgr.staging.output.0.child.log:2017-04-02 17:47:32,207: umgr.staging.output.0.child: umgr.staging.output.0           : MainThread     : ERROR   : TERM : umgr.staging.output.0.child run final
update.0.child.log:2017-04-02 17:49:11,889: update.0.child      : update.0                        : MainThread     : ERROR   : TERM : update.0.child run exit
update.0.child.log:2017-04-02 17:49:11,889: update.0.child      : update.0                        : MainThread     : ERROR   : TERM : update.0.child run final
```

Agent Side errors:
```
[iparask@comet-ln2 pilot.0000]$ grep ERROR *.log
agent.executing.0.child.log:2017-04-02 14:49:16,442: agent.executing.0.child: agent.executing.0               : MainThread     : ERROR   : TERM : agent.executing.0.child run exit
agent.executing.0.child.log:2017-04-02 14:49:16,442: agent.executing.0.child: agent.executing.0               : MainThread     : ERROR   : TERM : agent.executing.0.child run final
agent.scheduling.0.child.log:2017-04-02 14:49:16,442: agent.scheduling.0.child: agent.scheduling.0              : MainThread     : ERROR   : TERM : agent.scheduling.0.child run exit
agent.scheduling.0.child.log:2017-04-02 14:49:16,442: agent.scheduling.0.child: agent.scheduling.0              : MainThread     : ERROR   : TERM : agent.scheduling.0.child run final
agent.staging.input.0.child.log:2017-04-02 14:47:30,941: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : ERROR   : source /home/iparask/radical.pilot.sandbox/rp.session.js-172-81.jetstream-cloud.org.iparask.017258.0002/pilot.0000/staging_area/input.dat does not exist.
agent.staging.input.0.child.log:2017-04-02 14:47:30,941: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : ERROR   : worker <bound method Default.work of <Default(agent.staging.input.0, started)>> failed
agent.staging.input.0.child.log:2017-04-02 14:49:16,442: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : ERROR   : TERM : agent.staging.input.0.child run exit
agent.staging.input.0.child.log:2017-04-02 14:49:16,442: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : ERROR   : TERM : agent.staging.input.0.child run final
agent.staging.output.0.child.log:2017-04-02 14:49:16,442: agent.staging.output.0.child: agent.staging.output.0          : MainThread     : ERROR   : TERM : agent.staging.output.0.child run exit
agent.staging.output.0.child.log:2017-04-02 14:49:16,442: agent.staging.output.0.child: agent.staging.output.0          : MainThread     : ERROR   : TERM : agent.staging.output.0.child run final
update.0.child.log:2017-04-02 14:49:10,715: update.0.child      : update.0                        : MainThread     : ERROR   : TERM : update.0.child run exit
update.0.child.log:2017-04-02 14:49:10,715: update.0.child      : update.0                        : MainThread     : ERROR   : TERM : update.0.child run final
```

**Comment by andre-merzky** [comment] 2017-04-02 21:57
I think I found the problem, working on a fix - thanks!

**Comment by andre-merzky** [comment] 2017-04-02 22:04
Iannis, can you please pull the RP branch and retry?  Thanks!

**Comment by iparask** [comment] 2017-04-02 22:11
Stampede & Comet: OK

**Comment by andre-merzky** [comment] 2017-04-04 17:40
Ok - we'll merge then once you confirm stampede to be happy.

**Comment by andre-merzky** [comment] 2017-04-11 08:15
Vivek, any news on stampede?

**Comment by andre-merzky** [comment] 2017-04-17 10:49
The is merged by now and seems to work ok - closing.

**Closed by andre-merzky** 2017-04-17 10:49 UTC
Labels: bug, data staging
