### ISSUE TITLE
rp on supermic fails-- empty ve

### ISSUE THREAD

**Issue by trje3733** [radical-cybertools/radical.pilot#1383] opened 2017-07-13 21:38 UTC
[bootstrap_1.err.txt](https://github.com/radical-cybertools/radical.pilot/files/1146727/bootstrap_1.err.txt)
[bootstrap_1.out.txt](https://github.com/radical-cybertools/radical.pilot/files/1146728/bootstrap_1.out.txt)

**Comment by vivek-bala** [comment] 2017-07-13 21:43
Thanks Travis. Just to add some more info, this is using RP/v0.45 and the ve_supermic folder is empty. We tried from scratch where we deleted everything in the sandbox but still encountered the same issue.
It is reproducible for Travis, however I cannot produce this error.

**Comment by andre-merzky** [comment] 2017-07-13 21:50
This looks like a quoting issue in the bootstrapper - but that is surprising, since that should only become an issue if the directory names contain a space, which I don't think they do...  Hmmm....

**Comment by andre-merzky** [comment] 2017-07-13 21:53
Can you please run the following commands:

```
export   VIRTENV=/work/trje3733/radical.pilot.sandbox/ve_supermic
echo "VIRTENV : $VIRTENV"
VIRTENV=`(cd $VIRTENV; pwd -P)`
echo "VIRTENV : $VIRTENV (normalized)"
```

and send the output?  Thanks!

**Comment by iparask** [comment] 2017-07-13 21:54
This was a custom ```ls``` issue. It was solve as soon as it was removed.
Is there a way to use absolute paths in the bootstrapper at least?

**Comment by andre-merzky** [comment] 2017-07-13 22:08
Absolute paths: not always, as those are different per resource.  We can start prefixing all commands with `\`, which will disable aliases, but not custom binaries, scripts or `set` commands.  Until  this becomes a frequent issue, I would not put much work into it, honestly...

**Comment by iparask** [comment] 2017-07-13 22:09
Agreed!

**Comment by vivek-bala** [comment] 2017-07-13 22:09
Ok as this issue is fixed, closing.

**Closed by vivek-bala** 2017-07-13 22:09 UTC
Labels: bug
