### ISSUE TITLE
Failure when more than one pilot is used on TITAN

### ISSUE THREAD

**Issue by AA919** [radical-cybertools/radical.pilot#1166] opened 2016-11-29 10:18 UTC
Very strange phenomenon. It happens only when I use more than one pilot.
I have already tried to delete ve_titan.
This is the error that I found in the bootstraps:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/__init__.py", line 18, in <module>
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/session.py", line 23, in <module>
    from .unit_manager    import UnitManager
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 26, in <module>
    from .controller   import UnitManagerController
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/controller/__init__.py", line 10, in <module>
    from pilot_manager_controller import PilotManagerController
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 27, in <module>
    from .pilot_launcher_worker import PilotLauncherWorker
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 27, in <module>
    _, _, _, rp_sdist_name, rp_sdist_path = ru.get_version([root, pwd])
  File "/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/utils/get_version.py", line 85, in get_version
    raise RuntimeError ("Cannot determine version from %s" % paths)
RuntimeError: Cannot determine version from ['/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/controller/../', '/lustre/atlas2/csc108/scratch/aleang9/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/controller']
```

**Comment by andre-merzky** [comment] 2016-12-02 07:02
Seems like the sandbox logging fails, this needs debugging....

**Comment by andre-merzky** [comment] 2016-12-21 12:15
This should be solved with 9f3dd4c96e72d18680e66df7c6f17ea732ad8769

**Comment by andre-merzky** [comment] 2016-12-29 12:59
Comfirmed fixed.  This ticket is left open as the fix is titan specific, but the problem is not.  This needs resolving in general.

One possible solution would be to use the `debug` mode by default and rename it to `local`.   A static VE remains the best option for startup optimization in any case, and we likely don't need the current fine-grained setup options anymore.

**Comment by andre-merzky** [comment] 2017-01-19 10:36
This is considered solved - the proposal above was implemented.

**Closed by andre-merzky** 2017-01-19 10:36 UTC
Labels: bug
