### ISSUE TITLE
RP fails to request more than 1 node on Stampede2

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2058] opened 2020-02-04 19:36 UTC
Confirms `radical-cybertools/radical.entk/issues/416`
```
$ radical-stack 

  python               : 3.7.6
  pythonpath           : 
  virtualenv           : /home/mturilli/Virtualenvs/rp-testing

  radical.pilot        : 1.0.0-v1.0.0-72-g47132d5@devel
  radical.saga         : 1.0.1-v1.0.1-7-g265601d@devel
  radical.utils        : 1.0.0-v1.0.0-31-ga6ecd7a@devel
```
Resource request:
```
        pd_init = {'resource'      : 'xsede.stampede2_ssh',
                   'queue'         : 'normal',
                   'project'       : 'TG-MCB090174',
                   'queue'         : 'development',
                   'access_schema' : 'gsissh',
                   'runtime'       : 60,
                   'exit_on_error' : True,
                   'cores'         : 136 # 68
                  }
```
`agent_0.out`:
```
bootstrap agent agent.0
failed agent.0
--------------
RADICAL Utils -- Stacktrace [171537] [MainThread]

mturilli 171537 167343 48 13:05 ?        00:00:04          \_ rp.agent.0
Traceback (most recent call last):
File "/work/02855/mturilli/stampede2/radical.pilot.sandbox/rp.session.js-156-107.jetstream-cloud.org.mturilli.018296.0001/pilot.0000/rp_install/bin/radical-pilot-agent", line 50, in bootstrap_3
if aid == 'agent.0': agent = rp.Agent_0(cfg, session)
File "/work/02855/mturilli/stampede2/radical.pilot.sandbox/rp.session.js-156-107.jetstream-cloud.org.mturilli.018296.0001/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/agent_0.py", line 67, in __init__
self._configure_rm()
File "/work/02855/mturilli/stampede2/radical.pilot.sandbox/rp.session.js-156-107.jetstream-cloud.org.mturilli.018296.0001/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/agent_0.py", line 137, in _configure_rm
cfg=self._cfg, session=self._session)
File "/work/02855/mturilli/stampede2/radical.pilot.sandbox/rp.session.js-156-107.jetstream-cloud.org.mturilli.018296.0001/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/resource_manager/base.py", line 244, in create
return impl(cfg, session)
File "/work/02855/mturilli/stampede2/radical.pilot.sandbox/rp.session.js-156-107.jetstream-cloud.org.mturilli.018296.0001/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/resource_manager/slurm.py", line 22, in __init__
ResourceManager.__init__(self, cfg, session)
File "/work/02855/mturilli/stampede2/radical.pilot.sandbox/rp.session.js-156-107.jetstream-cloud.org.mturilli.018296.0001/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/resource_manager/base.py", line 172, in __init__
% (str(cores_avail), str(self.requested_cores)))
ValueError: Not enough cores available (68 < 136).
```

**Comment by lee212** [comment] 2020-02-04 20:17
If this fixes, then #1943 will be closed as well, the same root cause.

**Comment by Abdullah-Ghani** [comment] 2020-02-18 19:01
Having the same problem where it is failing to allocate one Node aswell.

```
 pd_init = {'resource'      : 'xsede.stampede2_ssh',
                   'queue'         : 'normal',
                   'project'       : 'TG-MCB090174',
                   'queue'         : 'development',
                   'access_schema' : 'gsissh',
                   'runtime'       : 60,
                   'exit_on_error' : True,
                   'cores'         : 60
                  }

        pdesc = rp.ComputePilotDescription(pd_init)
```

```
$ radical-stack

  python               : 3.7.6
  pythonpath           : 
  virtualenv           : /home/abdullahg/ve

  radical.pilot        : 1.1.0
  radical.saga         : 1.1.0
  radical.utils        : 1.1.1

```

The error:

```
$ grep ERROR *.*
grep: pilot.0000: Is a directory
pmgr.0000.log:1582052148.468 : pmgr.0000            : 11485 : 140688893142784 : ERROR    : [Callback]: pilot 'pilot.0000' failed - exit
pmgr.0000.log:1582052148.468 : pmgr.0000            : 11485 : 140688893142784 : ERROR    : listener died
pmgr_launching.0000.log:1582052148.464 : pmgr_launching.0000  : 11619 : 140494607775488 : ERROR    : bulk launch failed
radical.saga.cpi.log:1582052148.463 : radical.saga.cpi     : 11619 : 140493547632384 : ERROR    : NoSuccess: Couldn't get job id from submitted job! sbatch output:
rp.session.js-156-107.jetstream-cloud.org.abdullahg.018310.0001.log:1582052158.033 : rp.session.js-156-107.jetstream-cloud.org.abdullahg.018310.0001 : 11485 : 140690915473152 : ERROR    : failed to fet profile for pilot.0000

```

**Comment by andre-merzky** [comment] 2020-02-18 22:52
The problem was fixed in the last release.  @Abdullah-Ghani : please reopen the ticket if the problem persists!

**Comment by andre-merzky** [comment] 2020-02-18 22:52
The problem was fixed in the last release.  @Abdullah-Ghani : please reopen the ticket if the problem persists!

**Closed by andre-merzky** 2020-02-18 22:52 UTC
Labels: type:bug
