### ISSUE TITLE
RP/RA timings seem to be incorrect on BW

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1484] opened 2017-10-26 22:28 UTC
Using the following stack to generate profiles:

```
  radical.pilot        : 0.47-v0.46.2-93-g379bd68@feature-gpu
  radical.utils        : 0.47-v0.46-18-g003a153@devel
  saga                 : 0.47-v0.46-23-g21cb4e9@feature-gpu
```

Stack used to analyze the profiles:
```
  radical.analytics    : v0.45.2-7-g6862da3@devel
  radical.pilot        : 0.47-v0.46.2-16-g37aa40b@devel
  radical.utils        : 0.47-v0.46-10-gc515db1@devel
  saga                 : 0.47-v0.46-2-ga48f5f0@devel
```
and
```
  radical.analytics    : v0.45.2-7-g6862da3@devel
  radical.pilot        : 0.46.2
  radical.utils        : 0.46.2
  saga                 : 0.46.1
```

Profiles are available at https://github.com/radical-collaboration/GB-SC18/tree/master/scripts
/esmacs/current/8_replicas.

Please see the notebook at https://github.com/radical-collaboration/GB-SC18/blob/master/scripts/esmacs/current/8_replicas/plotme.ipynb. Note the output of cell 7. The TTE is reported to be greater than
the TTR.

**Comment by mturilli** [comment] 2017-11-01 15:48
This is now critical. A proposal due Nov, 15 2017 and a presentation due Nov, 18 2017 depend on experiments to be performed and plotted on BW.

**Comment by andre-merzky** [comment] 2017-11-03 07:43
At the moment this is considered to be caused by a profile retrieval problem: less precise umgr profile estimates kick in that case.  This waits for confirmation from Vivek now.

As a side note: that code path is gone in the RC, and the cause is now more obvious (times are not estimated anymore, but are simply missing).

**Comment by andre-merzky** [comment] 2017-11-07 20:12
Vivek, any news on this one?

**Comment by vivek-bala** [comment] 2017-11-07 20:29
This ticket was created after both me and Jumana faced the same issue. I think the suggestion, based on some other tickets, was to try the rc/0.46.3 branch. I tried that and was facing https://github.com/radical-cybertools/radical.analytics/issues/54. I think Jumana tried as well and is blocked by https://github.com/radical-cybertools/radical.analytics/issues/56.

**Comment by andre-merzky** [comment] 2017-11-07 20:36
Thanks Vivek.  #54 is closed by now, I'll look into #56.

**Comment by vivek-bala** [comment] 2018-01-24 19:59
@jdakka Do you face any issues in profiling on BW runs? Since we have runs from BW already profiled for the paper, is this issue old?

**Comment by jdakka** [comment] 2018-01-24 20:46
I have been using the `devel` stack `RP`->`RA` in order to profile all my runs.

**Comment by vivek-bala** [comment] 2019-03-28 13:15
IIRC this issue might have been resolved since then. @jdakka can you confirm?
I can't remember correctly if our BW project ends on March 31 (or somewhere around that time) or if BW is getting decommissioned. @mturilli do you happen to remember ?

**Comment by mturilli** [comment] 2019-03-28 15:26
The project has been extended into 2019 but I am not sure whether there is a precise deadline for decommissioning the machine. We support BW only with aprun as ORTE is now officially unsupported. I think we can close this ticket.

**Closed by mturilli** 2019-03-28 15:26 UTC
Labels: priority:critical, type:bug
