### ISSUE TITLE
help on debugging agent startup with split_module_2

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1188] opened 2017-01-18 14:42 UTC
I frequently have agent_0 timing out on agent_1.
From the looks of it, it seems that agent_1 starts correctly though.

```
2017-01-18 09:36:31,838: agent_0             : MainProcess                     : MainThread     : ERROR   : missing for ['agent_1']
```

What further information can I provide?

**Comment by andre-merzky** [comment] 2017-01-18 15:14
This is during the bootstrap, I assume the line(s) before are talking about waiting for `'alive'` messages.  When a new component starts, we make sure it is functional by waiting for it to connect to the control pubsub channel and send a first message, which is only supposed to be sent once it initialized correctly.  That message from `agent_1` seems not to arrive after a timeout, and `agent_0` would shut down.

3 possible reasons: (i) `agent_1` did not come up and thus does not send the message, (ii) the communication bridge failed to transport the message, (iii) `agent_0` missed out on the message.  

(i) you can check in the `agent_1` logs:

```sh
$ grep 'alive' agent_1.log
[...]
agent_1.log:2017-01-13 21:49:02,971: agent_1             : MainProcess                     : MainThread     : DEBUG   : parent sends alive
```

(ii) can be checked in the control bridge log - but that is actually disabled by default, since (a) errors there are very rare, and usually related to deployment issues, and (b) traffic over the bridges is very high.  The log levels for the bridges are thus not controlled over `RADICAL_PILOT_VERBOSE`, but are explicitly set in the agent configs:

```sh
 $ grep control src/radical/pilot/configs/agent_cray.json 
                "control_pubsub"             : {"log_level" : "off"},

``` 

note that logs there are probably somewhat cryptic, since messages are packed via `msgpack`, and thus not always human readable.

(iii) is really rare actually - I don't think I have ever seen message receival missed, unless the component timed out and simply did not check for messages anymore...

So, having said all this: my guess is that either `agent_1` did *not* proceed up to sending the alive message, or the filesystem on titan is slow again, which throws off all timeouts and such (because logging to FS etc), and the message came in too late to be accepted.  Feel free to send me the logs to dig into them...

**Comment by marksantcroos** [comment] 2017-01-18 15:41
The agent is coming up:
```
2017-01-18 09:34:38,385: agent_1             : MainProcess                     : MainThread     : DEBUG   : parent sends alive
```

**Comment by marksantcroos** [comment] 2017-01-18 15:46
So I made a snapshot of the agent_1.* files to tmp after I thought they should be started, and before the agent 0 should see them:
```
> diff tmp/agent_1.out .
1c1,2
< ---------------------------------------------------------------------
---
> ---------[ORTE] Task: 0 is launched! (Job ID: [43748,1])
> ------------
```

Something changed at the top of the logfile, which is interesting ...

**Comment by marksantcroos** [comment] 2017-01-18 15:49
```
/ccs/home/marksant1/radical.pilot.sandbox/rp.session.titan-ext7.marksant1.017184.0007/pilot.0000
```

**Comment by andre-merzky** [comment] 2017-01-18 16:20
thanks for the link!

The first error indicates indeed a missed messsage:

```
634 2017-01-18 10:25:43,896: agent_0             : MainProcess                     : MainThread     : ERROR   : barrier agent_0.ctrl failed 0/1
635 2017-01-18 10:25:43,896: agent_0             : MainProcess                     : MainThread     : ERROR   : waited  for ['agent_1']
636 2017-01-18 10:25:43,896: agent_0             : MainProcess                     : MainThread     : ERROR   : missing for ['agent_1']                                                                           
```

In `agent_0.log`, the sub-agent (`agent_1`) is started in line 239, at 10:23:43, and the main thread then checks the barrier which signals that all expected `alive` messages have arrived.  `agent_1.log` confirms that the alive message is in fact sent out at 10:23:50, but, per above, not received until 10:25:43.

At this point I would indeed enable logging in the bridges to trace the missing message.  Did anything in the agent config change?  I'll try to reproduce this later today...

**Comment by marksantcroos** [comment] 2017-01-18 18:34
> Did anything in the agent config change?

No.

> At this point I would indeed enable logging in the bridges to trace the missing message.
> I'll try to reproduce this later today...

Thanks!

**Comment by andre-merzky** [comment] 2017-01-31 14:43
Mark, this seems to be a race condition between the control channel coming up and the sub-agent sending its alive signal over it.  A strategically placed `sleep 10` seems to reliably avoid this.  I'll commit this for now, but will keep the issue open, as that obviously needs a cleaner solution.

**Comment by marksantcroos** [comment] 2017-01-31 15:52
Ok, will be monitoring if that improves it. Preliminary I would say it aligns with my perception of the issue.
The channels are brought up in different components so we can't do them ordered?

**Comment by andre-merzky** [comment] 2017-01-31 15:57
They actually should be ordered, and we actually do ensure that the bridge processes are up befor carying on.  And, in fact, the same bridge previously transports other alive messages.

My assumption was that the ZMQ threads which take care of message delivery on the sending side wasn't up, not the bridges.  But that seems not the case.

I think the fundamental problem is that we use a pubsub channel for this type of messages, which does not really provide guarantees.  Switching to a queue channel would give us more guarantees and checks, but also makes the channel topology more complex.

I need to look into this a little more to really understand what happens here...

**Comment by andre-merzky** [comment] 2017-03-13 11:59
#1277 is currently tested in this context

**Comment by andre-merzky** [comment] 2017-04-11 09:54
This is considered solved - that was triggered due to duplicated DVM startup (multiple initializers caused duplicated messages).

**Closed by andre-merzky** 2017-04-11 09:54 UTC
Labels: question

**Comment by andre-merzky** [comment] 2017-04-11 10:02
The last comment might be off target: Mark encountered the problem for longer it seems.  We'll keep this closed either way for now.
