### ISSUE TITLE
Jenkins Tests Examples Failing

### ISSUE THREAD

**Issue by itomaldonado** [radical-cybertools/radical.pilot#1351] opened 2017-05-22 14:03 UTC
Examples fail on "devel" branch:

Traceback (most recent call last):
  File "./examples/01_unit_details.py", line 109, in <module>
    unit.exit_code, unit.stdout.strip()[:35]))
AttributeError: 'NoneType' object has no attribute 'strip'

Link: https://jenkins.radical-project.org/job/radical.pilot.devel.test.pr/80/console

**Comment by andre-merzky** [comment] 2017-05-22 14:06
ouch... - sorry, only saw this now...

**Comment by andre-merzky** [comment] 2017-05-22 21:37
jenkins test this please

**Comment by andre-merzky** [comment] 2017-05-23 07:24
I got tests 1-8 to pass now, in a mix of re-creating the sandbox VE on the radical machine and some changes in the examples.  But alas I can't get the MPI test to run - not because of RP, but because of the MPI deployment on our machine.  So, as usual, the test is triggered by the environment, not by RP :-P

mpich and mpi4py are installed, but I see this:

```
> mpiexec -n 2 -host localhost python "helloworld_mpi.py" 
[one:01527] [[36218,0],0] mca_oob_tcp_recv_handler: invalid message type: 15
[one:01527] [[36218,0],0] mca_oob_tcp_recv_handler: invalid message type: 15
--------------------------------------------------------------------------
mpiexec noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
```

If anybody has an idea on how to fix this, please speak up - otherwise I'd suggest to disable the mpi example for the time being...

**Comment by itomaldonado** [comment] 2017-05-24 13:16
So on Jenkins, I am not sure if it is working or not either by the way. Here is the output for `./examples/09_mpi_units.py`. It seems the pilot jobs ran, but the `NoneType` error happened again.

```
===============================
Running: ./examples/09_mpi_units.py
===============================


================================================================================
 Getting Started (RP version split)                                             
================================================================================

/var/lib/jenkins/workspace/radical.pilot.devel.test.pr/.venv-87/local/lib/python2.7/site-packages/libcloud/utils/py3.py:76: UserWarning: Missing backports.ssl_match_hostname package
  warnings.warn("Missing backports.ssl_match_hostname package")
new session: [rp.session.one.jenkins.017308.0044]                              \
database   : [mongodb://localhost:27017/test]                                 ok
read config                                                                   ok

--------------------------------------------------------------------------------
submit pilots                                                                   

create pilot manager                                                          ok
create pilot description [local.localhost:2]                                  ok
submit 1 pilot(s)
        .                                                                     ok

--------------------------------------------------------------------------------
submit units                                                                    

create unit manager                                                           ok
add 1 pilot(s)                                                                ok
create 128 unit description(s)
        ........................................................................
        ........................................................              ok
submit 128 unit(s)
        ........................................................................
        ........................................................              ok

--------------------------------------------------------------------------------
gather results                                                                  

wait for 128 unit(s)
        O/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|
        -|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\|-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|-\|/-\|/-\-|             ok

caught Exception: 'NoneType' object has no attribute 'split'

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.one.jenkins.017308.0044                             \
close unit manager                                                            ok
close pilot manager                                                            \
wait for 1 pilot(s)
        O/-\|/-\|                                                                      ok
                                                                              ok
session lifetime: 142.7s                                                      ok
Traceback (most recent call last):
  File "./examples/09_mpi_units.py", line 117, in <module>
    ','.join(unit.stdout.split('\n'))))
```

**Comment by andre-merzky** [comment] 2017-05-24 13:53
the original problem is not the missing stdout (which leads to the exception), but the fact that the Units fail (which leads to the missing stdout) (the example does not do much in terms of sanity checks - it assumes the units succeed and goes ahead and prints stdout no matter what).  The CU failure in turn is caused by the mpi4py installation problem described above, I'm afraid.

**Comment by itomaldonado** [comment] 2017-05-24 15:00
Gotcha, so it is failing as well.... think we should set-up MPI in the jenkins machine? I can try to take a stab at it, this way we can also test it (which we should)

**Comment by andre-merzky** [comment] 2017-05-24 22:12
Well, the comment from 2 days ago points to my attempt to do exactly that: install mpich and mpi4py.  Alas, the result is not a functional installation, or so it seems.  So either feel free to give it a try to fix, or we disable the MPI tests...

**Comment by ibethune** [comment] 2017-05-29 10:34
@itomaldonado can you spend a bit of time to either get MPI working?

**Comment by ibethune** [comment] 2017-06-05 09:53
So it seems there is no issue with RP itself here, but with the broken/missing MPI installation on the jenkins box.  In this case, I don't consider this to be blocking for the release, although if it can be made to be working, that will streamline the testing process, obviously.

**Comment by andre-merzky** [comment] 2017-06-05 12:27
indeed, that is not an RP issue at this point.

**Comment by mturilli** [comment] 2017-06-05 16:25
As per our discussion at today's RTC meeting @andre-merzky, @itomaldonado, @mturilli should have a 1-hour meeting to decide whether is worth using mpi enabled CUs that use the mpi libraries offered by the remote resources. This meeting should happen in the week between 12-18 June 2017.

**Comment by mturilli** [comment] 2017-07-18 16:06
I add a note about jenkins here as the ticket is still open. Jenkins does not clean after itself. This results in a filled up `/` on `one.radical-project.org`. Offending paths:
* `/var/lib/jenkins/radical.pilot.sandbox`
* `var/log/jenkins` (966GB!)

**Comment by itomaldonado** [comment] 2017-07-18 16:08
I'll take a look at it tonight and make sure Jenkins cleans the project and logs.

**Comment by andre-merzky** [comment] 2017-08-24 10:48
Closing this now, as the original problem was not RP related.  Jenkins cleanup should go into a new ticket if needed...

**Closed by andre-merzky** 2017-08-24 10:48 UTC
Labels: resource
