### ISSUE TITLE
documentation Update

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#1325] opened 2017-04-22 21:06 UTC
We need to update the documentation of radical pilot.

**Comment by andre-merzky** [comment] 2017-04-23 06:26
@georgeha : which I easily can agree to the general observation - can you be more specific on what specifically prompted this ticket?  Thanks.

**Comment by georgeha** [comment] 2017-04-24 02:29
Hi, the main reason of that ticket is to track the changes of radical's pilot API.

**Comment by andre-merzky** [comment] 2017-04-24 06:34
If you don't mind, I'll close this as duplicate of #1292 then - but please let me know if I missed anything!

**Closed by andre-merzky** 2017-04-24 06:34 UTC
Labels: documentation
