### ISSUE TITLE
test_mpi fails on SuperMic

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#769] opened 2015-09-29 20:34 UTC
I tried to run the test_mpi on Supermic nd I got this error:

```
2015-09-29 16:27:17,019: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: ERROR   : Using bootstrapper /home/iparask/TestRepo/testing/lib/python2.7/site-packages/radical/pilot/bootstrapper/default_bootstrapper.sh
Copying bootstrapper 'file://localhost/home/iparask/TestRepo/testing/lib/python2.7/site-packages/radical/pilot/bootstrapper/default_bootstrapper.sh' to agent sandbox (<saga.filesystem.directory.Directory object at 0x7f722e0553d0>).
Copying sdist 'file://localhost/home/iparask/TestRepo/testing/local/lib/python2.7/site-packages/radical/utils/radical.utils-v0.35-39-gfcc9bd9-release-0.36.tar.gz' to sandbox (sftp://supermic.cct-lsu.xsede.org/work/iparaske/radical.pilot.sandbox/rp.session.iparask-virtual-machine.iparask.016707.0007-pilot.0000/).
Copying sdist 'file://localhost/home/iparask/TestRepo/testing/local/lib/python2.7/site-packages/saga/saga-python-v0.35-27-g9997a30-release-0.36.tar.gz' to sandbox (sftp://supermic.cct-lsu.xsede.org/work/iparaske/radical.pilot.sandbox/rp.session.iparask-virtual-machine.iparask.016707.0007-pilot.0000/).
Copying sdist 'file://localhost/home/iparask/TestRepo/testing/local/lib/python2.7/site-packages/radical/pilot/controller/..//radical.pilot-v0.35-479-gb5687c5-release-0.36.tar.gz' to sandbox (sftp://supermic.cct-lsu.xsede.org/work/iparaske/radical.pilot.sandbox/rp.session.iparask-virtual-machine.iparask.016707.0007-pilot.0000/).
Pilot launching failed! (missing agentlaunch method)
Traceback (most recent call last):
  File "/home/iparask/TestRepo/testing/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 595, in run
    if not agent_launch_method: raise RuntimeError("missing agentlaunch method")
RuntimeError: missing agentlaunch method
```

I think something is missing from the configuration file

**Comment by andre-merzky** [comment] 2015-09-29 20:38
Yes, indeed - good catch!

**Comment by iparask** [comment] 2015-09-29 20:46
Just tell me when to restart testing

**Comment by iparask** [comment] 2015-09-30 16:33
Should I pull?

**Comment by andre-merzky** [comment] 2015-09-30 17:47
Thanks for the reminder, Iannis!  This has been fixed in devel (*not* the release branch), so please give that a try, if you don't mind.

**Comment by iparask** [comment] 2015-10-01 16:51
It failed again for a different reason. As soon as I have all the log files, I will update here

**Comment by marksantcroos** [comment] 2015-10-01 16:54
FWIW, I dont expect it to work. Didn't know that test_mpi.py was part of the test protocol though.

**Comment by iparask** [comment] 2015-10-01 17:08
It is indeed, Row 10 of the Google Sheet that Andre created for testing.

**Comment by iparask** [comment] 2015-10-01 17:12
So the MPI job was not even able to run. RP failed while trying to launch.

In the bootstrap_1.err it had: Python 2.7.7 :: Continuum Analytics, Inc.

And that is Anaconda Python.

And I order to verify I did:

```
[iparaske@smic1 rp.session.iparask-virtual-machine.iparask.016709.0002-pilot.0000]$ module load python
[iparaske@smic1 rp.session.iparask-virtual-machine.iparask.016709.0002-pilot.0000]$ python
Python 2.7.7 |Anaconda 2.0.1 (64-bit)| (default, Jun  2 2014, 12:34:02) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
```

It seems that either something has changed significantly in SuperMIC or we should not load module python, because in that case it is:
```
[iparaske@smic1 ~]$ python
Python 2.6.6 (r266:84292, Oct 12 2012, 14:23:48) 
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by marksantcroos** [comment] 2015-10-01 19:15
What is the actual error? I had successful runs with Anaconda before on SuperMIC (not with the current agent though).

**Comment by iparask** [comment] 2015-10-01 19:23
From agent_0.bootstrap_3.log

```
2015-10-01 10:59:51,413: agent_0.bootstrap_3 : MainProcess                     : MainThread     : ERROR   :   File "/worka/work/iparaske/radical.pilot.sandbox/ve_supermic/rp_install/bin/radical-pilot-agent-multicore.py", line 6030, in bootstrap_3
    nodeip = LRMS.hostip(cfg.get('network_interface'))
  File "/worka/work/iparaske/radical.pilot.sandbox/ve_supermic/rp_install/bin/radical-pilot-agent-multicore.py", line 2398, in hostip
    ip = netifaces.ifaddresses(pref)[af][0]['addr']

2015-10-01 10:59:51,472: agent_0.bootstrap_3 : MainProcess                     : MainThread     : INFO    : stop
```

And from agent_0.out:

```

Error running agent: 2
  File "/worka/work/iparaske/radical.pilot.sandbox/ve_supermic/rp_install/bin/radical-pilot-agent-multicore.py", line 6030, in bootstrap_3
    nodeip = LRMS.hostip(cfg.get('network_interface'))
  File "/worka/work/iparaske/radical.pilot.sandbox/ve_supermic/rp_install/bin/radical-pilot-agent-multicore.py", line 2398, in hostip
    ip = netifaces.ifaddresses(pref)[af][0]['addr']

atexit
```

**Comment by iparask** [comment] 2015-10-01 19:28
And local log file:
```
[Callback]: ComputePilot 'pilot.0000' state: PendingActive.
2015-10-01 11:59:51,916: radical.pilot       : MainProcess                     : Thread-1       : INFO    : ComputePilot 'pilot.0000' state changed from 'PendingActive' to 'Failed'.
[Callback]: ComputePilot 'pilot.0000' state: Failed.

STDOUT: None



STDERR: None



LOG   : [<radical.pilot.logentry.Logentry object at 0x7f32984f0990>, <radical.pilot.logentry.Logentry object at 0x7f32984f0f10>, <radical.pilot.logentry.Logentry object at 0x7f32984f07d0>, <radical.pilot.logentry.Logentry object at 0x7f32984f04d0>, <radical.pilot.logentry.Logentry object at 0x7f32984f0b10>, <radical.pilot.logentry.Logentry object at 0x7f3299e48f10>, <radical.pilot.logentry.Logentry object at 0x7f3299e48f90>, <radical.pilot.logentry.Logentry object at 0x7f32984f6ad0>, <radical.pilot.logentry.Logentry object at 0x7f32984f6e50>, <radical.pilot.logentry.Logentry object at 0x7f32984f6dd0>, <radical.pilot.logentry.Logentry object at 0x7f32984f6f10>]


2015-10-01 11:59:51,917: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : pilot manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/iparask/TestRepo/testing/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 328, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/iparask/TestRepo/testing/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 249, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "test_mpi.py", line 25, in pilot_state_cb
    sys.exit (1)
SystemExit: 1
```

**Comment by andre-merzky** [comment] 2015-10-01 23:57
Iannis -- can you please paste a couple of lines before and after the exception stacks?  The actual error message seems missing.  If those lines indicate a missing 'netiface' module, can you please attach `bootstrap_1.out/err`?  Thanks!

**Comment by iparask** [comment] 2015-10-05 18:24
bootstrap_1.err:
```
Python 2.7.7 :: Continuum Analytics, Inc.
```
bootstrap_1.out:
https://gist.github.com/iparask/aab8669bee560df1913e

**Comment by marksantcroos** [comment] 2015-10-08 10:06
Duplicate of #789.

**Closed by marksantcroos** 2015-10-08 10:06 UTC
Labels: bug
