### ISSUE TITLE
Profiles not being created

### ISSUE THREAD

**Issue by chengwill97** [radical-cybertools/radical.pilot#1617] opened 2018-05-10 23:35 UTC
Execution on comet does not generate profiles. This is the current radical-stack

Current radical-stack
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : watershed_rp

  radical.analytics    : 0.47.0
  radical.pilot        : 0.47.10
  radical.utils        : 0.47.4
  saga                 : 0.47.3

**Comment by iparask** [comment] 2018-05-11 00:10
There are no obvious errors in the run. So, I do not know what to check.

**Comment by vivek-bala** [comment] 2018-05-11 14:16
Can you attach the client and agent side RP logs please? With your VE loaded, you can run
```radical-pilot-fetch-logfiles <session id>```. Then you can upload the corresponding rp.session.* folder to this ticket (after tarring/zipping it).

**Comment by iparask** [comment] 2018-05-11 14:19
Yes, I know. We did with Will `grep ERROR *.log` at the agent level and nothing returned. We forgot to mention that the `bootstrapper_1.prof` file exists, as well as, the unit prof files.

@andre-merzky & @vivek-bala is it fair to say that the profiles are not being flushed properly?

**Comment by vivek-bala** [comment] 2018-05-11 14:27
Also I am not sure which branch/commit is effected by this bug, but I think the profile variable was intermediately switched to RADICAL_PROFILE instead of RADICAL_PILOT_PROFILE (this was a bug). You might want to try that in the mean time.

**Comment by andre-merzky** [comment] 2018-05-11 14:27
This is ilkely a duplicate of radical-cybertools/radical.analytics/issues/69.  The workaround is to add 
```
export RADICAL_PROFILE=True
```
to your `~/.bashrc` on the **target** resource.  A fix actually exists, but since it touches environment handling and also overloads an API method, I need to wait for @vivek-bala's confirmation that this does not break EnTK.

**Comment by vivek-bala** [comment] 2018-05-11 14:29
Oops, I thought you were waiting for the confirmation on the reporter issue (which I might not have updated as well but works as intended in EnTK as well). Let me confirm this too.

**Comment by iparask** [comment] 2018-05-11 14:31
I think so. Why the target resource? Would that have the profiles always enabled? 

Nonetheless, @chengwill97 can you add the variable that @andre-merzky provides above and run again?

**Comment by andre-merzky** [comment] 2018-05-11 14:39
target resource:  because its the agent which misses the profiles :-)   And yes, that would have the profiles always enabled.

**Comment by andre-merzky** [comment] 2018-05-11 14:40
> Oops, I thought you were waiting for the confirmation on the reporter issue (which I might not have updated as well but works as intended in EnTK as well). Let me confirm this too.

@vivek-bala : ah, sorry for the confusion!  Both issues are related, thus the fix applies to both.

**Comment by chengwill97** [comment] 2018-05-15 18:39
So, the profiles for the pilot appears, but the session profiles are not showing up. There are no errors, and the stack is the same as listed above.

**Comment by jdakka** [comment] 2018-05-15 18:48
Make sure you add in `export RADICAL_PROFILE=True` and not `RADICAL_PILOT_PROFILE=True` based on this [ticket](https://github.com/radical-cybertools/radical.analytics/issues/69)

**Comment by chengwill97** [comment] 2018-05-15 19:15
Fixed, Thank you!

**Comment by chengwill97** [comment] 2018-05-15 19:17
@andre-merzky should the "RADICAL_PROFILE=True" be in the documentation, too?

**Comment by andre-merzky** [comment] 2018-05-15 19:47
Yes - but the documentation is soon going to change, as the code paths (and the env interpretation) has changed recently.

@vivek-bala : how about that entk testing of yours :)

**Comment by iparask** [comment] 2018-07-03 14:00
I see this behavior while running on Bridges. I run an EnTK script that executes with the following variables enabled:

```
export RADICAL_PILOT_VERBOSE=DEBUG
export RADICAL_ENTK_VERBOSE=DEBUG
export RADICAL_PILOT_PROFILE=TRUE
export RADICAL_ENTK_PROFILE=TRUE
```

The client side profiles from RP are not created. The resource profiles are created because I included `RADICAL_PROFILE=TRUE` on Bridges. Will include to the client side as well. My stack is:
```
  python               : 2.7.15
  pythonpath           :
  virtualenv           : EnTKGPU

  radical.analytics    : v0.45.2-102-gaec2e1d@devel
  radical.entk         : 0.6.1-0.6.0-31-g19668b3@feature-gpu
  radical.pilot        : 0.47.12-v0.47.12-172-g1f829fa@devel
  radical.utils        : 0.47.4-merge-pre_gpu-22-ga942c4b@devel
  saga                 : 0.47.4-v0.47.4-34-g61aec51@fix-issue_679
```

**Comment by iparask** [comment] 2018-07-03 14:23
Update: The client profiles with `RADICAL_PROFILE` works.

**Comment by andre-merzky** [comment] 2018-07-03 18:23
Alas, I can't reproduce this   yet :(

**Closed** 2019-04-01 16:13 UTC
Labels: comp:agent, layer:utils, priority:critical, topic:profiling, type:bug
