### ISSUE TITLE
apparently some state changes in the pilots do not fire callbacks

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#238] opened 2014-07-17 18:20 UTC
While running examples/late_binding.py targeting stampede and trestles, I see the following:
```
$ python late_binding_mt.py 
=========================
53c80cd9dbbb469a8aff8adf
=========================
Late-binding re-scheduling of 0 units
-------
PILOTS
{'53c80cdbdbbb469a8aff8ae1': {'caps': 1, 'state': u'Launching'}}
-------
UNITS
[]
-------
SCHEDULE
{}
Late-binding re-scheduling of 0 units
-------
PILOTS
{'53c80cdbdbbb469a8aff8ae1': {'caps': 1, 'state': u'Launching'},
 '53c80cdbdbbb469a8aff8ae2': {'caps': 16, 'state': u'PendingLaunch'}}
-------
UNITS
[]
-------
SCHEDULE
{}
Late-binding re-scheduling of 0 units
-------
PILOTS
{'53c80cdbdbbb469a8aff8ae1': {'caps': 1, 'state': u'Launching'},
 '53c80cdbdbbb469a8aff8ae2': {'caps': 16, 'state': u'PendingLaunch'},
 '53c80cdddbbb469a8aff8ae3': {'caps': 16, 'state': u'PendingLaunch'}}
-------
UNITS
[]
-------
SCHEDULE
{}
Late-binding re-scheduling of 0 units
-------
PILOTS
{'53c80cdddbbb469a8aff8ae3': {'caps': 16, 'state': u'Active'}}
-------
UNITS
[]
-------
SCHEDULE
{}
```
The failure to schedule a pilot on trestles and the exiting of the pilot on stampede at the end of its walltime did not fire the callback attached to pilots.

**Comment by andre-merzky** [comment] 2015-09-15 09:49
This ticket is a duplicate of #242 by now...

**Closed by andre-merzky** 2015-09-15 09:49 UTC
Labels: testing
