### ISSUE TITLE
3.9 Setup Task Environment

### ISSUE THREAD

**Issue by AninditaChavan** [radical-cybertools/radical.pilot#2520] opened 2022-02-20 01:47 UTC
**Environment variable is not available during task execution:**
```cud = rp.TaskDescription()

cud.executable  = '/bin/echo'
cud.arguments   = ['$RP_TASK_ID greets $TEST']
cud.environment = {'TEST' : 'jabberwocky'}
```

**Output:**
<img width="676" alt="Screen Shot 2022-02-19 at 8 46 57 PM" src="https://user-images.githubusercontent.com/20729102/154825220-d480c1bd-116d-4617-ad1d-b91cd261b9c3.png">

**Comment by kartikmodi** [comment] 2022-02-20 04:20
Debugging information which confirms it's same as #2511 
```
...
export RP_TASK_ID="task.000090"
export RP_TASK_NAME="task.000090"
export RP_PILOT_ID="pilot.0000"
export RP_SESSION_ID="rp.session.debian-x.workstation.019043.0010"
export RP_RESOURCE="local.localhost"
export RP_RESOURCE_SANDBOX="/home/workstation/radical.pilot.sandbox"
export RP_SESSION_SANDBOX="$RP_RESOURCE_SANDBOX/$RP_SESSION_ID/"
export RP_PILOT_SANDBOX="$RP_SESSION_SANDBOX/pilot.0000/"
export RP_TASK_SANDBOX="$RP_PILOT_SANDBOX/task.000090"
export RP_GTOD="$RP_PILOT_SANDBOX/gtod"
export RP_PROF="$RP_PILOT_SANDBOX/prof"
export RP_PROF_TGT="$RP_PILOT_SANDBOX/task.000090/task.000090.prof"

# ------------------------------------------------------------------------------
$RP_PROF exec_start
# task environment

# task env settings
export TEST="jabberwocky"

# ------------------------------------------------------------------------------
# pre-exec commands
$RP_PROF exec_pre

# ------------------------------------------------------------------------------
# execute ranks
$RP_PROF rank_start
case "$RP_RANK" in
    0)
        export OMP_NUM_THREADS="1"
        /bin/echo '$RP_TASK_ID greets $TEST'
        ;;
esac
RP_RET=$?
$RP_PROF rank_stop
...
```
Both the variables in line /bin/echo '$RP_TASK_ID greets $TEST'  are defined in the script but are not evaluated because of single quotes.

**Comment by andre-merzky** [comment] 2022-02-20 21:20
Thanks both - but this is a duplicate of #2511 and I'll close this one in favor of the other one.

**Closed by andre-merzky** 2022-02-20 21:20 UTC
Labels: type:bug, type:documentation
