### ISSUE TITLE
Getting Started Remote on Stampede failed

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#516] opened 2015-03-21 19:09 UTC
When I run the getting_started_remote.py on stampede, I got:

[Callback]: unit unit.000000 on pilot.0000 : Failed.
[Callback]: #      1
stderr: None
* Task unit.000000 state Failed, exit code: None, started: None, finished: None
[Callback]: ComputePilot 'pilot.0000' state: Canceled.

The debug log is here: https://gist.github.com/iparask/c28f0a012e6a08605e28

**Comment by andre-merzky** [comment] 2015-03-21 19:48
Thanks for the report!  Would you happen to have the STDOUT/STDERR for the failing compute units available, from stampede?  It should live in

```
/work/03170/tg824689/radical.pilot.sandbox/rp.session.iparask-virtual-machine.iparask.016515.0002-pilot.0000/unit.000000/
```

I believe.

**Comment by iparask** [comment] 2015-03-21 19:55
STDOUT: 
  5752   5752 330454 f2
  5752   5752 330454 total


STDERR:
Warning: Permanently added 'c557-202,129.114.90.154' (RSA) to the list of known hosts.
wc: f1: No such file or directory

**Comment by andre-merzky** [comment] 2015-03-21 20:29
Ah, thanks - some staging  directive failed.  Let me try to reproduce that on stampede...

**Comment by andre-merzky** [comment] 2015-03-23 11:07
This was caused by a typo, and also apparently some sftp versions decline to copy /dev/null ...  Both issues are fixed now.  Thanks!

**Closed by andre-merzky** 2015-03-23 11:07 UTC
Labels: Devel
