### ISSUE TITLE
Running MD simulations on Bridges2

### ISSUE THREAD

**Issue by akashban** [radical-cybertools/radical.pilot#2618] opened 2022-05-17 23:02 UTC
Hello, 

This a follow up for the previous ticket from our group #2505 . We are able to run our entk scripts on bridges2 now. Thank you. However, there is a issue while running simulations: files are getting stages to the correct directory (task.000X), but the simulation executable is not able to read the files. I am able to view the files using the terminal (essentially, these files physically exist and are not broken symlinks). I have attached the log files. I am unable to attach the our main entk script as it is unpublished material. Please let me know whom I should send the script via email/slack. Thank you. 
[debug.log](https://github.com/radical-cybertools/radical.pilot/files/8712061/debug.log)
[local_sandbox.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/8712062/local_sandbox.tar.gz)
[remote_sandbox-tar.gz](https://github.com/radical-cybertools/radical.pilot/files/8712063/remote_sandbox-tar.gz)
[verbose.log](https://github.com/radical-cybertools/radical.pilot/files/8712064/verbose.log)

**Comment by shantenujha** [comment] 2022-05-18 00:50
Hi Akash, Andre and Matteo would be the "first responders" please.

**Comment by eirrgang** [comment] 2022-05-18 11:03
Note: I have heard of symptoms like this on bridges2, and confirmed similar issues on frontera as being due to overzealous filesystem caching by local code (inserted at the HPC site) attempting to optimize Python jobs by intercepting system calls. Whether or not the reported issue is related, I am personally very interested in hearing about the followup diagnosis and resolution.

**Comment by shantenujha** [comment] 2022-05-18 11:21
@eirrgang thanks. good to know this "appears" to be general. We'll keep this thread updated with progress.

**Comment by eirrgang** [comment] 2022-05-18 11:58
Well, I don't know about "general," but there are definitely several sets of circumstances under which symptoms like this are known to appear. It would be good to improve diagnostic techniques, knowledge of specific systems and circumstances under which symptoms can appear, and to continue to build a catalog of best practices and mitigating strategies.

In case it is useful: on frontera we found that
* files created in one process-memory space might be obscured by cached `stat` results, but appeared to be immediately visible to other processes on the same node that had not already cached a `stat` for said directory,
* the filesystem call cacher could be avoided by the choice of `lmod` environment modules.

On bridges2 (or bridges?), I was unable to reproduce the reported problem, but may have inadvertently resolved it during my attempts to detect it, possibly by introducing a filesystem call that was more atomic or otherwise busted the cache (a same-filesystem `move`, probably).

On other systems (further into the past), similar symptoms could be the result of race conditions due to caching in the filesystem code itself, in which case files may _only_ be visible in the *same* process for some amount of time, and may appear absent in *other* processes for anything from milliseconds to process lifetime. In those cases, mitigation was through choice of filesystem, choice of filesystem mount options (or fileserver configuration), judicious choice of atomic filesystem operations, or grim acceptance and algorithmic workarounds.

So, yeah, I'm very curious.

**Comment by akashban** [comment] 2022-05-18 15:20
HI @andre-merzky , you are correct. I corrected that and I have attached the latest log files here. Actually, its the path to a python code that is required later in the workflow (entk stage 3). Hence, I am still getting an error in the first stage. Let me roughly draw out our workflow: 

Start-> Stage 1: MD pre-processing -> Stage 2: MD simulation -> Stage 3: Analysis -> Many other things -> End. 

The path to the python code (which I messed up initially) is in stage 3. Now, stage 3 can read the python code. However, stage 3 is not executed completely due to the issue in the prior stages, i.e.,  input files are there, but the MD engine is not able to read the files.   

@eirrgang , thank you for your insights. I am also presuming there is some time difference between file staging and MD simulation execution. (may be task.link_input_data vs task.executable ?). Our entk script works fine on my desktop and has worked previously on stampede2. Please let me know how I can help in debugging . Yes, its bridges2. 


[debug.log](https://github.com/radical-cybertools/radical.pilot/files/8717394/debug.log)
[local_sandbox.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/8717395/local_sandbox.tar.gz)
[remote_sandbox.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/8717396/remote_sandbox.tar.gz)
[verbose.log](https://github.com/radical-cybertools/radical.pilot/files/8717398/verbose.log)

**Comment by akashban** [comment] 2022-05-18 17:13
yes mpirun exists:

**[abanerje@bridges2-login014 ~]$ cd /jet/packages/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/openmpi-3.1.6-4mivpbjysgvfx23xkhssavhgkpgpnrug/bin/
[abanerje@bridges2-login014 bin]$ ls**
mpic++   mpifort      ompi-top      orte-ps      oshcxx       shmemCC
mpicc    **mpirun**       opal_wrapper  orterun      oshfort      shmemcxx
mpiCC    ompi-clean   ortecc        orte-server  oshmem_info  shmemfort
mpicxx   ompi-dvm     orte-clean    orte-top     oshrun       shmemrun
mpiexec  ompi_info    orted         oshc++       prun
mpif77   ompi-ps      orte-dvm      oshcc        shmemc++
mpif90   ompi-server  orte-info     oshCC        shmemcc


I ran this: /usr/bin/ssh -o StrictHostKeyChecking=no -o ControlMaster=auto localhost hostname

[abanerje@bridges2-login014 bin]$ /usr/bin/ssh -o StrictHostKeyChecking=no -o ControlMaster=auto localhost hostname
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
abanerje@localhost's password: 
**br014.ib.bridges2.psc.edu**

Does the task runtime have anything to do with the total wall time I asked for? I increased wall time from 30 to 300 seconds. Still get the error.

**Comment by akashban** [comment] 2022-05-18 21:06
Yeah, can I get some help on that? As in, could you share some link on how to do that?

**Comment by eirrgang** [comment] 2022-05-19 11:15
> Yeah, can I get some help on that? As in, could you share some link on how to do that?

Ref https://radicalpilot.readthedocs.io/en/stable/installation.html#ssh

However, you can follow the same sort of procedure while still allowing a pass phrase on your private key by using `ssh-agent` and `ssh-add`. There are plenty of examples online. For a programmatic example (in which the resource is accessible at `ssh://rp@127.0.0.1:2345`) you could put [something like this](https://github.com/SCALE-MS/scale-ms/blob/de6d8295f5c3676b2704646cc9009dd09cff1688/docker/prep-venv.sh#L10) in a shell script to be run interactively (one prompt to log in to the "remote" and a second prompt to unlock the private key at `ssh-add`) before starting the non-interactive part.

**Comment by akashban** [comment] 2022-06-03 22:44
Hi @andre-merzky and @eirrgang , 

I tried out the above link proivded by @eirrgang . It didnt work for bridges2. It worked perfectly for expanse and partially for stampede2 (stampede2 has 2 factor authentication). Is there any way to figure out why bridges2 is not allowing passwordless access after I provide my ssh key. Please let me know if I should provide more details.

**Comment by drawadiagram** [comment] 2022-06-08 17:32
Just wanted to chime in that public key authentication on Bridges2 (adding ecdsa to ~/ssh/keys) worked as of about a month and a half ago. I used it all the time to access directly "ssh mason@bridges2.psc.edu". I tried today and got an error like "Connection on xxx.xxx.xxx.xxx port 22 closed". I think PSC must have changed their auth rules, maybe not XSEDE.

**Comment by akashban** [comment] 2022-06-13 19:33
Hi @andre-merzky and @mturilli , just wanted to follow up on the bridges2 passswordless access issue. Do you have any ideas on how to solve the above?

**Comment by andre-merzky** [comment] 2022-08-01 21:50
@andre-merzky : ping

**Comment by andre-merzky** [comment] 2022-08-29 21:42
Note: passwordless ssh is possible according to xsede support.  Has this been tried, yet?

**Comment by andre-merzky** [comment] 2022-09-12 21:16
Info from Mason: current state is working.  Closing this issue for now, please reopen if needed.

**Closed by andre-merzky** 2022-09-12 21:16 UTC
Labels: type:question, topic:data, layer:rp, priority:medium, comp:agent:executor
