### ISSUE TITLE
failure to have cu events in prof files

### ISSUE THREAD

**Issue by aydinsaribudak** [radical-cybertools/radical.pilot#2110] opened 2020-04-01 20:08 UTC
Hi,
I ran get_started.py example on stampede2 with the following edit in res_dict structure. 
 ```
res_dict = {
resource': 'xsede.stampede2_ssh',
'walltime': 10,
'cpus': 1,
'project': 'TG-MCB090174',
'access_schema': 'gsissh'
 }
```
The "cu" relevant events are not reported in *prof files. Specifically, "cu_exec_start" is not reported in agent_staging_output.0000.prof file. The error message is telling that there is a failure to convert string to float. Error message and stack info are given below. session folder is attached.
Thanks 

python -V
`Python 3.7.6
`

radical-stack:
```
  python               : 3.7.6
  pythonpath           :
  virtualenv           : /home/aydins/env-test

  radical.analytics    : 0.90.7-v0.72.0-35-g4f5242d@devel
  radical.entk         : 1.0.2
  radical.pilot        : 1.2.1
  radical.saga         : 1.2.0
  radical.utils        : 1.2.2
```

Error message:
` agent_staging_output.0000 : 140376 : 47815875069696 : ERROR    : Pre/Post profile read failed: 'could not convert string to float: '
`

[session.zip](https://github.com/radical-cybertools/radical.pilot/files/4417348/session.zip)

**Comment by andre-merzky** [comment] 2020-04-02 09:24
Hi @aydinsaribudak , 

your unit's stderr shows:
```
python3: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory\npython3: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

This message is from the profiler which seems to fail to take the respective events.   Can you please send me the pilot sandbox to check what's going on?  This looks like a conflict between the pilot virtualenv and the environment the unit is running in.

**Comment by aydinsaribudak** [comment] 2020-04-02 11:15
Hi @andre-merzky 
Here is the session folder. I see that it is available within `unit.000000/unit.000000.prof`, but not in `agent_staging_output.0000.prof`

```
login4.stampede2(1027)$ grep -r cu_exec *.*
unit.000000/unit.000000.prof:,cu_exec_start,unit_script,MainThread,unit.000000,AGENT_EXECUTING,
unit.000000/unit.000000.prof:,cu_exec_stop,unit_script,MainThread,unit.000000,AGENT_EXECUTING,
```

[session_sandbox.zip](https://github.com/radical-cybertools/radical.pilot/files/4420599/session_sandbox.zip)

**Comment by andre-merzky** [comment] 2020-04-02 14:04
> `unit.000000/unit.000000.prof:,cu_exec_start,unit_script,MainThread,unit.000000,AGENT_EXECUTING,`

This shows that the profiles are *not* viable - they miss the timestamp as first entry, caused by the python module load problem, and that's what the parser in the output stager stumbles over, thus the error message in that component.

**Comment by andre-merzky** [comment] 2020-04-14 20:31
@andre-merzky : ping

**Comment by andre-merzky** [comment] 2020-04-21 12:05
This should be fixed in RP devel by now - the `gtod` too created by the bootstrapper was reverted to use system utilities instead of Python.

**Comment by mtitov** [comment] 2020-06-23 16:46
resolved (if same issue will appear ticket will be re-opened)

**Closed by mtitov** 2020-06-23 16:46 UTC
Labels: comp:agent:bootstrapper, comp:agent:executor, priority:high, topic:configuration, topic:execution, topic:profiling, type:bug
