### ISSUE TITLE
Cannot install fix/titan_deactivate branch

### ISSUE THREAD

**Issue by jrossyra** [radical-cybertools/radical.pilot#1771] opened 2018-11-30 01:06 UTC
I've had the issue #1755 and am trying to get a working installation again. If look at the stack from @jdakka  in issue #1770 for guidance, I am unable to install the radical pilot branch due to this error:

```
$ git clone https://github.com/radical-cybertools/radical.pilot
$ git fetch --all
$ git checkout -b remotes/origin/fix/titan_deactivate
$ pip install .
(package requirements output)
...
Building wheels for collected packages: radical.pilot
  Running setup.py bdist_wheel for radical.pilot ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-yzmX3R/wheels/e2/86/4b/b04d72e8e7fc1554b728dc65f0675b3f8dec5ee7bc88aa7c23
Successfully built radical.pilot
Installing collected packages: netifaces, radical.pilot
  Found existing installation: netifaces 0.10.6
    Not uninstalling netifaces at /autofs/nccs-svm1_sw/titan/.swci/0-login/opt/spack/20180315/linux-suse_linux11-x86_64/gcc-4.3.4/python-2.7.9-v6ctjewwdx6k2qs7ublexz7gnx457jo5/lib/python2.7/site-packages, outside environment /lustre/atlas/proj-shared/bip149/jrossyra/admd/admdenv
    Can't uninstall 'netifaces'. No files were found to uninstall.
  Can't roll back netifaces; was not uninstalled
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/autofs/nccs-svm1_sw/titan/.swci/0-login/opt/spack/20180315/linux-suse_linux11-x86_64/gcc-4.3.4/python-2.7.9-v6ctjewwdx6k2qs7ublexz7gnx457jo5/lib/python2.7/site-packages/netifaces.so'
Consider using the `--user` option or check the permissions.
```

I've also tried installing the current version 0.50.20 with a plain pip install command, but this resulted in a large number of runtime errors. I can post the issues from the released version if the fix for Titan is supposed to be released, however (if not) it seems if Jumana has this stack working on Titan I should try to test it first.

**Comment by andre-merzky** [comment] 2018-12-03 09:05
Hi John - it looks like pip tries to update a system level module.  Can you please confirm that you have indeed a virtualenv activated when this happens?  If that's the case, please list the commands in a fresh shell so that I can try to reproduce this error.  Thanks!

**Comment by lee212** [comment] 2019-04-02 18:37
@jrossyra, following up this, is this still reproducible once virtualenv enabled?

**Comment by iparask** [comment] 2020-06-23 13:38
Titan does not exist anymore. I'm closing this issue

**Closed by iparask** 2020-06-23 13:38 UTC
Labels: priority:medium, topic:deployment, type:bug
