### ISSUE TITLE
Hanging Jenkins tests

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1318] opened 2017-04-17 13:31 UTC
Hi Manuel, 

I think this is the reason why the tests are hanging:

```
root@one:/var/lib/jenkins/radical.pilot.sandbox/rp.session.one.jenkins.017273.0005/pilot.0000 # cat update.0.child.log
2017-04-17 12:50:42,592: update.0.child      : update.0                        : MainThread     : ERROR   : TERM : update.0.child run exception (timed out)
2017-04-17 12:50:42,592: update.0.child      : update.0                        : MainThread     : ERROR   : loop exception
Traceback (most recent call last):
  File "/var/lib/jenkins/radical.pilot.sandbox/rp.session.one.jenkins.017273.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1297, in run
    self._initialize_child()
  File "/var/lib/jenkins/radical.pilot.sandbox/rp.session.one.jenkins.017273.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 450, in _initialize_child
    self.initialize_child()
  File "/var/lib/jenkins/radical.pilot.sandbox/rp.session.one.jenkins.017273.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/worker/update.py", line 61, in initialize_child
    _, db, _, _, _   = ru.mongodb_connect(self._dburl)
  File "/var/lib/jenkins/radical.pilot.sandbox/rp.session.one.jenkins.017273.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/misc.py", line 94, in mongodb_connect
    mongo = pymongo.MongoClient (host=host, port=port, ssl=ssl)
  File "/var/lib/jenkins/radical.pilot.sandbox/ve_localhost/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 377, in __init__
    raise ConnectionFailure(str(e))
ConnectionFailure: timed out
2017-04-17 12:50:42,594: update.0.child      : update.0                        : MainThread     : ERROR   : TERM : update.0.child run final
```

Looks like the DB connection fails?  The DB URL is set in the agent config as `mongodb://rp:rp@ds015335.mlab.com:15335/rp`.  Firewall issues?

HtH, Andre.

**Comment by ibethune** [comment] 2017-04-17 13:45
Obviously, would be good to fix.  But having working Jenkins setup is not a requirement for the 0.46 release.

**Comment by andre-merzky** [comment] 2017-04-17 13:48
I guess - but we discussed last week if we could offload some of the testing for the termination branch to Jenkins.  Lets pick this up on the call I guess, the merge will probably e a topic anyway?

**Comment by ibethune** [comment] 2017-04-17 13:53
yup

**Comment by itomaldonado** [comment] 2017-04-17 14:14
Added this to the current tests, so it uses localhost mongodb instead of a remote mongodb.
export RADICAL_PILOT_DBURL="mongodb://localhost:27017/test"

**Comment by itomaldonado** [comment] 2017-04-17 14:32
I can confirm it is using the correct mongodb configuration:

`database   : [mongodb://localhost:27017/test]                                 ok`

**Comment by andre-merzky** [comment] 2017-04-17 16:17
Great!  Is there a way to trigger new test runs for the PRs?

**Comment by ibethune** [comment] 2017-04-27 08:27
@itomaldonado if the connectivity issues are resolved can you please close (and answer Andre's question above?)

**Comment by ibethune** [comment] 2017-05-16 08:48
@itomaldonado can you please update this ticket (close if the issue is indeed resolved)

**Comment by ibethune** [comment] 2017-05-22 09:07
Sorry to keep bugging you @itomaldonado - can you please revisit this and update the ticket?

**Comment by itomaldonado** [comment] 2017-05-22 14:22
Ups, like I said I didn't get the notifications for any of radical-cybertools' issues.

So to confirm tests are using the correct database, you can see this line:
```
database   : [mongodb://localhost:27017/test]                                 ok
```

To re-run a test in a PR (as in to force re-testing) you can just comment the following on a PR.
```
jenkins test this please
```

(A bit more...)
Internally out Jenkins instance is looking for the following regex to re-launch a test:
```
^[jJ]enkins\W+test\W+this\W+please.*
```

**Comment by ibethune** [comment] 2017-05-22 14:28
OK, so since this particular problem (DB connectivity) is fixed, we can close this.

**Closed by ibethune** 2017-05-22 14:28 UTC
Labels: testing
