### ISSUE TITLE
Unable to import mkl on Gordon, v0.45.RC2

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1238] opened 2017-02-20 18:57 UTC
On Gordon
```
intel/2013.1.117(49):ERROR:105: Unable to locate a modulefile for 'mkl'
Python 2.7.10
```

**Comment by ibethune** [comment] 2017-02-21 08:35
@mingtaiha can you say a bit more about what you were trying to do when you get this error?  The ticket is not referenced in the testing spreadsheet...

**Comment by mingtaiha** [comment] 2017-02-21 18:39
Sure, sorry for the short description. I was running 09_mpi_units.py. I posted this error in its own ticket as opposed to adding it to [Ticket #1239](https://github.com/radical-cybertools/radical.pilot/issues/1239) as the `mkl error` only occurred on Gordon and not on the other machines (Comet, Stampede):

My radical-stack:
```
(ve)[mingtha@workflow rp]$ radical-stack 
python            : 2.7.5
virtualenv        : /home/mingtha/ve
radical.utils     : v0.45.RC2@detached-v0.45.RC2
saga-python       : v0.45.RC2@detached-v0.45.RC2
radical.pilot     : v0.45.RC2@detached-v0.45.RC2
```

**Comment by andre-merzky** [comment] 2017-02-21 20:13
I tried in a number of different ways, but I did not manage to reproduce this problem.  Could you please check if you not loading `mkl` in your bashrc, or any other modules? Otherwise I am somewhat at a loss - can you please attach a tarball of the pilot sandbox?

**Comment by andre-merzky** [comment] 2017-02-21 20:16
One thing I just realized: I am on a slightly different Python version:

```
# before any module load:
$ module list
Currently Loaded Modulefiles:
  1) intel/2013.1.117   2) mvapich2_ib/1.9    3) gnubase/1.0

$ python -V
Python 2.6.6

$ module load python
python -V
Python 2.7.10
```

How did you get to your version?

**Comment by ibethune** [comment] 2017-02-24 11:52
@mingtaiha - can you check if you can reproduce, and if the mkl module is somehow loading in your user-specific setup.  If it persists, a copy of the pilot sandbox is needed to debug.

**Comment by mingtaiha** [comment] 2017-02-27 15:58
I tried it again and I get the same error. The error can be found in `bootstrap_1.err`. Here's the entire sandbox. I am also unable to import `mpi4py`


[rp.session.workflow.iu.xsede.org.mingtha.017224.0000-pilot.0000.zip](https://github.com/radical-cybertools/radical.pilot/files/804197/rp.session.workflow.iu.xsede.org.mingtha.017224.0000-pilot.0000.zip)

**Comment by andre-merzky** [comment] 2017-02-28 07:20
Can you please send me the following files from `gordon`?

```
~/.login
~/.profile
~/.bashrc
```

Thanks!

**Comment by andre-merzky** [comment] 2017-02-28 07:30
Hmm, also, from the sandbox it seems that the error of not finding the mkl module is non-fatal -- installation otherwise succeeds, and units are being executed, right?  Those fail due to missing mpi4py, but that is a different issue altogether, right?  Do the other (non-mpi-) examples succeed?

**Comment by andre-merzky** [comment] 2017-02-28 09:53
I opened an xsede ticket on the error message - at this point I don't see this stopping v0.45.  Tests on Gordon work ok otherwise.

**Comment by andre-merzky** [comment] 2017-03-02 10:08
XSEDE confirmed this to be a module dependency issue which will be fixed on their end.  Since its non-fatal anyway, this ticket is being closed.

https://portal.xsede.org/group/xup/tickets/-/tickets/63551

**Closed by andre-merzky** 2017-03-02 10:08 UTC
