### ISSUE TITLE
Problems with RP after merging early binding branch and Bridges branch

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1373] opened 2017-06-09 16:35 UTC
Here's the error that I get:
```
(ve.exec_model_exp) mingtha@Ubuntu-1604-xenial-64-minimal:~/repos/affinity_model/exp/res_select$ python baseline_conf.py 
Traceback (most recent call last):
  File "baseline_conf.py", line 6, in <module>
    import radical.pilot as rp
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/__init__.py", line 23, in <module>
    from .session                   import Session
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 29, in <module>
    from . import utils         as rpu
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/utils/__init__.py", line 14, in <module>
    sdist_name, sdist_path = _ru.get_version([_root])
ValueError: need more than 5 values to unpack
```

**Comment by andre-merzky** [comment] 2017-06-09 17:03
you are quick :)  I also had to merge PRs on utils and saga, and that took a while due to a screw-up of mine.  Anyway, that is done now - if you move all three to devel, things should be working again (or so I hope).  Please let me know if not!

**Comment by mingtaiha** [comment] 2017-06-09 17:19
Sorry if I was rushing >.<
I'm testing it now, and will get back to you.

**Comment by andre-merzky** [comment] 2017-06-09 21:45
> Sorry if I was rushing >.<

Ah, no worries, I am grateful that you run the tests! :D

**Comment by andre-merzky** [comment] 2017-06-10 20:48
Ming, let me know if this is still an issue.  A couple of more merges and fixes have been pushed to devel by now...

**Comment by mingtaiha** [comment] 2017-06-11 17:26
The test run is still not finished

**Comment by mingtaiha** [comment] 2017-06-12 14:52
The queue time in Bridges is taking quite a while. It'll be more time before I can get back to you.

**Comment by mingtaiha** [comment] 2017-07-03 04:10
After some long queue waiting times, I get the following error. Bridges is not able to install the packages correctly. I tried remove the existing VM and yet this still doesn't work. This problem is reminiscent of #1353 

[bootstrap_1.out.txt](https://github.com/radical-cybertools/radical.pilot/files/1118393/bootstrap_1.out.txt)

**Comment by andre-merzky** [comment] 2017-07-24 08:21
A  partial fix for this has now been merged into devel.  The problem is not completely solved - but the resource leakage has been reduced to a level where one can create about 60 sessions per application.  I'll open a new ticket as a reminder that this needs more work

**Comment by andre-merzky** [comment] 2017-07-24 08:23
Commented on the wrong ticket :/

**Comment by andre-merzky** [comment] 2017-07-24 08:25
Ming, can you please remove the pilot VE on bridges, and try again with a plain devel stack?  This should be fixed by now.  Thanks.

**Comment by andre-merzky** [comment] 2017-08-07 07:56
closing in favor of #1404

**Closed by andre-merzky** 2017-08-07 07:56 UTC
Labels: testing
