### ISSUE TITLE
Comet - OSError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1352] opened 2017-05-23 15:21 UTC
I get the following error when I running CUs to Comet. A majority of the CUs encounter this error and fail execute correctly, but some CUs to run successfully.

```
2017-05-22 08:06:50,874: agent.executing.0.child: agent.executing.0               : MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/home/mingtha/radical.pilot.sandbox/rp.session.Ubuntu-1604-xenial-64-minimal.mingtha.017307.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 194, in _handle_unit
    self.spawn(launcher=launcher, cu=cu)
  File "/home/mingtha/radical.pilot.sandbox/rp.session.Ubuntu-1604-xenial-64-minimal.mingtha.017307.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 359, in spawn
    creationflags      = 0)
  File "/opt/python/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/python/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
  File "/home/mingtha/radical.pilot.sandbox/rp.session.Ubuntu-1604-xenial-64-minimal.mingtha.017307.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/atfork/atfork.py", line 182, in os_fork_wrapper
    pid = _orig_os_fork()
OSError: [Errno 11] Resource temporarily unavailable
```

My radical-stack
```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/mingtha/ve/ve.exec_model_exp

  radical.analytics    : v0.45@devel
  radical.pilot        : split-105-g9ca8d328@feature-early_binding
  radical.utils        : v0.45-45-gce49d06@feature-managed_process
  saga                 : split-16-g4be5f196@devel
```
I encounter this problem when testing the early binding feature, if that helps.

**Comment by andre-merzky** [comment] 2017-05-30 00:30
I assume this is a duplicate of #1153 - we are hitting ssh process limits in the default configuration in that branch.  Can you give it another try with `xsede.comet_orte`, please?  FWIW, I think this is unrelated to the early binding changes - the CU looks the same to the pilot at that point in time.

**Comment by mingtaiha** [comment] 2017-05-30 00:48
Sure. I'll let you know what I happens.

**Comment by mingtaiha** [comment] 2017-05-30 15:27
I get the following error when I retry

```
2017-05-30 04:39:54,709: radical.saga.cpi    : pmgr.launching.0                : Thread-1       : ERROR   : Exception in job monitoring thread: Insufficient system resources: Insufficient system resources: read from process failed '[Errno 5] Input/output error' : (0:RUNNING: 
25862.0:DONE:0   
29108.0:RUNNING: 
29108.0:DONE:0   
2861.0:RUNNING: 
2861.0:DONE:0   
16300.0:RUNNING: 
16300.0:DONE:0   
27169.0:RUNNING: 
27169.0:DONE:0   
2936.0:RUNNING: 
2936.0:DONE:0   
Shared connection to comet.sdsc.xsede.org closed.
) (()) (/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +64 (translate_exception)  :  e = se.NoSuccess ("Insufficient system resources: %s" % cmsg))
2017-05-30 04:39:54,709: radical.saga.cpi    : pmgr.launching.0                : Thread-1       : ERROR   : Cancel job monitoring for ssh://comet.sdsc.xsede.org/
```

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/utils/process.py", line 487, in run
    self._run()
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/utils/process.py", line 575, in _run
    self._ru_msg_send('terminating')
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/utils/process.py", line 163, in _ru_msg_send
    self._ru_endpoint.send(msg)
error: [Errno 9] Bad file descriptor
```

**Comment by andre-merzky** [comment] 2017-05-31 22:36
To be sure: this is retrying with ORTE, right?  

The second snippet (the traceback on `_ru_endpoint`) is unlikely relevant - that error is already fixed, but that happens during termination.  The original problem seems to be `Shared connection to comet.sdsc.xsede.org closed`.  Can you please check if any ssh sessions to comet are lingering?  From where are you running this?

**Comment by mingtaiha** [comment] 2017-05-31 22:42
I am running with ORTE :), from our group server `two.radical-project.org`. Should I be using the newer branches instead? I am using older branches (see below)

```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/mingtha/ve/ve.exec_model_exp

  radical.analytics    : v0.45@devel
  radical.pilot        : split-105-g9ca8d328@feature-early_binding
  radical.utils        : v0.45-45-gce49d06@feature-managed_process
  saga                 : split-16-g4be5f196@devel
```

**Comment by andre-merzky** [comment] 2017-06-02 07:03
Yes, please do give the current devel stack + ORTE a try, if you don't mind.  Thank you!

**Comment by andre-merzky** [comment] 2017-06-05 14:02
any updates on this one?

**Comment by mingtaiha** [comment] 2017-06-05 14:44
I get the following error when I run with the `devel` stack

```
Caught Exception attribute set is not extensible/private (key pilot) (/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/attributes.py +1068 (_attributes_i_set)  :  raise se.IncorrectState ("attribute set is not extensible/private (key %s)" %  key))
```

My `radical-stack`
```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/mingtha/ve/ve.exec_model_exp

  radical.analytics    : v0.45@devel
  radical.pilot        : split-76-g2a8c6c92@devel
  radical.utils        : v0.45-48-g67704f0@devel
  saga                 : split-16-g4be5f196@devel
```

**Comment by andre-merzky** [comment] 2017-06-05 14:48
Ooops - that is unexpected...  Can you check please if saga@devel is updated?  What is your client machine?

**Comment by mingtaiha** [comment] 2017-06-05 20:13
I pulled the `devel` branches today, and I am running on `two.radical-project.org`

**Comment by andre-merzky** [comment] 2017-06-10 21:20
Ming, if this persists after the flurry of merges, please send me a set of client logfiles.  Thanks!

**Comment by mingtaiha** [comment] 2017-06-11 17:25
Sure

**Comment by andre-merzky** [comment] 2017-06-19 14:24
TODO AM: dig out support exchanges about system limits, send to Shantenu

**Comment by andre-merzky** [comment] 2017-06-20 07:34
I'm afraid I did not manage to dig this out - too many mails laying around with a similar set of topics on ssh exhaustion :-/  The point remains that we do not know the exact set of limits which apply on comet's ssh connections.  I'll open an XSEDE  ticket to get a authorative answer.

**Comment by shantenujha** [comment] 2017-06-20 19:43
OK. Can you send me XSEDE ticket #70364 response you get, and I'll see if there is something I can do to help.

**Closed by shantenujha** 2017-06-20 19:43 UTC

**Comment by andre-merzky** [comment] 2017-07-03 14:10
the limit was  confirmed to be 10 connections per compute node.
